// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ai_generations.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const countAIGenerations = `-- name: CountAIGenerations :one
SELECT count(*) FROM ai_generations
WHERE ($1::uuid IS NULL OR campaign_id = $1::uuid)
`

func (q *Queries) CountAIGenerations(ctx context.Context, campaignID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAIGenerations, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIGeneration = `-- name: CreateAIGeneration :one
INSERT INTO ai_generations (id, provider, model, status, campaign_id, brief, prompt, prompt_version)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
RETURNING id, provider, model, status, campaign_id, brief, prompt, prompt_version, raw_output, parsed, component_count, variant_count, imported_component_ids, imported_variant_ids, usage, error, created_at, parsed_at, imported_at
`

type CreateAIGenerationParams struct {
	ID            uuid.UUID
	Provider      string
	Model         *string
	Status        string
	CampaignID    uuid.NullUUID
	Brief         []byte
	Prompt        string
	PromptVersion string
}

func (q *Queries) CreateAIGeneration(ctx context.Context, arg CreateAIGenerationParams) (AiGeneration, error) {
	row := q.db.QueryRow(ctx, createAIGeneration,
		arg.ID,
		arg.Provider,
		arg.Model,
		arg.Status,
		arg.CampaignID,
		arg.Brief,
		arg.Prompt,
		arg.PromptVersion,
	)
	var i AiGeneration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.CampaignID,
		&i.Brief,
		&i.Prompt,
		&i.PromptVersion,
		&i.RawOutput,
		&i.Parsed,
		&i.ComponentCount,
		&i.VariantCount,
		&i.ImportedComponentIds,
		&i.ImportedVariantIds,
		&i.Usage,
		&i.Error,
		&i.CreatedAt,
		&i.ParsedAt,
		&i.ImportedAt,
	)
	return i, err
}

const getAIGeneration = `-- name: GetAIGeneration :one
SELECT id, provider, model, status, campaign_id, brief, prompt, prompt_version, raw_output, parsed, component_count, variant_count, imported_component_ids, imported_variant_ids, usage, error, created_at, parsed_at, imported_at FROM ai_generations WHERE id = $1
`

func (q *Queries) GetAIGeneration(ctx context.Context, id uuid.UUID) (AiGeneration, error) {
	row := q.db.QueryRow(ctx, getAIGeneration, id)
	var i AiGeneration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.CampaignID,
		&i.Brief,
		&i.Prompt,
		&i.PromptVersion,
		&i.RawOutput,
		&i.Parsed,
		&i.ComponentCount,
		&i.VariantCount,
		&i.ImportedComponentIds,
		&i.ImportedVariantIds,
		&i.Usage,
		&i.Error,
		&i.CreatedAt,
		&i.ParsedAt,
		&i.ImportedAt,
	)
	return i, err
}

const listAIGenerations = `-- name: ListAIGenerations :many
SELECT id, provider, model, status, campaign_id, brief, prompt, prompt_version, raw_output, parsed, component_count, variant_count, imported_component_ids, imported_variant_ids, usage, error, created_at, parsed_at, imported_at FROM ai_generations
WHERE ($1::uuid IS NULL OR campaign_id = $1::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListAIGenerationsParams struct {
	CampaignID uuid.NullUUID
	Off        int32
	Lim        int32
}

func (q *Queries) ListAIGenerations(ctx context.Context, arg ListAIGenerationsParams) ([]AiGeneration, error) {
	rows, err := q.db.Query(ctx, listAIGenerations, arg.CampaignID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiGeneration{}
	for rows.Next() {
		var i AiGeneration
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Status,
			&i.CampaignID,
			&i.Brief,
			&i.Prompt,
			&i.PromptVersion,
			&i.RawOutput,
			&i.Parsed,
			&i.ComponentCount,
			&i.VariantCount,
			&i.ImportedComponentIds,
			&i.ImportedVariantIds,
			&i.Usage,
			&i.Error,
			&i.CreatedAt,
			&i.ParsedAt,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAIGenerationFailed = `-- name: SetAIGenerationFailed :exec
UPDATE ai_generations SET status = 'failed', error = $1 WHERE id = $2
`

type SetAIGenerationFailedParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) SetAIGenerationFailed(ctx context.Context, arg SetAIGenerationFailedParams) error {
	_, err := q.db.Exec(ctx, setAIGenerationFailed, arg.Error, arg.ID)
	return err
}

const setAIGenerationImported = `-- name: SetAIGenerationImported :one
UPDATE ai_generations
SET status = 'imported', imported_component_ids = $1, imported_variant_ids = $2,
    imported_at = now()
WHERE id = $3 AND status = 'parsed'
RETURNING id, provider, model, status, campaign_id, brief, prompt, prompt_version, raw_output, parsed, component_count, variant_count, imported_component_ids, imported_variant_ids, usage, error, created_at, parsed_at, imported_at
`

type SetAIGenerationImportedParams struct {
	ComponentIds []uuid.UUID
	VariantIds   []uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) SetAIGenerationImported(ctx context.Context, arg SetAIGenerationImportedParams) (AiGeneration, error) {
	row := q.db.QueryRow(ctx, setAIGenerationImported, arg.ComponentIds, arg.VariantIds, arg.ID)
	var i AiGeneration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.CampaignID,
		&i.Brief,
		&i.Prompt,
		&i.PromptVersion,
		&i.RawOutput,
		&i.Parsed,
		&i.ComponentCount,
		&i.VariantCount,
		&i.ImportedComponentIds,
		&i.ImportedVariantIds,
		&i.Usage,
		&i.Error,
		&i.CreatedAt,
		&i.ParsedAt,
		&i.ImportedAt,
	)
	return i, err
}

const setAIGenerationParsed = `-- name: SetAIGenerationParsed :one
UPDATE ai_generations
SET status = 'parsed', raw_output = $1, parsed = $2,
    component_count = $3, variant_count = $4,
    usage = COALESCE($5, usage), model = COALESCE($6, model),
    error = NULL, parsed_at = now()
WHERE id = $7
RETURNING id, provider, model, status, campaign_id, brief, prompt, prompt_version, raw_output, parsed, component_count, variant_count, imported_component_ids, imported_variant_ids, usage, error, created_at, parsed_at, imported_at
`

type SetAIGenerationParsedParams struct {
	RawOutput      *string
	Parsed         []byte
	ComponentCount int32
	VariantCount   int32
	Usage          []byte
	Model          *string
	ID             uuid.UUID
}

func (q *Queries) SetAIGenerationParsed(ctx context.Context, arg SetAIGenerationParsedParams) (AiGeneration, error) {
	row := q.db.QueryRow(ctx, setAIGenerationParsed,
		arg.RawOutput,
		arg.Parsed,
		arg.ComponentCount,
		arg.VariantCount,
		arg.Usage,
		arg.Model,
		arg.ID,
	)
	var i AiGeneration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.CampaignID,
		&i.Brief,
		&i.Prompt,
		&i.PromptVersion,
		&i.RawOutput,
		&i.Parsed,
		&i.ComponentCount,
		&i.VariantCount,
		&i.ImportedComponentIds,
		&i.ImportedVariantIds,
		&i.Usage,
		&i.Error,
		&i.CreatedAt,
		&i.ParsedAt,
		&i.ImportedAt,
	)
	return i, err
}
