// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: brand_scan.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const countBrandScanDismissals = `-- name: CountBrandScanDismissals :one
SELECT count(*) FROM brand_scan_dismissals
WHERE ($1::text IS NULL OR group_by = $1)
`

func (q *Queries) CountBrandScanDismissals(ctx context.Context, groupBy *string) (int64, error) {
	row := q.db.QueryRow(ctx, countBrandScanDismissals, groupBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBrandScanDismissal = `-- name: CreateBrandScanDismissal :one
INSERT INTO brand_scan_dismissals (id, group_by, key, note)
VALUES ($1, $2, $3, $4)
RETURNING id, group_by, key, note, created_at
`

type CreateBrandScanDismissalParams struct {
	ID      uuid.UUID
	GroupBy string
	Key     string
	Note    *string
}

func (q *Queries) CreateBrandScanDismissal(ctx context.Context, arg CreateBrandScanDismissalParams) (BrandScanDismissal, error) {
	row := q.db.QueryRow(ctx, createBrandScanDismissal,
		arg.ID,
		arg.GroupBy,
		arg.Key,
		arg.Note,
	)
	var i BrandScanDismissal
	err := row.Scan(
		&i.ID,
		&i.GroupBy,
		&i.Key,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBrandScanDismissal = `-- name: DeleteBrandScanDismissal :execrows
DELETE FROM brand_scan_dismissals WHERE id = $1
`

func (q *Queries) DeleteBrandScanDismissal(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBrandScanDismissal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBrandScanDismissals = `-- name: ListBrandScanDismissals :many
SELECT id, group_by, key, note, created_at FROM brand_scan_dismissals
WHERE ($1::text IS NULL OR group_by = $1)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListBrandScanDismissalsParams struct {
	GroupBy *string
	Off     int32
	Lim     int32
}

func (q *Queries) ListBrandScanDismissals(ctx context.Context, arg ListBrandScanDismissalsParams) ([]BrandScanDismissal, error) {
	rows, err := q.db.Query(ctx, listBrandScanDismissals, arg.GroupBy, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrandScanDismissal{}
	for rows.Next() {
		var i BrandScanDismissal
		if err := rows.Scan(
			&i.ID,
			&i.GroupBy,
			&i.Key,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
