// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: businesses.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const bulkSetSuppressed = `-- name: BulkSetSuppressed :execrows
UPDATE businesses
SET suppressed = $1, updated_at = now()
WHERE id = ANY ($2::uuid[])
  AND suppressed IS DISTINCT FROM $1
`

type BulkSetSuppressedParams struct {
	Suppressed bool
	Ids        []uuid.UUID
}

func (q *Queries) BulkSetSuppressed(ctx context.Context, arg BulkSetSuppressedParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkSetSuppressed, arg.Suppressed, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBusinessByDomain = `-- name: FindBusinessByDomain :one
SELECT id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at FROM businesses
WHERE domain = $1 AND domain IS NOT NULL
ORDER BY created_at
LIMIT 1
`

func (q *Queries) FindBusinessByDomain(ctx context.Context, domain *string) (Business, error) {
	row := q.db.QueryRow(ctx, findBusinessByDomain, domain)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findBusinessByPhoneZip = `-- name: FindBusinessByPhoneZip :one
SELECT id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at FROM businesses
WHERE phone = $1 AND zip = $2
ORDER BY created_at
LIMIT 1
`

type FindBusinessByPhoneZipParams struct {
	Phone *string
	Zip   *string
}

func (q *Queries) FindBusinessByPhoneZip(ctx context.Context, arg FindBusinessByPhoneZipParams) (Business, error) {
	row := q.db.QueryRow(ctx, findBusinessByPhoneZip, arg.Phone, arg.Zip)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findFreshCrawledSibling = `-- name: FindFreshCrawledSibling :one
SELECT b.id
FROM businesses b
WHERE b.domain = $1
  AND b.id <> $2
  AND b.last_crawled_at IS NOT NULL
  AND b.last_crawled_at > now() - make_interval(days => $3::int)
  AND EXISTS (SELECT 1 FROM business_emails be WHERE be.business_id = b.id)
ORDER BY b.last_crawled_at DESC
LIMIT 1
`

type FindFreshCrawledSiblingParams struct {
	Domain     *string
	ExcludeID  uuid.UUID
	MaxAgeDays int32
}

func (q *Queries) FindFreshCrawledSibling(ctx context.Context, arg FindFreshCrawledSiblingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findFreshCrawledSibling, arg.Domain, arg.ExcludeID, arg.MaxAgeDays)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getBusiness = `-- name: GetBusiness :one
SELECT b.id, b.place_id, b.name, b.category, b.address, b.city, b.state, b.zip, b.phone, b.website, b.domain, b.rating, b.reviews, b.lat, b.lng, b.raw, b.first_job_id, b.suppressed, b.notes, b.last_crawled_at, b.created_at, b.updated_at,
       (SELECT j.name FROM jobs j WHERE j.id = b.first_job_id)::text AS first_job_name,
       COALESCE((SELECT be.email FROM business_emails be
                 WHERE be.business_id = b.id
                 ORDER BY be.is_primary DESC, be.found_at, be.email LIMIT 1), '')::text AS primary_email,
       COALESCE((SELECT be.source FROM business_emails be
                 WHERE be.business_id = b.id
                 ORDER BY be.is_primary DESC, be.found_at, be.email LIMIT 1), '')::text AS primary_email_source,
       (SELECT count(*) FROM business_emails be WHERE be.business_id = b.id)::bigint AS emails_count
FROM businesses b
WHERE b.id = $1
`

type GetBusinessRow struct {
	ID                 uuid.UUID
	PlaceID            *string
	Name               string
	Category           *string
	Address            *string
	City               *string
	State              *string
	Zip                *string
	Phone              *string
	Website            *string
	Domain             *string
	Rating             *float64
	Reviews            *int32
	Lat                *float64
	Lng                *float64
	Raw                []byte
	FirstJobID         uuid.NullUUID
	Suppressed         bool
	Notes              *string
	LastCrawledAt      *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	FirstJobName       string
	PrimaryEmail       string
	PrimaryEmailSource string
	EmailsCount        int64
}

func (q *Queries) GetBusiness(ctx context.Context, id uuid.UUID) (GetBusinessRow, error) {
	row := q.db.QueryRow(ctx, getBusiness, id)
	var i GetBusinessRow
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstJobName,
		&i.PrimaryEmail,
		&i.PrimaryEmailSource,
		&i.EmailsCount,
	)
	return i, err
}

const insertBusiness = `-- name: InsertBusiness :one
INSERT INTO businesses (id, place_id, name, category, address, city, state, zip, phone, website,
                        domain, rating, reviews, lat, lng, raw, first_job_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12,
        $13, $14, $15, $16,
        $17)
RETURNING id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at
`

type InsertBusinessParams struct {
	ID         uuid.UUID
	PlaceID    *string
	Name       string
	Category   *string
	Address    *string
	City       *string
	State      *string
	Zip        *string
	Phone      *string
	Website    *string
	Domain     *string
	Rating     *float64
	Reviews    *int32
	Lat        *float64
	Lng        *float64
	Raw        []byte
	FirstJobID uuid.NullUUID
}

func (q *Queries) InsertBusiness(ctx context.Context, arg InsertBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, insertBusiness,
		arg.ID,
		arg.PlaceID,
		arg.Name,
		arg.Category,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Phone,
		arg.Website,
		arg.Domain,
		arg.Rating,
		arg.Reviews,
		arg.Lat,
		arg.Lng,
		arg.Raw,
		arg.FirstJobID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobCrawlTargets = `-- name: ListJobCrawlTargets :many
SELECT b.id, b.website, b.domain
FROM job_results jr
         JOIN businesses b ON b.id = jr.business_id
WHERE jr.job_id = $1
  AND b.website IS NOT NULL
  AND b.website <> ''
  AND NOT EXISTS (SELECT 1 FROM business_emails be WHERE be.business_id = b.id)
ORDER BY b.id
`

type ListJobCrawlTargetsRow struct {
	ID      uuid.UUID
	Website *string
	Domain  *string
}

func (q *Queries) ListJobCrawlTargets(ctx context.Context, jid uuid.UUID) ([]ListJobCrawlTargetsRow, error) {
	rows, err := q.db.Query(ctx, listJobCrawlTargets, jid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobCrawlTargetsRow{}
	for rows.Next() {
		var i ListJobCrawlTargetsRow
		if err := rows.Scan(&i.ID, &i.Website, &i.Domain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBusinessCrawled = `-- name: MarkBusinessCrawled :exec
UPDATE businesses SET last_crawled_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkBusinessCrawled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBusinessCrawled, id)
	return err
}

const updateBusinessFlags = `-- name: UpdateBusinessFlags :one
UPDATE businesses
SET suppressed = COALESCE($1, suppressed),
    notes      = CASE WHEN $2::boolean THEN $3 ELSE notes END,
    updated_at = now()
WHERE id = $4
RETURNING id
`

type UpdateBusinessFlagsParams struct {
	Suppressed *bool
	SetNotes   bool
	Notes      *string
	ID         uuid.UUID
}

func (q *Queries) UpdateBusinessFlags(ctx context.Context, arg UpdateBusinessFlagsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateBusinessFlags,
		arg.Suppressed,
		arg.SetNotes,
		arg.Notes,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateBusinessFromListing = `-- name: UpdateBusinessFromListing :one
UPDATE businesses
SET name       = $1,
    category   = COALESCE($2, category),
    address    = COALESCE($3, address),
    city       = COALESCE($4, city),
    state      = COALESCE($5, state),
    zip        = COALESCE($6, zip),
    phone      = COALESCE($7, phone),
    website    = COALESCE($8, website),
    domain     = COALESCE($9, domain),
    rating     = COALESCE($10, rating),
    reviews    = COALESCE($11, reviews),
    lat        = COALESCE($12, lat),
    lng        = COALESCE($13, lng),
    updated_at = now()
WHERE id = $14
RETURNING id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at
`

type UpdateBusinessFromListingParams struct {
	Name     string
	Category *string
	Address  *string
	City     *string
	State    *string
	Zip      *string
	Phone    *string
	Website  *string
	Domain   *string
	Rating   *float64
	Reviews  *int32
	Lat      *float64
	Lng      *float64
	ID       uuid.UUID
}

func (q *Queries) UpdateBusinessFromListing(ctx context.Context, arg UpdateBusinessFromListingParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusinessFromListing,
		arg.Name,
		arg.Category,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Phone,
		arg.Website,
		arg.Domain,
		arg.Rating,
		arg.Reviews,
		arg.Lat,
		arg.Lng,
		arg.ID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBusinessByPlaceID = `-- name: UpsertBusinessByPlaceID :one
INSERT INTO businesses (id, place_id, name, category, address, city, state, zip, phone, website,
                        domain, rating, reviews, lat, lng, raw, first_job_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12,
        $13, $14, $15, $16,
        $17)
ON CONFLICT (place_id) DO UPDATE
    SET name       = EXCLUDED.name,
        category   = COALESCE(EXCLUDED.category, businesses.category),
        address    = COALESCE(EXCLUDED.address, businesses.address),
        city       = COALESCE(EXCLUDED.city, businesses.city),
        state      = COALESCE(EXCLUDED.state, businesses.state),
        zip        = COALESCE(EXCLUDED.zip, businesses.zip),
        phone      = COALESCE(EXCLUDED.phone, businesses.phone),
        website    = COALESCE(EXCLUDED.website, businesses.website),
        domain     = COALESCE(EXCLUDED.domain, businesses.domain),
        rating     = COALESCE(EXCLUDED.rating, businesses.rating),
        reviews    = COALESCE(EXCLUDED.reviews, businesses.reviews),
        lat        = COALESCE(EXCLUDED.lat, businesses.lat),
        lng        = COALESCE(EXCLUDED.lng, businesses.lng),
        raw        = COALESCE(EXCLUDED.raw, businesses.raw),
        updated_at = now()
RETURNING id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at
`

type UpsertBusinessByPlaceIDParams struct {
	ID         uuid.UUID
	PlaceID    *string
	Name       string
	Category   *string
	Address    *string
	City       *string
	State      *string
	Zip        *string
	Phone      *string
	Website    *string
	Domain     *string
	Rating     *float64
	Reviews    *int32
	Lat        *float64
	Lng        *float64
	Raw        []byte
	FirstJobID uuid.NullUUID
}

func (q *Queries) UpsertBusinessByPlaceID(ctx context.Context, arg UpsertBusinessByPlaceIDParams) (Business, error) {
	row := q.db.QueryRow(ctx, upsertBusinessByPlaceID,
		arg.ID,
		arg.PlaceID,
		arg.Name,
		arg.Category,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Phone,
		arg.Website,
		arg.Domain,
		arg.Rating,
		arg.Reviews,
		arg.Lat,
		arg.Lng,
		arg.Raw,
		arg.FirstJobID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
