// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: businesses.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const bulkSetSuppressed = `-- name: BulkSetSuppressed :execrows
UPDATE businesses
SET suppressed = $1, updated_at = now()
WHERE id = ANY ($2::uuid[])
  AND suppressed IS DISTINCT FROM $1
`

type BulkSetSuppressedParams struct {
	Suppressed bool
	Ids        []uuid.UUID
}

func (q *Queries) BulkSetSuppressed(ctx context.Context, arg BulkSetSuppressedParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkSetSuppressed, arg.Suppressed, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fillBusinessPhone = `-- name: FillBusinessPhone :execrows
UPDATE businesses
SET phone = $1, updated_at = now()
WHERE id = $2
  AND (phone IS NULL OR phone = '')
`

type FillBusinessPhoneParams struct {
	Phone *string
	ID    uuid.UUID
}

// Sets the phone number of a business that has none; a number from the Maps provider
// is never overwritten.
func (q *Queries) FillBusinessPhone(ctx context.Context, arg FillBusinessPhoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, fillBusinessPhone, arg.Phone, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBusinessByDomain = `-- name: FindBusinessByDomain :one
SELECT id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at, name_key, name_prefixes, domain_suffixes FROM businesses
WHERE domain = $1 AND domain IS NOT NULL
ORDER BY created_at
LIMIT 1
`

func (q *Queries) FindBusinessByDomain(ctx context.Context, domain *string) (Business, error) {
	row := q.db.QueryRow(ctx, findBusinessByDomain, domain)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
		&i.NamePrefixes,
		&i.DomainSuffixes,
	)
	return i, err
}

const findBusinessByPhoneZip = `-- name: FindBusinessByPhoneZip :one
SELECT id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at, name_key, name_prefixes, domain_suffixes FROM businesses
WHERE phone = $1 AND zip = $2
ORDER BY created_at
LIMIT 1
`

type FindBusinessByPhoneZipParams struct {
	Phone *string
	Zip   *string
}

func (q *Queries) FindBusinessByPhoneZip(ctx context.Context, arg FindBusinessByPhoneZipParams) (Business, error) {
	row := q.db.QueryRow(ctx, findBusinessByPhoneZip, arg.Phone, arg.Zip)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
		&i.NamePrefixes,
		&i.DomainSuffixes,
	)
	return i, err
}

const getBusiness = `-- name: GetBusiness :one
SELECT b.id, b.place_id, b.name, b.category, b.address, b.city, b.state, b.zip, b.phone, b.website, b.domain, b.rating, b.reviews, b.lat, b.lng, b.raw, b.first_job_id, b.suppressed, b.notes, b.last_crawled_at, b.created_at, b.updated_at, b.name_key, b.name_prefixes, b.domain_suffixes,
       (SELECT j.name FROM jobs j WHERE j.id = b.first_job_id)::text AS first_job_name,
       COALESCE((SELECT be.email FROM business_emails be
                 WHERE be.business_id = b.id
                 ORDER BY be.is_primary DESC, be.found_at, be.email LIMIT 1), '')::text AS primary_email,
       COALESCE((SELECT be.source FROM business_emails be
                 WHERE be.business_id = b.id
                 ORDER BY be.is_primary DESC, be.found_at, be.email LIMIT 1), '')::text AS primary_email_source,
       (SELECT count(*) FROM business_emails be WHERE be.business_id = b.id)::bigint AS emails_count
FROM businesses b
WHERE b.id = $1
`

type GetBusinessRow struct {
	ID                 uuid.UUID
	PlaceID            *string
	Name               string
	Category           *string
	Address            *string
	City               *string
	State              *string
	Zip                *string
	Phone              *string
	Website            *string
	Domain             *string
	Rating             *float64
	Reviews            *int32
	Lat                *float64
	Lng                *float64
	Raw                []byte
	FirstJobID         uuid.NullUUID
	Suppressed         bool
	Notes              *string
	LastCrawledAt      *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	NameKey            *string
	NamePrefixes       []string
	DomainSuffixes     []string
	FirstJobName       string
	PrimaryEmail       string
	PrimaryEmailSource string
	EmailsCount        int64
}

func (q *Queries) GetBusiness(ctx context.Context, id uuid.UUID) (GetBusinessRow, error) {
	row := q.db.QueryRow(ctx, getBusiness, id)
	var i GetBusinessRow
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
		&i.NamePrefixes,
		&i.DomainSuffixes,
		&i.FirstJobName,
		&i.PrimaryEmail,
		&i.PrimaryEmailSource,
		&i.EmailsCount,
	)
	return i, err
}

const insertBusiness = `-- name: InsertBusiness :one
INSERT INTO businesses (id, place_id, name, category, address, city, state, zip, phone, website,
                        domain, rating, reviews, lat, lng, raw, first_job_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12,
        $13, $14, $15, $16,
        $17)
RETURNING id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at, name_key, name_prefixes, domain_suffixes
`

type InsertBusinessParams struct {
	ID         uuid.UUID
	PlaceID    *string
	Name       string
	Category   *string
	Address    *string
	City       *string
	State      *string
	Zip        *string
	Phone      *string
	Website    *string
	Domain     *string
	Rating     *float64
	Reviews    *int32
	Lat        *float64
	Lng        *float64
	Raw        []byte
	FirstJobID uuid.NullUUID
}

func (q *Queries) InsertBusiness(ctx context.Context, arg InsertBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, insertBusiness,
		arg.ID,
		arg.PlaceID,
		arg.Name,
		arg.Category,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Phone,
		arg.Website,
		arg.Domain,
		arg.Rating,
		arg.Reviews,
		arg.Lat,
		arg.Lng,
		arg.Raw,
		arg.FirstJobID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
		&i.NamePrefixes,
		&i.DomainSuffixes,
	)
	return i, err
}

const listFreshCrawledSiblings = `-- name: ListFreshCrawledSiblings :many
SELECT b.id, b.website
FROM businesses b
WHERE b.domain = $1
  AND lower(regexp_replace(regexp_replace(b.website, '[?#].*$', ''), '^https?://(www\.)?|/+$', '', 'gi'))
      = $2::text
  AND b.id <> $3
  AND b.last_crawled_at IS NOT NULL
  AND b.last_crawled_at > now() - make_interval(days => $4::int)
  AND EXISTS (SELECT 1 FROM business_emails be WHERE be.business_id = b.id)
ORDER BY b.last_crawled_at DESC
LIMIT 200
`

type ListFreshCrawledSiblingsParams struct {
	Domain     *string
	PathKey    string
	ExcludeID  uuid.UUID
	MaxAgeDays int32
}

type ListFreshCrawledSiblingsRow struct {
	ID      uuid.UUID
	Website *string
}

// Candidates for a sibling: another listing of the same website, not merely the same
// domain. A city or a franchise often hosts one page per location under a single
// domain, and each page carries its own address. This matches on the path only
// (ignoring scheme, "www.", the query string and trailing slashes, the way
// business.WebsitePathKey computes the argument); the caller compares the query
// string, which often names the page ("profile.php?id=…", "detail.aspx?s=…").
func (q *Queries) ListFreshCrawledSiblings(ctx context.Context, arg ListFreshCrawledSiblingsParams) ([]ListFreshCrawledSiblingsRow, error) {
	rows, err := q.db.Query(ctx, listFreshCrawledSiblings,
		arg.Domain,
		arg.PathKey,
		arg.ExcludeID,
		arg.MaxAgeDays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFreshCrawledSiblingsRow{}
	for rows.Next() {
		var i ListFreshCrawledSiblingsRow
		if err := rows.Scan(&i.ID, &i.Website); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobCrawlTargets = `-- name: ListJobCrawlTargets :many
SELECT b.id, b.website, b.domain
FROM job_results jr
         JOIN businesses b ON b.id = jr.business_id
WHERE jr.job_id = $1
  AND b.website IS NOT NULL
  AND b.website <> ''
  AND (($2::bool
        AND NOT EXISTS (SELECT 1 FROM business_emails be WHERE be.business_id = b.id))
    OR ($3::bool
        AND NOT EXISTS (SELECT 1 FROM business_socials bs WHERE bs.business_id = b.id)))
ORDER BY b.id
`

type ListJobCrawlTargetsParams struct {
	Jid         uuid.UUID
	WantEmails  bool
	WantSocials bool
}

type ListJobCrawlTargetsRow struct {
	ID      uuid.UUID
	Website *string
	Domain  *string
}

// The job's businesses with a website that still lack what the crawl looks for.
func (q *Queries) ListJobCrawlTargets(ctx context.Context, arg ListJobCrawlTargetsParams) ([]ListJobCrawlTargetsRow, error) {
	rows, err := q.db.Query(ctx, listJobCrawlTargets, arg.Jid, arg.WantEmails, arg.WantSocials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobCrawlTargetsRow{}
	for rows.Next() {
		var i ListJobCrawlTargetsRow
		if err := rows.Scan(&i.ID, &i.Website, &i.Domain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobSocialTargets = `-- name: ListJobSocialTargets :many
SELECT DISTINCT ON (b.id) b.id, bs.url
FROM job_results jr
         JOIN businesses b ON b.id = jr.business_id
         JOIN business_socials bs ON bs.business_id = b.id AND bs.network = $1
WHERE jr.job_id = $2
  AND (NOT $3::bool
    OR NOT EXISTS (SELECT 1 FROM business_emails be WHERE be.business_id = b.id))
ORDER BY b.id, bs.found_at, bs.url
`

type ListJobSocialTargetsParams struct {
	Network          string
	Jid              uuid.UUID
	MissingEmailOnly bool
}

type ListJobSocialTargetsRow struct {
	ID  uuid.UUID
	Url string
}

// The job's businesses with a profile on one network, and that profile (the first one
// found when the site links to several), optionally only those still without an email.
func (q *Queries) ListJobSocialTargets(ctx context.Context, arg ListJobSocialTargetsParams) ([]ListJobSocialTargetsRow, error) {
	rows, err := q.db.Query(ctx, listJobSocialTargets, arg.Network, arg.Jid, arg.MissingEmailOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobSocialTargetsRow{}
	for rows.Next() {
		var i ListJobSocialTargetsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBusinessCrawled = `-- name: MarkBusinessCrawled :exec
UPDATE businesses SET last_crawled_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkBusinessCrawled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBusinessCrawled, id)
	return err
}

const updateBusinessFlags = `-- name: UpdateBusinessFlags :one
UPDATE businesses
SET suppressed = COALESCE($1, suppressed),
    notes      = CASE WHEN $2::boolean THEN $3 ELSE notes END,
    updated_at = now()
WHERE id = $4
RETURNING id
`

type UpdateBusinessFlagsParams struct {
	Suppressed *bool
	SetNotes   bool
	Notes      *string
	ID         uuid.UUID
}

func (q *Queries) UpdateBusinessFlags(ctx context.Context, arg UpdateBusinessFlagsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateBusinessFlags,
		arg.Suppressed,
		arg.SetNotes,
		arg.Notes,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateBusinessFromListing = `-- name: UpdateBusinessFromListing :one
UPDATE businesses
SET name       = $1,
    category   = COALESCE($2, category),
    address    = COALESCE($3, address),
    city       = COALESCE($4, city),
    state      = COALESCE($5, state),
    zip        = COALESCE($6, zip),
    phone      = COALESCE($7, phone),
    website    = COALESCE($8, website),
    domain     = COALESCE($9, domain),
    rating     = COALESCE($10, rating),
    reviews    = COALESCE($11, reviews),
    lat        = COALESCE($12, lat),
    lng        = COALESCE($13, lng),
    updated_at = now()
WHERE id = $14
RETURNING id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at, name_key, name_prefixes, domain_suffixes
`

type UpdateBusinessFromListingParams struct {
	Name     string
	Category *string
	Address  *string
	City     *string
	State    *string
	Zip      *string
	Phone    *string
	Website  *string
	Domain   *string
	Rating   *float64
	Reviews  *int32
	Lat      *float64
	Lng      *float64
	ID       uuid.UUID
}

func (q *Queries) UpdateBusinessFromListing(ctx context.Context, arg UpdateBusinessFromListingParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusinessFromListing,
		arg.Name,
		arg.Category,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Phone,
		arg.Website,
		arg.Domain,
		arg.Rating,
		arg.Reviews,
		arg.Lat,
		arg.Lng,
		arg.ID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
		&i.NamePrefixes,
		&i.DomainSuffixes,
	)
	return i, err
}

const upsertBusinessByPlaceID = `-- name: UpsertBusinessByPlaceID :one
INSERT INTO businesses (id, place_id, name, category, address, city, state, zip, phone, website,
                        domain, rating, reviews, lat, lng, raw, first_job_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12,
        $13, $14, $15, $16,
        $17)
ON CONFLICT (place_id) DO UPDATE
    SET name       = EXCLUDED.name,
        category   = COALESCE(EXCLUDED.category, businesses.category),
        address    = COALESCE(EXCLUDED.address, businesses.address),
        city       = COALESCE(EXCLUDED.city, businesses.city),
        state      = COALESCE(EXCLUDED.state, businesses.state),
        zip        = COALESCE(EXCLUDED.zip, businesses.zip),
        phone      = COALESCE(EXCLUDED.phone, businesses.phone),
        website    = COALESCE(EXCLUDED.website, businesses.website),
        domain     = COALESCE(EXCLUDED.domain, businesses.domain),
        rating     = COALESCE(EXCLUDED.rating, businesses.rating),
        reviews    = COALESCE(EXCLUDED.reviews, businesses.reviews),
        lat        = COALESCE(EXCLUDED.lat, businesses.lat),
        lng        = COALESCE(EXCLUDED.lng, businesses.lng),
        raw        = COALESCE(EXCLUDED.raw, businesses.raw),
        updated_at = now()
RETURNING id, place_id, name, category, address, city, state, zip, phone, website, domain, rating, reviews, lat, lng, raw, first_job_id, suppressed, notes, last_crawled_at, created_at, updated_at, name_key, name_prefixes, domain_suffixes
`

type UpsertBusinessByPlaceIDParams struct {
	ID         uuid.UUID
	PlaceID    *string
	Name       string
	Category   *string
	Address    *string
	City       *string
	State      *string
	Zip        *string
	Phone      *string
	Website    *string
	Domain     *string
	Rating     *float64
	Reviews    *int32
	Lat        *float64
	Lng        *float64
	Raw        []byte
	FirstJobID uuid.NullUUID
}

func (q *Queries) UpsertBusinessByPlaceID(ctx context.Context, arg UpsertBusinessByPlaceIDParams) (Business, error) {
	row := q.db.QueryRow(ctx, upsertBusinessByPlaceID,
		arg.ID,
		arg.PlaceID,
		arg.Name,
		arg.Category,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Phone,
		arg.Website,
		arg.Domain,
		arg.Rating,
		arg.Reviews,
		arg.Lat,
		arg.Lng,
		arg.Raw,
		arg.FirstJobID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Phone,
		&i.Website,
		&i.Domain,
		&i.Rating,
		&i.Reviews,
		&i.Lat,
		&i.Lng,
		&i.Raw,
		&i.FirstJobID,
		&i.Suppressed,
		&i.Notes,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
		&i.NamePrefixes,
		&i.DomainSuffixes,
	)
	return i, err
}
