// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: business_emails.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const clearPrimaryEmail = `-- name: ClearPrimaryEmail :exec
UPDATE business_emails SET is_primary = false WHERE business_id = $1 AND is_primary
`

func (q *Queries) ClearPrimaryEmail(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryEmail, businessID)
	return err
}

const insertBusinessEmail = `-- name: InsertBusinessEmail :one
INSERT INTO business_emails (id, business_id, email, source, page_url, is_primary)
VALUES ($1, $2, $3, $4,
        $5, false)
ON CONFLICT (business_id, email) DO UPDATE
    SET page_url = COALESCE(business_emails.page_url, EXCLUDED.page_url)
RETURNING id, business_id, email, source, page_url, is_primary, found_at
`

type InsertBusinessEmailParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	Email      string
	Source     string
	PageUrl    *string
}

func (q *Queries) InsertBusinessEmail(ctx context.Context, arg InsertBusinessEmailParams) (BusinessEmail, error) {
	row := q.db.QueryRow(ctx, insertBusinessEmail,
		arg.ID,
		arg.BusinessID,
		arg.Email,
		arg.Source,
		arg.PageUrl,
	)
	var i BusinessEmail
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Source,
		&i.PageUrl,
		&i.IsPrimary,
		&i.FoundAt,
	)
	return i, err
}

const listBusinessEmails = `-- name: ListBusinessEmails :many
SELECT id, business_id, email, source, page_url, is_primary, found_at FROM business_emails
WHERE business_id = $1
ORDER BY is_primary DESC, found_at, email
`

func (q *Queries) ListBusinessEmails(ctx context.Context, businessID uuid.UUID) ([]BusinessEmail, error) {
	rows, err := q.db.Query(ctx, listBusinessEmails, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessEmail{}
	for rows.Next() {
		var i BusinessEmail
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Email,
			&i.Source,
			&i.PageUrl,
			&i.IsPrimary,
			&i.FoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessEmailsWithVerification = `-- name: ListBusinessEmailsWithVerification :many
SELECT be.id, be.business_id, be.email, be.source, be.page_url, be.is_primary, be.found_at,
       ev.id               AS verification_id,
       ev.final_score      AS verification_score,
       ev.verification_tag AS verification_tag,
       ev.typo_suggestion  AS typo_suggestion,
       ev.pass1_score      AS pass1_score,
       ev.pass2_status     AS pass2_status,
       ev.pass1_verified_at AS pass1_verified_at,
       ev.pass2_verified_at AS pass2_verified_at
FROM business_emails be
         LEFT JOIN email_verifications ev ON ev.email = be.email
WHERE be.business_id = $1
ORDER BY be.is_primary DESC, be.found_at, be.email
`

type ListBusinessEmailsWithVerificationRow struct {
	ID                uuid.UUID
	BusinessID        uuid.UUID
	Email             string
	Source            string
	PageUrl           *string
	IsPrimary         bool
	FoundAt           time.Time
	VerificationID    uuid.NullUUID
	VerificationScore *int32
	VerificationTag   *string
	TypoSuggestion    *string
	Pass1Score        *int32
	Pass2Status       *string
	Pass1VerifiedAt   *time.Time
	Pass2VerifiedAt   *time.Time
}

// The detail view needs each address's verification alongside it; the LEFT JOIN keeps
// addresses that have never been through Pass 1.
func (q *Queries) ListBusinessEmailsWithVerification(ctx context.Context, businessID uuid.UUID) ([]ListBusinessEmailsWithVerificationRow, error) {
	rows, err := q.db.Query(ctx, listBusinessEmailsWithVerification, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessEmailsWithVerificationRow{}
	for rows.Next() {
		var i ListBusinessEmailsWithVerificationRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Email,
			&i.Source,
			&i.PageUrl,
			&i.IsPrimary,
			&i.FoundAt,
			&i.VerificationID,
			&i.VerificationScore,
			&i.VerificationTag,
			&i.TypoSuggestion,
			&i.Pass1Score,
			&i.Pass2Status,
			&i.Pass1VerifiedAt,
			&i.Pass2VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryEmail = `-- name: SetPrimaryEmail :exec
UPDATE business_emails SET is_primary = true WHERE id = $1
`

func (q *Queries) SetPrimaryEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPrimaryEmail, id)
	return err
}
