// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaigns.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addCampaignSendingAccount = `-- name: AddCampaignSendingAccount :exec
INSERT INTO campaign_sending_accounts (campaign_id, sending_account_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddCampaignSendingAccountParams struct {
	CampaignID       uuid.UUID
	SendingAccountID uuid.UUID
}

func (q *Queries) AddCampaignSendingAccount(ctx context.Context, arg AddCampaignSendingAccountParams) error {
	_, err := q.db.Exec(ctx, addCampaignSendingAccount, arg.CampaignID, arg.SendingAccountID)
	return err
}

const archiveCampaign = `-- name: ArchiveCampaign :one
UPDATE campaigns
SET status = 'archived', archived_at = now(), updated_at = now()
WHERE id = $1 AND status <> 'archived'
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

func (q *Queries) ArchiveCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, archiveCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const bumpCampaignWeightsVersion = `-- name: BumpCampaignWeightsVersion :one
UPDATE campaigns SET weights_version = weights_version + 1, updated_at = now() WHERE id = $1 RETURNING weights_version
`

func (q *Queries) BumpCampaignWeightsVersion(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpCampaignWeightsVersion, id)
	var weights_version int32
	err := row.Scan(&weights_version)
	return weights_version, err
}

const claimCampaignLaunch = `-- name: ClaimCampaignLaunch :one
UPDATE campaigns
SET status = 'launching', launch_claimed_at = now(), error = NULL, updated_at = now()
WHERE id = $1 AND status IN ('ready', 'scheduled')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

// A compare-and-set: only a ready or scheduled campaign can start launching, and
// only once.
func (q *Queries) ClaimCampaignLaunch(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, claimCampaignLaunch, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const countCampaignsByStatus = `-- name: CountCampaignsByStatus :many
SELECT status, count(*)::bigint AS total FROM campaigns GROUP BY status
`

type CountCampaignsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountCampaignsByStatus(ctx context.Context) ([]CountCampaignsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCampaignsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCampaignsByStatusRow{}
	for rows.Next() {
		var i CountCampaignsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (id, name, brief, schedule, settings, steps, step_delays)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

type CreateCampaignParams struct {
	ID         uuid.UUID
	Name       string
	Brief      []byte
	Schedule   []byte
	Settings   []byte
	Steps      int32
	StepDelays []byte
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.Name,
		arg.Brief,
		arg.Schedule,
		arg.Settings,
		arg.Steps,
		arg.StepDelays,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const getCampaignByInstantlyID = `-- name: GetCampaignByInstantlyID :one
SELECT id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id FROM campaigns WHERE instantly_campaign_id = $1
`

func (q *Queries) GetCampaignByInstantlyID(ctx context.Context, instantlyCampaignID *string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByInstantlyID, instantlyCampaignID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const listCampaignSendingAccounts = `-- name: ListCampaignSendingAccounts :many
SELECT sa.id, sa.email, sa.first_name, sa.last_name, sa.provider_code, sa.status, sa.warmup_status, sa.daily_limit, sa.sending_gap, sa.warmup_score, sa.status_message, sa.tracking_domain, sa.tracking_domain_status, sa.setup_pending, sa.is_managed, sa.raw, sa.last_synced_at, sa.created_at, sa.updated_at FROM sending_accounts sa
JOIN campaign_sending_accounts csa ON csa.sending_account_id = sa.id
WHERE csa.campaign_id = $1
ORDER BY sa.email
`

func (q *Queries) ListCampaignSendingAccounts(ctx context.Context, campaignID uuid.UUID) ([]SendingAccount, error) {
	rows, err := q.db.Query(ctx, listCampaignSendingAccounts, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SendingAccount{}
	for rows.Next() {
		var i SendingAccount
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.ProviderCode,
			&i.Status,
			&i.WarmupStatus,
			&i.DailyLimit,
			&i.SendingGap,
			&i.WarmupScore,
			&i.StatusMessage,
			&i.TrackingDomain,
			&i.TrackingDomainStatus,
			&i.SetupPending,
			&i.IsManaged,
			&i.Raw,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByStatus = `-- name: ListCampaignsByStatus :many
SELECT id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id FROM campaigns WHERE status = ANY($1::text[]) ORDER BY created_at
`

func (q *Queries) ListCampaignsByStatus(ctx context.Context, statuses []string) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByStatus, statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Brief,
			&i.Schedule,
			&i.Settings,
			&i.Steps,
			&i.StepDelays,
			&i.WeightsVersion,
			&i.InstantlyCampaignID,
			&i.InstantlyStatus,
			&i.InstantlySendingStatus,
			&i.InstantlyNotSendingStatus,
			&i.LaunchClaimedAt,
			&i.LaunchedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.Error,
			&i.LeadsTotal,
			&i.LeadsPushed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.ScheduledLaunchAt,
			&i.LaunchRequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsForSendingAccount = `-- name: ListCampaignsForSendingAccount :many
SELECT c.id, c.name, c.status, c.brief, c.schedule, c.settings, c.steps, c.step_delays, c.weights_version, c.instantly_campaign_id, c.instantly_status, c.instantly_sending_status, c.instantly_not_sending_status, c.launch_claimed_at, c.launched_at, c.paused_at, c.completed_at, c.archived_at, c.last_synced_at, c.last_sync_error, c.error, c.leads_total, c.leads_pushed, c.created_at, c.updated_at, c.source, c.scheduled_launch_at, c.launch_request_id FROM campaigns c
JOIN campaign_sending_accounts csa ON csa.campaign_id = c.id
WHERE csa.sending_account_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListCampaignsForSendingAccount(ctx context.Context, sendingAccountID uuid.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsForSendingAccount, sendingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Brief,
			&i.Schedule,
			&i.Settings,
			&i.Steps,
			&i.StepDelays,
			&i.WeightsVersion,
			&i.InstantlyCampaignID,
			&i.InstantlyStatus,
			&i.InstantlySendingStatus,
			&i.InstantlyNotSendingStatus,
			&i.LaunchClaimedAt,
			&i.LaunchedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.Error,
			&i.LeadsTotal,
			&i.LeadsPushed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.ScheduledLaunchAt,
			&i.LaunchRequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedImportedCampaignsToSync = `-- name: ListFinishedImportedCampaignsToSync :many
SELECT id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id FROM campaigns c
WHERE c.source = 'instantly' AND c.instantly_campaign_id IS NOT NULL
  AND c.status NOT IN ('active', 'paused', 'launching', 'archived')
  AND (NOT EXISTS (SELECT 1 FROM campaign_stats_daily d WHERE d.campaign_id = c.id)
       OR c.completed_at >= now() - make_interval(days => $1::int))
ORDER BY c.created_at
`

// Campaigns started in Instantly that have stopped sending but still need a sync:
// one that has never had its per-day figures fetched, or one completed recently
// enough that replies and opportunities may still be coming in.
func (q *Queries) ListFinishedImportedCampaignsToSync(ctx context.Context, settleDays int32) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listFinishedImportedCampaignsToSync, settleDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Brief,
			&i.Schedule,
			&i.Settings,
			&i.Steps,
			&i.StepDelays,
			&i.WeightsVersion,
			&i.InstantlyCampaignID,
			&i.InstantlyStatus,
			&i.InstantlySendingStatus,
			&i.InstantlyNotSendingStatus,
			&i.LaunchClaimedAt,
			&i.LaunchedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.Error,
			&i.LeadsTotal,
			&i.LeadsPushed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.ScheduledLaunchAt,
			&i.LaunchRequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCampaignActive = `-- name: MarkCampaignActive :one
UPDATE campaigns
SET status = 'active', launched_at = COALESCE(launched_at, now()), paused_at = NULL, error = NULL, updated_at = now()
WHERE id = $1 AND status IN ('launching', 'paused', 'active')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

func (q *Queries) MarkCampaignActive(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignActive, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const markCampaignCompleted = `-- name: MarkCampaignCompleted :one
UPDATE campaigns
SET status = 'completed', completed_at = COALESCE(completed_at, now()), updated_at = now()
WHERE id = $1 AND status IN ('active', 'paused')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

func (q *Queries) MarkCampaignCompleted(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignCompleted, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const markCampaignFailed = `-- name: MarkCampaignFailed :one
UPDATE campaigns
SET status = 'failed', error = $1, updated_at = now()
WHERE id = $2 AND status IN ('ready', 'scheduled', 'launching')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

type MarkCampaignFailedParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) MarkCampaignFailed(ctx context.Context, arg MarkCampaignFailedParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignFailed, arg.Error, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const markCampaignPaused = `-- name: MarkCampaignPaused :one
UPDATE campaigns
SET status = 'paused', paused_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('active', 'launching')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

func (q *Queries) MarkCampaignPaused(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignPaused, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const markCampaignReady = `-- name: MarkCampaignReady :one
UPDATE campaigns
SET status = 'ready', scheduled_launch_at = NULL, launch_request_id = $1,
    error = NULL, updated_at = now()
WHERE id = $2 AND status IN ('draft', 'ready', 'failed', 'scheduled')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

type MarkCampaignReadyParams struct {
	LaunchRequestID uuid.NullUUID
	ID              uuid.UUID
}

// A launch now. It also takes over a scheduled campaign, which is how "launch now
// instead" works; the new request id makes the scheduled job stale.
func (q *Queries) MarkCampaignReady(ctx context.Context, arg MarkCampaignReadyParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignReady, arg.LaunchRequestID, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const recomputeCampaignCounts = `-- name: RecomputeCampaignCounts :one
UPDATE campaigns c
SET leads_total  = counted.total,
    leads_pushed = counted.pushed
FROM (SELECT count(*)::int AS total,
             count(*) FILTER (WHERE pushed_at IS NOT NULL)::int AS pushed
      FROM campaign_leads WHERE campaign_id = $1) counted
WHERE c.id = $1
RETURNING c.id, c.name, c.status, c.brief, c.schedule, c.settings, c.steps, c.step_delays, c.weights_version, c.instantly_campaign_id, c.instantly_status, c.instantly_sending_status, c.instantly_not_sending_status, c.launch_claimed_at, c.launched_at, c.paused_at, c.completed_at, c.archived_at, c.last_synced_at, c.last_sync_error, c.error, c.leads_total, c.leads_pushed, c.created_at, c.updated_at, c.source, c.scheduled_launch_at, c.launch_request_id
`

func (q *Queries) RecomputeCampaignCounts(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, recomputeCampaignCounts, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const scheduleCampaignLaunch = `-- name: ScheduleCampaignLaunch :one
UPDATE campaigns
SET status = 'scheduled', scheduled_launch_at = $1,
    launch_request_id = $2, error = NULL, updated_at = now()
WHERE id = $3 AND status IN ('draft', 'ready', 'failed', 'scheduled')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

type ScheduleCampaignLaunchParams struct {
	ScheduledLaunchAt *time.Time
	LaunchRequestID   uuid.NullUUID
	ID                uuid.UUID
}

// A launch later, or a new time for one already scheduled.
func (q *Queries) ScheduleCampaignLaunch(ctx context.Context, arg ScheduleCampaignLaunchParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, scheduleCampaignLaunch, arg.ScheduledLaunchAt, arg.LaunchRequestID, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const setCampaignInstantlyID = `-- name: SetCampaignInstantlyID :one
UPDATE campaigns
SET instantly_campaign_id = $1, updated_at = now()
WHERE id = $2 AND instantly_campaign_id IS NULL
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

type SetCampaignInstantlyIDParams struct {
	InstantlyCampaignID *string
	ID                  uuid.UUID
}

func (q *Queries) SetCampaignInstantlyID(ctx context.Context, arg SetCampaignInstantlyIDParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setCampaignInstantlyID, arg.InstantlyCampaignID, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const setCampaignProviderState = `-- name: SetCampaignProviderState :exec
UPDATE campaigns
SET instantly_status             = $1,
    instantly_sending_status     = $2,
    instantly_not_sending_status = $3,
    last_synced_at               = $4,
    last_sync_error              = NULL,
    updated_at                   = now()
WHERE id = $5
`

type SetCampaignProviderStateParams struct {
	InstantlyStatus  *int32
	SendingStatus    *string
	NotSendingStatus *int32
	SyncedAt         *time.Time
	ID               uuid.UUID
}

// synced_at comes from the workers' clock, not now(): the sent-email backfill
// compares it with Instantly's timestamps, so both must be on the same clock.
func (q *Queries) SetCampaignProviderState(ctx context.Context, arg SetCampaignProviderStateParams) error {
	_, err := q.db.Exec(ctx, setCampaignProviderState,
		arg.InstantlyStatus,
		arg.SendingStatus,
		arg.NotSendingStatus,
		arg.SyncedAt,
		arg.ID,
	)
	return err
}

const setCampaignSendingAccounts = `-- name: SetCampaignSendingAccounts :exec
DELETE FROM campaign_sending_accounts WHERE campaign_id = $1
`

func (q *Queries) SetCampaignSendingAccounts(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setCampaignSendingAccounts, campaignID)
	return err
}

const setCampaignStatus = `-- name: SetCampaignStatus :one
UPDATE campaigns
SET status     = $1,
    error      = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

type SetCampaignStatusParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) SetCampaignStatus(ctx context.Context, arg SetCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setCampaignStatus, arg.Status, arg.Error, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const setCampaignSyncError = `-- name: SetCampaignSyncError :exec
UPDATE campaigns SET last_sync_error = $1, updated_at = now() WHERE id = $2
`

type SetCampaignSyncErrorParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) SetCampaignSyncError(ctx context.Context, arg SetCampaignSyncErrorParams) error {
	_, err := q.db.Exec(ctx, setCampaignSyncError, arg.Error, arg.ID)
	return err
}

const setImportedCampaignCounts = `-- name: SetImportedCampaignCounts :exec
UPDATE campaigns
SET leads_total = $1, leads_pushed = $1
WHERE id = $2 AND source = 'instantly'
`

type SetImportedCampaignCountsParams struct {
	LeadsTotal int32
	ID         uuid.UUID
}

// An imported campaign's leads live only in Instantly, so its counters come from
// Instantly's analytics rather than from campaign_leads.
func (q *Queries) SetImportedCampaignCounts(ctx context.Context, arg SetImportedCampaignCountsParams) error {
	_, err := q.db.Exec(ctx, setImportedCampaignCounts, arg.LeadsTotal, arg.ID)
	return err
}

const unscheduleCampaign = `-- name: UnscheduleCampaign :one
UPDATE campaigns
SET status = 'draft', scheduled_launch_at = NULL, launch_request_id = NULL, updated_at = now()
WHERE id = $1 AND status = 'scheduled'
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

func (q *Queries) UnscheduleCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, unscheduleCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET name        = COALESCE($1, name),
    brief       = COALESCE($2, brief),
    schedule    = COALESCE($3, schedule),
    settings    = COALESCE($4, settings),
    steps       = COALESCE($5, steps),
    step_delays = COALESCE($6, step_delays),
    updated_at  = now()
WHERE id = $7
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id
`

type UpdateCampaignParams struct {
	Name       *string
	Brief      []byte
	Schedule   []byte
	Settings   []byte
	Steps      *int32
	StepDelays []byte
	ID         uuid.UUID
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.Name,
		arg.Brief,
		arg.Schedule,
		arg.Settings,
		arg.Steps,
		arg.StepDelays,
		arg.ID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
	)
	return i, err
}

const upsertInstantlyCampaign = `-- name: UpsertInstantlyCampaign :one
INSERT INTO campaigns (id, name, status, steps, source, instantly_campaign_id, instantly_status,
                       launched_at, paused_at, completed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'instantly',
        $5, $6,
        CASE WHEN $3::text <> 'draft' THEN $7::timestamptz END,
        CASE WHEN $3::text = 'paused' THEN now() END,
        CASE WHEN $3::text = 'completed' THEN now() END,
        $7, now())
ON CONFLICT (instantly_campaign_id) DO UPDATE
SET name            = EXCLUDED.name,
    steps           = EXCLUDED.steps,
    instantly_status = EXCLUDED.instantly_status,
    status          = CASE WHEN campaigns.status = 'archived' THEN campaigns.status ELSE EXCLUDED.status END,
    launched_at     = COALESCE(campaigns.launched_at, EXCLUDED.launched_at),
    paused_at       = CASE WHEN EXCLUDED.status = 'paused' THEN COALESCE(campaigns.paused_at, now()) END,
    completed_at    = CASE WHEN EXCLUDED.status = 'completed' THEN COALESCE(campaigns.completed_at, now()) END,
    updated_at      = CASE WHEN (campaigns.name, campaigns.steps, campaigns.status, campaigns.instantly_status)
                                IS DISTINCT FROM (EXCLUDED.name, EXCLUDED.steps, EXCLUDED.status, EXCLUDED.instantly_status)
                           THEN now() ELSE campaigns.updated_at END
WHERE campaigns.source = 'instantly'
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at, source, scheduled_launch_at, launch_request_id, (xmax = 0)::boolean AS inserted
`

type UpsertInstantlyCampaignParams struct {
	ID                  uuid.UUID
	Name                string
	Status              string
	Steps               int32
	InstantlyCampaignID *string
	InstantlyStatus     *int32
	CreatedAt           time.Time
}

type UpsertInstantlyCampaignRow struct {
	ID                        uuid.UUID
	Name                      string
	Status                    string
	Brief                     []byte
	Schedule                  []byte
	Settings                  []byte
	Steps                     int32
	StepDelays                []byte
	WeightsVersion            int32
	InstantlyCampaignID       *string
	InstantlyStatus           *int32
	InstantlySendingStatus    *string
	InstantlyNotSendingStatus *int32
	LaunchClaimedAt           *time.Time
	LaunchedAt                *time.Time
	PausedAt                  *time.Time
	CompletedAt               *time.Time
	ArchivedAt                *time.Time
	LastSyncedAt              *time.Time
	LastSyncError             *string
	Error                     *string
	LeadsTotal                int32
	LeadsPushed               int32
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	Source                    string
	ScheduledLaunchAt         *time.Time
	LaunchRequestID           uuid.NullUUID
	Inserted                  bool
}

// Imports a campaign started in Instantly, or refreshes one imported before. A
// campaign Karvon launched matches on its Instantly id too, but is left alone
// (no row comes back): its own sync owns it. An archived import stays archived.
func (q *Queries) UpsertInstantlyCampaign(ctx context.Context, arg UpsertInstantlyCampaignParams) (UpsertInstantlyCampaignRow, error) {
	row := q.db.QueryRow(ctx, upsertInstantlyCampaign,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Steps,
		arg.InstantlyCampaignID,
		arg.InstantlyStatus,
		arg.CreatedAt,
	)
	var i UpsertInstantlyCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ScheduledLaunchAt,
		&i.LaunchRequestID,
		&i.Inserted,
	)
	return i, err
}
