// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaign_variants.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const activateCampaignVariants = `-- name: ActivateCampaignVariants :exec
UPDATE email_variants SET status = 'active', updated_at = now()
WHERE id IN (SELECT variant_id FROM campaign_variants WHERE campaign_id = $1) AND status = 'approved'
`

// A launched campaign's variants become active content.
func (q *Queries) ActivateCampaignVariants(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateCampaignVariants, campaignID)
	return err
}

const addCampaignVariant = `-- name: AddCampaignVariant :exec
INSERT INTO campaign_variants (campaign_id, variant_id, step, weight, status)
VALUES ($1, $2, $3, $4, $5)
`

type AddCampaignVariantParams struct {
	CampaignID uuid.UUID
	VariantID  uuid.UUID
	Step       int32
	Weight     int32
	Status     string
}

func (q *Queries) AddCampaignVariant(ctx context.Context, arg AddCampaignVariantParams) error {
	_, err := q.db.Exec(ctx, addCampaignVariant,
		arg.CampaignID,
		arg.VariantID,
		arg.Step,
		arg.Weight,
		arg.Status,
	)
	return err
}

const clearCampaignVariants = `-- name: ClearCampaignVariants :exec
DELETE FROM campaign_variants WHERE campaign_id = $1
`

func (q *Queries) ClearCampaignVariants(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCampaignVariants, campaignID)
	return err
}

const listActiveCampaignVariantsForStep = `-- name: ListActiveCampaignVariantsForStep :many
SELECT cv.variant_id, cv.weight FROM campaign_variants cv
JOIN email_variants v ON v.id = cv.variant_id
WHERE cv.campaign_id = $1 AND cv.step = $2 AND cv.status = 'active' AND cv.weight > 0
  AND v.status IN ('approved', 'active')
ORDER BY cv.variant_id
`

type ListActiveCampaignVariantsForStepParams struct {
	CampaignID uuid.UUID
	Step       int32
}

type ListActiveCampaignVariantsForStepRow struct {
	VariantID uuid.UUID
	Weight    int32
}

func (q *Queries) ListActiveCampaignVariantsForStep(ctx context.Context, arg ListActiveCampaignVariantsForStepParams) ([]ListActiveCampaignVariantsForStepRow, error) {
	rows, err := q.db.Query(ctx, listActiveCampaignVariantsForStep, arg.CampaignID, arg.Step)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCampaignVariantsForStepRow{}
	for rows.Next() {
		var i ListActiveCampaignVariantsForStepRow
		if err := rows.Scan(&i.VariantID, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignVariants = `-- name: ListCampaignVariants :many
SELECT cv.campaign_id, cv.variant_id, cv.step, cv.weight, cv.status AS assignment_status, cv.created_at AS attached_at,
       v.name, v.status AS variant_status, v.subject_template, v.body_template, v.component_ids
FROM campaign_variants cv
JOIN email_variants v ON v.id = cv.variant_id
WHERE cv.campaign_id = $1
ORDER BY cv.step, v.name
`

type ListCampaignVariantsRow struct {
	CampaignID       uuid.UUID
	VariantID        uuid.UUID
	Step             int32
	Weight           int32
	AssignmentStatus string
	AttachedAt       time.Time
	Name             string
	VariantStatus    string
	SubjectTemplate  string
	BodyTemplate     string
	ComponentIds     []uuid.UUID
}

func (q *Queries) ListCampaignVariants(ctx context.Context, campaignID uuid.UUID) ([]ListCampaignVariantsRow, error) {
	rows, err := q.db.Query(ctx, listCampaignVariants, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignVariantsRow{}
	for rows.Next() {
		var i ListCampaignVariantsRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.VariantID,
			&i.Step,
			&i.Weight,
			&i.AssignmentStatus,
			&i.AttachedAt,
			&i.Name,
			&i.VariantStatus,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.ComponentIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsUsingVariant = `-- name: ListCampaignsUsingVariant :many
SELECT c.id, c.name, c.status, c.brief, c.schedule, c.settings, c.steps, c.step_delays, c.weights_version, c.instantly_campaign_id, c.instantly_status, c.instantly_sending_status, c.instantly_not_sending_status, c.launch_claimed_at, c.launched_at, c.paused_at, c.completed_at, c.archived_at, c.last_synced_at, c.last_sync_error, c.error, c.leads_total, c.leads_pushed, c.created_at, c.updated_at, c.source FROM campaigns c JOIN campaign_variants cv ON cv.campaign_id = c.id WHERE cv.variant_id = $1 ORDER BY c.created_at DESC
`

func (q *Queries) ListCampaignsUsingVariant(ctx context.Context, variantID uuid.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsUsingVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Brief,
			&i.Schedule,
			&i.Settings,
			&i.Steps,
			&i.StepDelays,
			&i.WeightsVersion,
			&i.InstantlyCampaignID,
			&i.InstantlyStatus,
			&i.InstantlySendingStatus,
			&i.InstantlyNotSendingStatus,
			&i.LaunchClaimedAt,
			&i.LaunchedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.Error,
			&i.LeadsTotal,
			&i.LeadsPushed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
