// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaigns.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const addCampaignSendingAccount = `-- name: AddCampaignSendingAccount :exec
INSERT INTO campaign_sending_accounts (campaign_id, sending_account_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddCampaignSendingAccountParams struct {
	CampaignID       uuid.UUID
	SendingAccountID uuid.UUID
}

func (q *Queries) AddCampaignSendingAccount(ctx context.Context, arg AddCampaignSendingAccountParams) error {
	_, err := q.db.Exec(ctx, addCampaignSendingAccount, arg.CampaignID, arg.SendingAccountID)
	return err
}

const archiveCampaign = `-- name: ArchiveCampaign :one
UPDATE campaigns
SET status = 'archived', archived_at = now(), updated_at = now()
WHERE id = $1 AND status <> 'archived'
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

func (q *Queries) ArchiveCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, archiveCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bumpCampaignWeightsVersion = `-- name: BumpCampaignWeightsVersion :one
UPDATE campaigns SET weights_version = weights_version + 1, updated_at = now() WHERE id = $1 RETURNING weights_version
`

func (q *Queries) BumpCampaignWeightsVersion(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpCampaignWeightsVersion, id)
	var weights_version int32
	err := row.Scan(&weights_version)
	return weights_version, err
}

const claimCampaignLaunch = `-- name: ClaimCampaignLaunch :one
UPDATE campaigns
SET status = 'launching', launch_claimed_at = now(), error = NULL, updated_at = now()
WHERE id = $1 AND status = 'ready'
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

// A compare-and-set: only a ready campaign can start launching, and only once.
func (q *Queries) ClaimCampaignLaunch(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, claimCampaignLaunch, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCampaignsByStatus = `-- name: CountCampaignsByStatus :many
SELECT status, count(*)::bigint AS total FROM campaigns GROUP BY status
`

type CountCampaignsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountCampaignsByStatus(ctx context.Context) ([]CountCampaignsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCampaignsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCampaignsByStatusRow{}
	for rows.Next() {
		var i CountCampaignsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (id, name, brief, schedule, settings, steps, step_delays)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

type CreateCampaignParams struct {
	ID         uuid.UUID
	Name       string
	Brief      []byte
	Schedule   []byte
	Settings   []byte
	Steps      int32
	StepDelays []byte
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.Name,
		arg.Brief,
		arg.Schedule,
		arg.Settings,
		arg.Steps,
		arg.StepDelays,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByInstantlyID = `-- name: GetCampaignByInstantlyID :one
SELECT id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at FROM campaigns WHERE instantly_campaign_id = $1
`

func (q *Queries) GetCampaignByInstantlyID(ctx context.Context, instantlyCampaignID *string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByInstantlyID, instantlyCampaignID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignSendingAccounts = `-- name: ListCampaignSendingAccounts :many
SELECT sa.id, sa.email, sa.first_name, sa.last_name, sa.provider_code, sa.status, sa.warmup_status, sa.daily_limit, sa.sending_gap, sa.warmup_score, sa.status_message, sa.tracking_domain, sa.tracking_domain_status, sa.setup_pending, sa.is_managed, sa.raw, sa.last_synced_at, sa.created_at, sa.updated_at FROM sending_accounts sa
JOIN campaign_sending_accounts csa ON csa.sending_account_id = sa.id
WHERE csa.campaign_id = $1
ORDER BY sa.email
`

func (q *Queries) ListCampaignSendingAccounts(ctx context.Context, campaignID uuid.UUID) ([]SendingAccount, error) {
	rows, err := q.db.Query(ctx, listCampaignSendingAccounts, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SendingAccount{}
	for rows.Next() {
		var i SendingAccount
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.ProviderCode,
			&i.Status,
			&i.WarmupStatus,
			&i.DailyLimit,
			&i.SendingGap,
			&i.WarmupScore,
			&i.StatusMessage,
			&i.TrackingDomain,
			&i.TrackingDomainStatus,
			&i.SetupPending,
			&i.IsManaged,
			&i.Raw,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByStatus = `-- name: ListCampaignsByStatus :many
SELECT id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at FROM campaigns WHERE status = ANY($1::text[]) ORDER BY created_at
`

func (q *Queries) ListCampaignsByStatus(ctx context.Context, statuses []string) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByStatus, statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Brief,
			&i.Schedule,
			&i.Settings,
			&i.Steps,
			&i.StepDelays,
			&i.WeightsVersion,
			&i.InstantlyCampaignID,
			&i.InstantlyStatus,
			&i.InstantlySendingStatus,
			&i.InstantlyNotSendingStatus,
			&i.LaunchClaimedAt,
			&i.LaunchedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.Error,
			&i.LeadsTotal,
			&i.LeadsPushed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsForSendingAccount = `-- name: ListCampaignsForSendingAccount :many
SELECT c.id, c.name, c.status, c.brief, c.schedule, c.settings, c.steps, c.step_delays, c.weights_version, c.instantly_campaign_id, c.instantly_status, c.instantly_sending_status, c.instantly_not_sending_status, c.launch_claimed_at, c.launched_at, c.paused_at, c.completed_at, c.archived_at, c.last_synced_at, c.last_sync_error, c.error, c.leads_total, c.leads_pushed, c.created_at, c.updated_at FROM campaigns c
JOIN campaign_sending_accounts csa ON csa.campaign_id = c.id
WHERE csa.sending_account_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListCampaignsForSendingAccount(ctx context.Context, sendingAccountID uuid.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsForSendingAccount, sendingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Brief,
			&i.Schedule,
			&i.Settings,
			&i.Steps,
			&i.StepDelays,
			&i.WeightsVersion,
			&i.InstantlyCampaignID,
			&i.InstantlyStatus,
			&i.InstantlySendingStatus,
			&i.InstantlyNotSendingStatus,
			&i.LaunchClaimedAt,
			&i.LaunchedAt,
			&i.PausedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.Error,
			&i.LeadsTotal,
			&i.LeadsPushed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCampaignActive = `-- name: MarkCampaignActive :one
UPDATE campaigns
SET status = 'active', launched_at = COALESCE(launched_at, now()), paused_at = NULL, error = NULL, updated_at = now()
WHERE id = $1 AND status IN ('launching', 'paused', 'active')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

func (q *Queries) MarkCampaignActive(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignActive, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCampaignCompleted = `-- name: MarkCampaignCompleted :one
UPDATE campaigns
SET status = 'completed', completed_at = COALESCE(completed_at, now()), updated_at = now()
WHERE id = $1 AND status IN ('active', 'paused')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

func (q *Queries) MarkCampaignCompleted(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignCompleted, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCampaignFailed = `-- name: MarkCampaignFailed :one
UPDATE campaigns
SET status = 'failed', error = $1, updated_at = now()
WHERE id = $2 AND status IN ('ready', 'launching')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

type MarkCampaignFailedParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) MarkCampaignFailed(ctx context.Context, arg MarkCampaignFailedParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignFailed, arg.Error, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCampaignPaused = `-- name: MarkCampaignPaused :one
UPDATE campaigns
SET status = 'paused', paused_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('active', 'launching')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

func (q *Queries) MarkCampaignPaused(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignPaused, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCampaignReady = `-- name: MarkCampaignReady :one
UPDATE campaigns SET status = 'ready', updated_at = now()
WHERE id = $1 AND status IN ('draft', 'ready', 'failed')
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

func (q *Queries) MarkCampaignReady(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignReady, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recomputeCampaignCounts = `-- name: RecomputeCampaignCounts :one
UPDATE campaigns c
SET leads_total  = counted.total,
    leads_pushed = counted.pushed
FROM (SELECT count(*)::int AS total,
             count(*) FILTER (WHERE pushed_at IS NOT NULL)::int AS pushed
      FROM campaign_leads WHERE campaign_id = $1) counted
WHERE c.id = $1
RETURNING c.id, c.name, c.status, c.brief, c.schedule, c.settings, c.steps, c.step_delays, c.weights_version, c.instantly_campaign_id, c.instantly_status, c.instantly_sending_status, c.instantly_not_sending_status, c.launch_claimed_at, c.launched_at, c.paused_at, c.completed_at, c.archived_at, c.last_synced_at, c.last_sync_error, c.error, c.leads_total, c.leads_pushed, c.created_at, c.updated_at
`

func (q *Queries) RecomputeCampaignCounts(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, recomputeCampaignCounts, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCampaignInstantlyID = `-- name: SetCampaignInstantlyID :one
UPDATE campaigns
SET instantly_campaign_id = $1, updated_at = now()
WHERE id = $2 AND instantly_campaign_id IS NULL
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

type SetCampaignInstantlyIDParams struct {
	InstantlyCampaignID *string
	ID                  uuid.UUID
}

func (q *Queries) SetCampaignInstantlyID(ctx context.Context, arg SetCampaignInstantlyIDParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setCampaignInstantlyID, arg.InstantlyCampaignID, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCampaignProviderState = `-- name: SetCampaignProviderState :exec
UPDATE campaigns
SET instantly_status             = $1,
    instantly_sending_status     = $2,
    instantly_not_sending_status = $3,
    last_synced_at               = now(),
    last_sync_error              = NULL,
    updated_at                   = now()
WHERE id = $4
`

type SetCampaignProviderStateParams struct {
	InstantlyStatus  *int32
	SendingStatus    *string
	NotSendingStatus *int32
	ID               uuid.UUID
}

func (q *Queries) SetCampaignProviderState(ctx context.Context, arg SetCampaignProviderStateParams) error {
	_, err := q.db.Exec(ctx, setCampaignProviderState,
		arg.InstantlyStatus,
		arg.SendingStatus,
		arg.NotSendingStatus,
		arg.ID,
	)
	return err
}

const setCampaignSendingAccounts = `-- name: SetCampaignSendingAccounts :exec
DELETE FROM campaign_sending_accounts WHERE campaign_id = $1
`

func (q *Queries) SetCampaignSendingAccounts(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setCampaignSendingAccounts, campaignID)
	return err
}

const setCampaignStatus = `-- name: SetCampaignStatus :one
UPDATE campaigns
SET status     = $1,
    error      = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

type SetCampaignStatusParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) SetCampaignStatus(ctx context.Context, arg SetCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setCampaignStatus, arg.Status, arg.Error, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCampaignSyncError = `-- name: SetCampaignSyncError :exec
UPDATE campaigns SET last_sync_error = $1, updated_at = now() WHERE id = $2
`

type SetCampaignSyncErrorParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) SetCampaignSyncError(ctx context.Context, arg SetCampaignSyncErrorParams) error {
	_, err := q.db.Exec(ctx, setCampaignSyncError, arg.Error, arg.ID)
	return err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET name        = COALESCE($1, name),
    brief       = COALESCE($2, brief),
    schedule    = COALESCE($3, schedule),
    settings    = COALESCE($4, settings),
    steps       = COALESCE($5, steps),
    step_delays = COALESCE($6, step_delays),
    updated_at  = now()
WHERE id = $7
RETURNING id, name, status, brief, schedule, settings, steps, step_delays, weights_version, instantly_campaign_id, instantly_status, instantly_sending_status, instantly_not_sending_status, launch_claimed_at, launched_at, paused_at, completed_at, archived_at, last_synced_at, last_sync_error, error, leads_total, leads_pushed, created_at, updated_at
`

type UpdateCampaignParams struct {
	Name       *string
	Brief      []byte
	Schedule   []byte
	Settings   []byte
	Steps      *int32
	StepDelays []byte
	ID         uuid.UUID
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.Name,
		arg.Brief,
		arg.Schedule,
		arg.Settings,
		arg.Steps,
		arg.StepDelays,
		arg.ID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Brief,
		&i.Schedule,
		&i.Settings,
		&i.Steps,
		&i.StepDelays,
		&i.WeightsVersion,
		&i.InstantlyCampaignID,
		&i.InstantlyStatus,
		&i.InstantlySendingStatus,
		&i.InstantlyNotSendingStatus,
		&i.LaunchClaimedAt,
		&i.LaunchedAt,
		&i.PausedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.Error,
		&i.LeadsTotal,
		&i.LeadsPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
