// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaign_leads.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const claimPendingCampaignLeads = `-- name: ClaimPendingCampaignLeads :many
UPDATE campaign_leads cl
SET status = 'pushing', claimed_at = now(), push_attempts = push_attempts + 1, updated_at = now()
FROM contacts c
WHERE cl.id IN (
    SELECT l.id FROM campaign_leads l
    JOIN contacts ct ON ct.id = l.contact_id
    WHERE l.campaign_id = $1 AND l.status = 'pending' AND ct.suppressed_at IS NULL
      AND NOT EXISTS (SELECT 1 FROM global_excluded_addresses x WHERE x.email = ct.email)
    ORDER BY l.created_at
    LIMIT $2
    FOR UPDATE OF l SKIP LOCKED)
  AND c.id = cl.contact_id
RETURNING cl.id, cl.campaign_id, cl.contact_id, cl.business_id, cl.status, cl.instantly_lead_id, cl.instantly_status, cl.interest_status, cl.interest_label, cl.claimed_at, cl.pushed_at, cl.push_attempts, cl.last_push_error, cl.custom_vars, cl.last_contacted_at, cl.last_opened_at, cl.last_clicked_at, cl.last_replied_at, cl.open_count, cl.click_count, cl.reply_count, cl.created_at, cl.updated_at
`

type ClaimPendingCampaignLeadsParams struct {
	CampaignID uuid.UUID
	Lim        int32
}

// The push claim. A lead is claimed only while it is pending, its contact is not
// suppressed and its address is not globally excluded, so neither is ever handed
// to the provider.
func (q *Queries) ClaimPendingCampaignLeads(ctx context.Context, arg ClaimPendingCampaignLeadsParams) ([]CampaignLead, error) {
	rows, err := q.db.Query(ctx, claimPendingCampaignLeads, arg.CampaignID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLead{}
	for rows.Next() {
		var i CampaignLead
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.BusinessID,
			&i.Status,
			&i.InstantlyLeadID,
			&i.InstantlyStatus,
			&i.InterestStatus,
			&i.InterestLabel,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.PushAttempts,
			&i.LastPushError,
			&i.CustomVars,
			&i.LastContactedAt,
			&i.LastOpenedAt,
			&i.LastClickedAt,
			&i.LastRepliedAt,
			&i.OpenCount,
			&i.ClickCount,
			&i.ReplyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCampaignLeadsByStatus = `-- name: CountCampaignLeadsByStatus :many
SELECT status, count(*)::bigint AS total FROM campaign_leads WHERE campaign_id = $1 GROUP BY status
`

type CountCampaignLeadsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountCampaignLeadsByStatus(ctx context.Context, campaignID uuid.UUID) ([]CountCampaignLeadsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCampaignLeadsByStatus, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCampaignLeadsByStatusRow{}
	for rows.Next() {
		var i CountCampaignLeadsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingCampaignLeads = `-- name: CountPendingCampaignLeads :one
SELECT count(*) FROM campaign_leads cl
JOIN contacts c ON c.id = cl.contact_id
WHERE cl.campaign_id = $1 AND cl.status = 'pending' AND c.suppressed_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM global_excluded_addresses x WHERE x.email = c.email)
`

func (q *Queries) CountPendingCampaignLeads(ctx context.Context, campaignID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingCampaignLeads, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCampaignLead = `-- name: DeleteCampaignLead :execrows
DELETE FROM campaign_leads WHERE id = $1 AND status IN ('pending', 'failed', 'skipped')
`

func (q *Queries) DeleteCampaignLead(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCampaignLead, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCampaignLead = `-- name: GetCampaignLead :one
SELECT id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at FROM campaign_leads WHERE id = $1
`

func (q *Queries) GetCampaignLead(ctx context.Context, id uuid.UUID) (CampaignLead, error) {
	row := q.db.QueryRow(ctx, getCampaignLead, id)
	var i CampaignLead
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.BusinessID,
		&i.Status,
		&i.InstantlyLeadID,
		&i.InstantlyStatus,
		&i.InterestStatus,
		&i.InterestLabel,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.PushAttempts,
		&i.LastPushError,
		&i.CustomVars,
		&i.LastContactedAt,
		&i.LastOpenedAt,
		&i.LastClickedAt,
		&i.LastRepliedAt,
		&i.OpenCount,
		&i.ClickCount,
		&i.ReplyCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignLeadByContact = `-- name: GetCampaignLeadByContact :one
SELECT id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at FROM campaign_leads WHERE campaign_id = $1 AND contact_id = $2
`

type GetCampaignLeadByContactParams struct {
	CampaignID uuid.UUID
	ContactID  uuid.UUID
}

func (q *Queries) GetCampaignLeadByContact(ctx context.Context, arg GetCampaignLeadByContactParams) (CampaignLead, error) {
	row := q.db.QueryRow(ctx, getCampaignLeadByContact, arg.CampaignID, arg.ContactID)
	var i CampaignLead
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.BusinessID,
		&i.Status,
		&i.InstantlyLeadID,
		&i.InstantlyStatus,
		&i.InterestStatus,
		&i.InterestLabel,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.PushAttempts,
		&i.LastPushError,
		&i.CustomVars,
		&i.LastContactedAt,
		&i.LastOpenedAt,
		&i.LastClickedAt,
		&i.LastRepliedAt,
		&i.OpenCount,
		&i.ClickCount,
		&i.ReplyCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignLeadByInstantlyID = `-- name: GetCampaignLeadByInstantlyID :one
SELECT id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at FROM campaign_leads WHERE campaign_id = $1 AND instantly_lead_id = $2
`

type GetCampaignLeadByInstantlyIDParams struct {
	CampaignID      uuid.UUID
	InstantlyLeadID *string
}

func (q *Queries) GetCampaignLeadByInstantlyID(ctx context.Context, arg GetCampaignLeadByInstantlyIDParams) (CampaignLead, error) {
	row := q.db.QueryRow(ctx, getCampaignLeadByInstantlyID, arg.CampaignID, arg.InstantlyLeadID)
	var i CampaignLead
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.BusinessID,
		&i.Status,
		&i.InstantlyLeadID,
		&i.InstantlyStatus,
		&i.InterestStatus,
		&i.InterestLabel,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.PushAttempts,
		&i.LastPushError,
		&i.CustomVars,
		&i.LastContactedAt,
		&i.LastOpenedAt,
		&i.LastClickedAt,
		&i.LastRepliedAt,
		&i.OpenCount,
		&i.ClickCount,
		&i.ReplyCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCampaignLead = `-- name: InsertCampaignLead :one
INSERT INTO campaign_leads (id, campaign_id, contact_id, business_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id, contact_id) DO NOTHING
RETURNING id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at
`

type InsertCampaignLeadParams struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	ContactID  uuid.UUID
	BusinessID uuid.NullUUID
}

func (q *Queries) InsertCampaignLead(ctx context.Context, arg InsertCampaignLeadParams) (CampaignLead, error) {
	row := q.db.QueryRow(ctx, insertCampaignLead,
		arg.ID,
		arg.CampaignID,
		arg.ContactID,
		arg.BusinessID,
	)
	var i CampaignLead
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.BusinessID,
		&i.Status,
		&i.InstantlyLeadID,
		&i.InstantlyStatus,
		&i.InterestStatus,
		&i.InterestLabel,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.PushAttempts,
		&i.LastPushError,
		&i.CustomVars,
		&i.LastContactedAt,
		&i.LastOpenedAt,
		&i.LastClickedAt,
		&i.LastRepliedAt,
		&i.OpenCount,
		&i.ClickCount,
		&i.ReplyCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignLeadContactIDs = `-- name: ListCampaignLeadContactIDs :many
SELECT contact_id FROM campaign_leads WHERE campaign_id = $1
`

func (q *Queries) ListCampaignLeadContactIDs(ctx context.Context, campaignID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCampaignLeadContactIDs, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var contact_id uuid.UUID
		if err := rows.Scan(&contact_id); err != nil {
			return nil, err
		}
		items = append(items, contact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignLeadsForContact = `-- name: ListCampaignLeadsForContact :many
SELECT id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at FROM campaign_leads WHERE contact_id = $1 ORDER BY created_at
`

func (q *Queries) ListCampaignLeadsForContact(ctx context.Context, contactID uuid.UUID) ([]CampaignLead, error) {
	rows, err := q.db.Query(ctx, listCampaignLeadsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLead{}
	for rows.Next() {
		var i CampaignLead
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.BusinessID,
			&i.Status,
			&i.InstantlyLeadID,
			&i.InstantlyStatus,
			&i.InterestStatus,
			&i.InterestLabel,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.PushAttempts,
			&i.LastPushError,
			&i.CustomVars,
			&i.LastContactedAt,
			&i.LastOpenedAt,
			&i.LastClickedAt,
			&i.LastRepliedAt,
			&i.OpenCount,
			&i.ClickCount,
			&i.ReplyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushedCampaignLeads = `-- name: ListPushedCampaignLeads :many
SELECT id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at FROM campaign_leads WHERE campaign_id = $1 AND instantly_lead_id IS NOT NULL ORDER BY created_at
`

func (q *Queries) ListPushedCampaignLeads(ctx context.Context, campaignID uuid.UUID) ([]CampaignLead, error) {
	rows, err := q.db.Query(ctx, listPushedCampaignLeads, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLead{}
	for rows.Next() {
		var i CampaignLead
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.BusinessID,
			&i.Status,
			&i.InstantlyLeadID,
			&i.InstantlyStatus,
			&i.InterestStatus,
			&i.InterestLabel,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.PushAttempts,
			&i.LastPushError,
			&i.CustomVars,
			&i.LastContactedAt,
			&i.LastOpenedAt,
			&i.LastClickedAt,
			&i.LastRepliedAt,
			&i.OpenCount,
			&i.ClickCount,
			&i.ReplyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushedCampaignLeadsForContact = `-- name: ListPushedCampaignLeadsForContact :many
SELECT cl.id, cl.campaign_id, cl.contact_id, cl.business_id, cl.status, cl.instantly_lead_id, cl.instantly_status, cl.interest_status, cl.interest_label, cl.claimed_at, cl.pushed_at, cl.push_attempts, cl.last_push_error, cl.custom_vars, cl.last_contacted_at, cl.last_opened_at, cl.last_clicked_at, cl.last_replied_at, cl.open_count, cl.click_count, cl.reply_count, cl.created_at, cl.updated_at FROM campaign_leads cl
JOIN campaigns c ON c.id = cl.campaign_id
WHERE cl.contact_id = $1
  AND cl.instantly_lead_id IS NOT NULL
  AND c.status <> 'archived'
`

// Every lead of a contact that reached the provider, whatever state it is in now.
// Suppression uses this rather than the rows it just stopped, because a lead can
// already be terminal (bounced, unsubscribed) and still be sitting in Instantly.
func (q *Queries) ListPushedCampaignLeadsForContact(ctx context.Context, contactID uuid.UUID) ([]CampaignLead, error) {
	rows, err := q.db.Query(ctx, listPushedCampaignLeadsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLead{}
	for rows.Next() {
		var i CampaignLead
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.BusinessID,
			&i.Status,
			&i.InstantlyLeadID,
			&i.InstantlyStatus,
			&i.InterestStatus,
			&i.InterestLabel,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.PushAttempts,
			&i.LastPushError,
			&i.CustomVars,
			&i.LastContactedAt,
			&i.LastOpenedAt,
			&i.LastClickedAt,
			&i.LastRepliedAt,
			&i.OpenCount,
			&i.ClickCount,
			&i.ReplyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCampaignLeadPushed = `-- name: MarkCampaignLeadPushed :one
UPDATE campaign_leads
SET status = CASE WHEN status = 'excluded' THEN 'excluded' ELSE 'active' END, instantly_lead_id = $1, instantly_status = 1,
    pushed_at = COALESCE(pushed_at, now()), claimed_at = NULL, last_push_error = NULL,
    custom_vars = $2, updated_at = now()
WHERE id = $3
RETURNING id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at
`

type MarkCampaignLeadPushedParams struct {
	InstantlyLeadID *string
	CustomVars      []byte
	ID              uuid.UUID
}

// A lead the exclusion sweep stopped while its push was in flight stays excluded;
// the caller sees that and removes it from the provider again.
func (q *Queries) MarkCampaignLeadPushed(ctx context.Context, arg MarkCampaignLeadPushedParams) (CampaignLead, error) {
	row := q.db.QueryRow(ctx, markCampaignLeadPushed, arg.InstantlyLeadID, arg.CustomVars, arg.ID)
	var i CampaignLead
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.BusinessID,
		&i.Status,
		&i.InstantlyLeadID,
		&i.InstantlyStatus,
		&i.InterestStatus,
		&i.InterestLabel,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.PushAttempts,
		&i.LastPushError,
		&i.CustomVars,
		&i.LastContactedAt,
		&i.LastOpenedAt,
		&i.LastClickedAt,
		&i.LastRepliedAt,
		&i.OpenCount,
		&i.ClickCount,
		&i.ReplyCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCampaignLeadStatus = `-- name: MarkCampaignLeadStatus :one
UPDATE campaign_leads
SET status = $1, last_push_error = $2, claimed_at = NULL, updated_at = now()
WHERE id = $3
RETURNING id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at
`

type MarkCampaignLeadStatusParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) MarkCampaignLeadStatus(ctx context.Context, arg MarkCampaignLeadStatusParams) (CampaignLead, error) {
	row := q.db.QueryRow(ctx, markCampaignLeadStatus, arg.Status, arg.Error, arg.ID)
	var i CampaignLead
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.BusinessID,
		&i.Status,
		&i.InstantlyLeadID,
		&i.InstantlyStatus,
		&i.InterestStatus,
		&i.InterestLabel,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.PushAttempts,
		&i.LastPushError,
		&i.CustomVars,
		&i.LastContactedAt,
		&i.LastOpenedAt,
		&i.LastClickedAt,
		&i.LastRepliedAt,
		&i.OpenCount,
		&i.ClickCount,
		&i.ReplyCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCampaignLeadTerminal = `-- name: MarkCampaignLeadTerminal :exec
UPDATE campaign_leads
SET status = $1, claimed_at = NULL, updated_at = now()
WHERE id = $2 AND status NOT IN ('bounced', 'unsubscribed')
`

type MarkCampaignLeadTerminalParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) MarkCampaignLeadTerminal(ctx context.Context, arg MarkCampaignLeadTerminalParams) error {
	_, err := q.db.Exec(ctx, markCampaignLeadTerminal, arg.Status, arg.ID)
	return err
}

const recordCampaignLeadClick = `-- name: RecordCampaignLeadClick :exec
UPDATE campaign_leads
SET click_count = click_count + 1,
    last_clicked_at = GREATEST(COALESCE(last_clicked_at, $1), $1),
    updated_at = now()
WHERE id = $2
`

type RecordCampaignLeadClickParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) RecordCampaignLeadClick(ctx context.Context, arg RecordCampaignLeadClickParams) error {
	_, err := q.db.Exec(ctx, recordCampaignLeadClick, arg.At, arg.ID)
	return err
}

const recordCampaignLeadContact = `-- name: RecordCampaignLeadContact :exec
UPDATE campaign_leads
SET status = CASE WHEN status IN ('pending', 'pushing', 'active') THEN 'active' ELSE status END,
    last_contacted_at = GREATEST(COALESCE(last_contacted_at, $1), $1),
    updated_at = now()
WHERE id = $2
`

type RecordCampaignLeadContactParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) RecordCampaignLeadContact(ctx context.Context, arg RecordCampaignLeadContactParams) error {
	_, err := q.db.Exec(ctx, recordCampaignLeadContact, arg.At, arg.ID)
	return err
}

const recordCampaignLeadOpen = `-- name: RecordCampaignLeadOpen :exec
UPDATE campaign_leads
SET open_count = open_count + 1,
    last_opened_at = GREATEST(COALESCE(last_opened_at, $1), $1),
    updated_at = now()
WHERE id = $2
`

type RecordCampaignLeadOpenParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) RecordCampaignLeadOpen(ctx context.Context, arg RecordCampaignLeadOpenParams) error {
	_, err := q.db.Exec(ctx, recordCampaignLeadOpen, arg.At, arg.ID)
	return err
}

const recordCampaignLeadReply = `-- name: RecordCampaignLeadReply :exec
UPDATE campaign_leads
SET reply_count = reply_count + 1,
    status = CASE WHEN status IN ('pending', 'pushing', 'active', 'paused', 'completed') THEN 'replied' ELSE status END,
    last_replied_at = GREATEST(COALESCE(last_replied_at, $1), $1),
    updated_at = now()
WHERE id = $2
`

type RecordCampaignLeadReplyParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) RecordCampaignLeadReply(ctx context.Context, arg RecordCampaignLeadReplyParams) error {
	_, err := q.db.Exec(ctx, recordCampaignLeadReply, arg.At, arg.ID)
	return err
}

const releaseCampaignLeadClaims = `-- name: ReleaseCampaignLeadClaims :execrows
UPDATE campaign_leads
SET status = 'pending', claimed_at = NULL, last_push_error = $1, updated_at = now()
WHERE campaign_id = $2 AND status = 'pushing' AND id = ANY($3::uuid[])
`

type ReleaseCampaignLeadClaimsParams struct {
	Error      *string
	CampaignID uuid.UUID
	Ids        []uuid.UUID
}

func (q *Queries) ReleaseCampaignLeadClaims(ctx context.Context, arg ReleaseCampaignLeadClaimsParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseCampaignLeadClaims, arg.Error, arg.CampaignID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCampaignLeadInterest = `-- name: SetCampaignLeadInterest :exec
UPDATE campaign_leads
SET interest_status = $1, interest_label = $2, updated_at = now()
WHERE id = $3
`

type SetCampaignLeadInterestParams struct {
	InterestStatus *int32
	InterestLabel  *string
	ID             uuid.UUID
}

func (q *Queries) SetCampaignLeadInterest(ctx context.Context, arg SetCampaignLeadInterestParams) error {
	_, err := q.db.Exec(ctx, setCampaignLeadInterest, arg.InterestStatus, arg.InterestLabel, arg.ID)
	return err
}

const setCampaignLeadProviderState = `-- name: SetCampaignLeadProviderState :exec
UPDATE campaign_leads
SET instantly_lead_id = COALESCE($1, instantly_lead_id),
    instantly_status  = $2,
    interest_status   = $3,
    interest_label    = $4,
    status            = $5,
    open_count        = GREATEST(open_count, $6),
    click_count       = GREATEST(click_count, $7),
    reply_count       = GREATEST(reply_count, $8),
    last_contacted_at = COALESCE($9, last_contacted_at),
    last_opened_at    = COALESCE($10, last_opened_at),
    last_clicked_at   = COALESCE($11, last_clicked_at),
    last_replied_at   = COALESCE($12, last_replied_at),
    updated_at        = now()
WHERE id = $13
`

type SetCampaignLeadProviderStateParams struct {
	InstantlyLeadID *string
	InstantlyStatus *int32
	InterestStatus  *int32
	InterestLabel   *string
	Status          string
	OpenCount       int32
	ClickCount      int32
	ReplyCount      int32
	LastContactedAt *time.Time
	LastOpenedAt    *time.Time
	LastClickedAt   *time.Time
	LastRepliedAt   *time.Time
	ID              uuid.UUID
}

func (q *Queries) SetCampaignLeadProviderState(ctx context.Context, arg SetCampaignLeadProviderStateParams) error {
	_, err := q.db.Exec(ctx, setCampaignLeadProviderState,
		arg.InstantlyLeadID,
		arg.InstantlyStatus,
		arg.InterestStatus,
		arg.InterestLabel,
		arg.Status,
		arg.OpenCount,
		arg.ClickCount,
		arg.ReplyCount,
		arg.LastContactedAt,
		arg.LastOpenedAt,
		arg.LastClickedAt,
		arg.LastRepliedAt,
		arg.ID,
	)
	return err
}

const suppressCampaignLeadsForContact = `-- name: SuppressCampaignLeadsForContact :many
UPDATE campaign_leads
SET status = 'suppressed', claimed_at = NULL, updated_at = now()
WHERE contact_id = $1 AND status IN ('pending', 'pushing', 'active', 'paused', 'completed', 'replied')
RETURNING id, campaign_id, contact_id, business_id, status, instantly_lead_id, instantly_status, interest_status, interest_label, claimed_at, pushed_at, push_attempts, last_push_error, custom_vars, last_contacted_at, last_opened_at, last_clicked_at, last_replied_at, open_count, click_count, reply_count, created_at, updated_at
`

// Every non-terminal lead of a suppressed contact stops where it is.
func (q *Queries) SuppressCampaignLeadsForContact(ctx context.Context, contactID uuid.UUID) ([]CampaignLead, error) {
	rows, err := q.db.Query(ctx, suppressCampaignLeadsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLead{}
	for rows.Next() {
		var i CampaignLead
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.BusinessID,
			&i.Status,
			&i.InstantlyLeadID,
			&i.InstantlyStatus,
			&i.InterestStatus,
			&i.InterestLabel,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.PushAttempts,
			&i.LastPushError,
			&i.CustomVars,
			&i.LastContactedAt,
			&i.LastOpenedAt,
			&i.LastClickedAt,
			&i.LastRepliedAt,
			&i.OpenCount,
			&i.ClickCount,
			&i.ReplyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
