// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaign_settings.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const getCampaignSettings = `-- name: GetCampaignSettings :one
SELECT id, instantly_webhook_token, instantly_webhook_secret_enc, instantly_webhook_id, instantly_webhook_url, instantly_webhook_status, instantly_webhook_error, default_audience_id, updated_at FROM campaign_settings WHERE id = 1
`

func (q *Queries) GetCampaignSettings(ctx context.Context) (CampaignSetting, error) {
	row := q.db.QueryRow(ctx, getCampaignSettings)
	var i CampaignSetting
	err := row.Scan(
		&i.ID,
		&i.InstantlyWebhookToken,
		&i.InstantlyWebhookSecretEnc,
		&i.InstantlyWebhookID,
		&i.InstantlyWebhookUrl,
		&i.InstantlyWebhookStatus,
		&i.InstantlyWebhookError,
		&i.DefaultAudienceID,
		&i.UpdatedAt,
	)
	return i, err
}

const setDefaultAudience = `-- name: SetDefaultAudience :exec
UPDATE campaign_settings SET default_audience_id = $1, updated_at = now() WHERE id = 1
`

func (q *Queries) SetDefaultAudience(ctx context.Context, audienceID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, setDefaultAudience, audienceID)
	return err
}

const setInstantlyWebhook = `-- name: SetInstantlyWebhook :one
UPDATE campaign_settings
SET instantly_webhook_token      = $1,
    instantly_webhook_secret_enc = $2,
    instantly_webhook_id         = $3,
    instantly_webhook_url        = $4,
    instantly_webhook_status     = $5,
    instantly_webhook_error      = $6,
    updated_at                   = now()
WHERE id = 1
RETURNING id, instantly_webhook_token, instantly_webhook_secret_enc, instantly_webhook_id, instantly_webhook_url, instantly_webhook_status, instantly_webhook_error, default_audience_id, updated_at
`

type SetInstantlyWebhookParams struct {
	Token      *string
	SecretEnc  []byte
	WebhookID  *string
	WebhookUrl *string
	Status     *int32
	Error      *string
}

func (q *Queries) SetInstantlyWebhook(ctx context.Context, arg SetInstantlyWebhookParams) (CampaignSetting, error) {
	row := q.db.QueryRow(ctx, setInstantlyWebhook,
		arg.Token,
		arg.SecretEnc,
		arg.WebhookID,
		arg.WebhookUrl,
		arg.Status,
		arg.Error,
	)
	var i CampaignSetting
	err := row.Scan(
		&i.ID,
		&i.InstantlyWebhookToken,
		&i.InstantlyWebhookSecretEnc,
		&i.InstantlyWebhookID,
		&i.InstantlyWebhookUrl,
		&i.InstantlyWebhookStatus,
		&i.InstantlyWebhookError,
		&i.DefaultAudienceID,
		&i.UpdatedAt,
	)
	return i, err
}

const setInstantlyWebhookStatus = `-- name: SetInstantlyWebhookStatus :exec
UPDATE campaign_settings
SET instantly_webhook_status = $1,
    instantly_webhook_error  = $2,
    updated_at               = now()
WHERE id = 1
`

type SetInstantlyWebhookStatusParams struct {
	Status *int32
	Error  *string
}

func (q *Queries) SetInstantlyWebhookStatus(ctx context.Context, arg SetInstantlyWebhookStatusParams) error {
	_, err := q.db.Exec(ctx, setInstantlyWebhookStatus, arg.Status, arg.Error)
	return err
}
