// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contacts.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countCampaignContactsByStage = `-- name: CountCampaignContactsByStage :many
SELECT c.lifecycle_stage, count(*)::bigint AS total
FROM contacts c
WHERE c.id IN (SELECT contact_id FROM campaign_leads WHERE campaign_id = $1)
GROUP BY c.lifecycle_stage
`

type CountCampaignContactsByStageRow struct {
	LifecycleStage string
	Total          int64
}

func (q *Queries) CountCampaignContactsByStage(ctx context.Context, campaignID uuid.UUID) ([]CountCampaignContactsByStageRow, error) {
	rows, err := q.db.Query(ctx, countCampaignContactsByStage, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCampaignContactsByStageRow{}
	for rows.Next() {
		var i CountCampaignContactsByStageRow
		if err := rows.Scan(&i.LifecycleStage, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countContactsByStage = `-- name: CountContactsByStage :many
SELECT lifecycle_stage, count(*)::bigint AS total FROM contacts GROUP BY lifecycle_stage
`

type CountContactsByStageRow struct {
	LifecycleStage string
	Total          int64
}

func (q *Queries) CountContactsByStage(ctx context.Context) ([]CountContactsByStageRow, error) {
	rows, err := q.db.Query(ctx, countContactsByStage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountContactsByStageRow{}
	for rows.Next() {
		var i CountContactsByStageRow
		if err := rows.Scan(&i.LifecycleStage, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createContactConsent = `-- name: CreateContactConsent :one
INSERT INTO contact_consents (id, contact_id, source, captured_at, evidence, captured_by, campaign_lead_id, provider_event_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
RETURNING id, contact_id, source, captured_at, evidence, captured_by, campaign_lead_id, provider_event_id, revoked_at, revoke_reason, created_at
`

type CreateContactConsentParams struct {
	ID              uuid.UUID
	ContactID       uuid.UUID
	Source          string
	CapturedAt      time.Time
	Evidence        string
	CapturedBy      string
	CampaignLeadID  uuid.NullUUID
	ProviderEventID uuid.NullUUID
}

func (q *Queries) CreateContactConsent(ctx context.Context, arg CreateContactConsentParams) (ContactConsent, error) {
	row := q.db.QueryRow(ctx, createContactConsent,
		arg.ID,
		arg.ContactID,
		arg.Source,
		arg.CapturedAt,
		arg.Evidence,
		arg.CapturedBy,
		arg.CampaignLeadID,
		arg.ProviderEventID,
	)
	var i ContactConsent
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.CapturedAt,
		&i.Evidence,
		&i.CapturedBy,
		&i.CampaignLeadID,
		&i.ProviderEventID,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const createContactSuppression = `-- name: CreateContactSuppression :one
INSERT INTO contact_suppressions (id, contact_id, reason, source, note, campaign_lead_id, provider_event_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
RETURNING id, contact_id, reason, source, note, campaign_lead_id, provider_event_id, created_at, lifted_at, lifted_note
`

type CreateContactSuppressionParams struct {
	ID              uuid.UUID
	ContactID       uuid.UUID
	Reason          string
	Source          string
	Note            *string
	CampaignLeadID  uuid.NullUUID
	ProviderEventID uuid.NullUUID
}

func (q *Queries) CreateContactSuppression(ctx context.Context, arg CreateContactSuppressionParams) (ContactSuppression, error) {
	row := q.db.QueryRow(ctx, createContactSuppression,
		arg.ID,
		arg.ContactID,
		arg.Reason,
		arg.Source,
		arg.Note,
		arg.CampaignLeadID,
		arg.ProviderEventID,
	)
	var i ContactSuppression
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Reason,
		&i.Source,
		&i.Note,
		&i.CampaignLeadID,
		&i.ProviderEventID,
		&i.CreatedAt,
		&i.LiftedAt,
		&i.LiftedNote,
	)
	return i, err
}

const getActiveConsent = `-- name: GetActiveConsent :one
SELECT id, contact_id, source, captured_at, evidence, captured_by, campaign_lead_id, provider_event_id, revoked_at, revoke_reason, created_at FROM contact_consents WHERE contact_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveConsent(ctx context.Context, contactID uuid.UUID) (ContactConsent, error) {
	row := q.db.QueryRow(ctx, getActiveConsent, contactID)
	var i ContactConsent
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.CapturedAt,
		&i.Evidence,
		&i.CapturedBy,
		&i.CampaignLeadID,
		&i.ProviderEventID,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSuppression = `-- name: GetActiveSuppression :one
SELECT id, contact_id, reason, source, note, campaign_lead_id, provider_event_id, created_at, lifted_at, lifted_note FROM contact_suppressions WHERE contact_id = $1 AND lifted_at IS NULL
`

func (q *Queries) GetActiveSuppression(ctx context.Context, contactID uuid.UUID) (ContactSuppression, error) {
	row := q.db.QueryRow(ctx, getActiveSuppression, contactID)
	var i ContactSuppression
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Reason,
		&i.Source,
		&i.Note,
		&i.CampaignLeadID,
		&i.ProviderEventID,
		&i.CreatedAt,
		&i.LiftedAt,
		&i.LiftedNote,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, email, domain, first_name, last_name, company, title, phone, website, business_id, source, lifecycle_stage, stage_changed_at, suppressed_at, suppression_reason, attributes, last_event_at, created_at, updated_at FROM contacts WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Title,
		&i.Phone,
		&i.Website,
		&i.BusinessID,
		&i.Source,
		&i.LifecycleStage,
		&i.StageChangedAt,
		&i.SuppressedAt,
		&i.SuppressionReason,
		&i.Attributes,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByEmail = `-- name: GetContactByEmail :one
SELECT id, email, domain, first_name, last_name, company, title, phone, website, business_id, source, lifecycle_stage, stage_changed_at, suppressed_at, suppression_reason, attributes, last_event_at, created_at, updated_at FROM contacts WHERE email = $1
`

func (q *Queries) GetContactByEmail(ctx context.Context, email string) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByEmail, email)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Title,
		&i.Phone,
		&i.Website,
		&i.BusinessID,
		&i.Source,
		&i.LifecycleStage,
		&i.StageChangedAt,
		&i.SuppressedAt,
		&i.SuppressionReason,
		&i.Attributes,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactConsent = `-- name: GetContactConsent :one
SELECT id, contact_id, source, captured_at, evidence, captured_by, campaign_lead_id, provider_event_id, revoked_at, revoke_reason, created_at FROM contact_consents WHERE id = $1
`

func (q *Queries) GetContactConsent(ctx context.Context, id uuid.UUID) (ContactConsent, error) {
	row := q.db.QueryRow(ctx, getContactConsent, id)
	var i ContactConsent
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.CapturedAt,
		&i.Evidence,
		&i.CapturedBy,
		&i.CampaignLeadID,
		&i.ProviderEventID,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const getContactSuppression = `-- name: GetContactSuppression :one
SELECT id, contact_id, reason, source, note, campaign_lead_id, provider_event_id, created_at, lifted_at, lifted_note FROM contact_suppressions WHERE id = $1
`

func (q *Queries) GetContactSuppression(ctx context.Context, id uuid.UUID) (ContactSuppression, error) {
	row := q.db.QueryRow(ctx, getContactSuppression, id)
	var i ContactSuppression
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Reason,
		&i.Source,
		&i.Note,
		&i.CampaignLeadID,
		&i.ProviderEventID,
		&i.CreatedAt,
		&i.LiftedAt,
		&i.LiftedNote,
	)
	return i, err
}

const liftContactSuppression = `-- name: LiftContactSuppression :one
UPDATE contacts
SET suppressed_at      = NULL,
    suppression_reason = NULL,
    lifecycle_stage    = $1,
    last_event_at      = now(),
    updated_at         = now()
WHERE id = $2
RETURNING id, email, domain, first_name, last_name, company, title, phone, website, business_id, source, lifecycle_stage, stage_changed_at, suppressed_at, suppression_reason, attributes, last_event_at, created_at, updated_at
`

type LiftContactSuppressionParams struct {
	Stage string
	ID    uuid.UUID
}

func (q *Queries) LiftContactSuppression(ctx context.Context, arg LiftContactSuppressionParams) (Contact, error) {
	row := q.db.QueryRow(ctx, liftContactSuppression, arg.Stage, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Title,
		&i.Phone,
		&i.Website,
		&i.BusinessID,
		&i.Source,
		&i.LifecycleStage,
		&i.StageChangedAt,
		&i.SuppressedAt,
		&i.SuppressionReason,
		&i.Attributes,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const liftSuppression = `-- name: LiftSuppression :one
UPDATE contact_suppressions
SET lifted_at = now(), lifted_note = $1
WHERE id = $2 AND lifted_at IS NULL
RETURNING id, contact_id, reason, source, note, campaign_lead_id, provider_event_id, created_at, lifted_at, lifted_note
`

type LiftSuppressionParams struct {
	Note *string
	ID   uuid.UUID
}

func (q *Queries) LiftSuppression(ctx context.Context, arg LiftSuppressionParams) (ContactSuppression, error) {
	row := q.db.QueryRow(ctx, liftSuppression, arg.Note, arg.ID)
	var i ContactSuppression
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Reason,
		&i.Source,
		&i.Note,
		&i.CampaignLeadID,
		&i.ProviderEventID,
		&i.CreatedAt,
		&i.LiftedAt,
		&i.LiftedNote,
	)
	return i, err
}

const listContactConsents = `-- name: ListContactConsents :many
SELECT id, contact_id, source, captured_at, evidence, captured_by, campaign_lead_id, provider_event_id, revoked_at, revoke_reason, created_at FROM contact_consents WHERE contact_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListContactConsents(ctx context.Context, contactID uuid.UUID) ([]ContactConsent, error) {
	rows, err := q.db.Query(ctx, listContactConsents, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactConsent{}
	for rows.Next() {
		var i ContactConsent
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Source,
			&i.CapturedAt,
			&i.Evidence,
			&i.CapturedBy,
			&i.CampaignLeadID,
			&i.ProviderEventID,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactSuppressions = `-- name: ListContactSuppressions :many
SELECT id, contact_id, reason, source, note, campaign_lead_id, provider_event_id, created_at, lifted_at, lifted_note FROM contact_suppressions WHERE contact_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListContactSuppressions(ctx context.Context, contactID uuid.UUID) ([]ContactSuppression, error) {
	rows, err := q.db.Query(ctx, listContactSuppressions, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactSuppression{}
	for rows.Next() {
		var i ContactSuppression
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Reason,
			&i.Source,
			&i.Note,
			&i.CampaignLeadID,
			&i.ProviderEventID,
			&i.CreatedAt,
			&i.LiftedAt,
			&i.LiftedNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeConsent = `-- name: RevokeConsent :one
UPDATE contact_consents
SET revoked_at = now(), revoke_reason = $1
WHERE id = $2 AND revoked_at IS NULL
RETURNING id, contact_id, source, captured_at, evidence, captured_by, campaign_lead_id, provider_event_id, revoked_at, revoke_reason, created_at
`

type RevokeConsentParams struct {
	Reason *string
	ID     uuid.UUID
}

func (q *Queries) RevokeConsent(ctx context.Context, arg RevokeConsentParams) (ContactConsent, error) {
	row := q.db.QueryRow(ctx, revokeConsent, arg.Reason, arg.ID)
	var i ContactConsent
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.CapturedAt,
		&i.Evidence,
		&i.CapturedBy,
		&i.CampaignLeadID,
		&i.ProviderEventID,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const setContactStage = `-- name: SetContactStage :one
UPDATE contacts
SET lifecycle_stage = $1, last_event_at = now(), updated_at = now()
WHERE id = $2
RETURNING id, email, domain, first_name, last_name, company, title, phone, website, business_id, source, lifecycle_stage, stage_changed_at, suppressed_at, suppression_reason, attributes, last_event_at, created_at, updated_at
`

type SetContactStageParams struct {
	Stage string
	ID    uuid.UUID
}

// The trigger enforces the rules; this statement only moves the pointer.
func (q *Queries) SetContactStage(ctx context.Context, arg SetContactStageParams) (Contact, error) {
	row := q.db.QueryRow(ctx, setContactStage, arg.Stage, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Title,
		&i.Phone,
		&i.Website,
		&i.BusinessID,
		&i.Source,
		&i.LifecycleStage,
		&i.StageChangedAt,
		&i.SuppressedAt,
		&i.SuppressionReason,
		&i.Attributes,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const suppressContact = `-- name: SuppressContact :one
UPDATE contacts
SET suppressed_at      = COALESCE(suppressed_at, now()),
    suppression_reason = $1,
    lifecycle_stage    = $2,
    last_event_at      = now(),
    updated_at         = now()
WHERE id = $3
RETURNING id, email, domain, first_name, last_name, company, title, phone, website, business_id, source, lifecycle_stage, stage_changed_at, suppressed_at, suppression_reason, attributes, last_event_at, created_at, updated_at
`

type SuppressContactParams struct {
	Reason *string
	Stage  string
	ID     uuid.UUID
}

func (q *Queries) SuppressContact(ctx context.Context, arg SuppressContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, suppressContact, arg.Reason, arg.Stage, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Title,
		&i.Phone,
		&i.Website,
		&i.BusinessID,
		&i.Source,
		&i.LifecycleStage,
		&i.StageChangedAt,
		&i.SuppressedAt,
		&i.SuppressionReason,
		&i.Attributes,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchContactEvent = `-- name: TouchContactEvent :exec
UPDATE contacts SET last_event_at = GREATEST(COALESCE(last_event_at, $1), $1) WHERE id = $2
`

type TouchContactEventParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) TouchContactEvent(ctx context.Context, arg TouchContactEventParams) error {
	_, err := q.db.Exec(ctx, touchContactEvent, arg.At, arg.ID)
	return err
}

const updateContactProfile = `-- name: UpdateContactProfile :one
UPDATE contacts
SET first_name = COALESCE($1, first_name),
    last_name  = COALESCE($2, last_name),
    company    = COALESCE($3, company),
    title      = COALESCE($4, title),
    phone      = COALESCE($5, phone),
    website    = COALESCE($6, website),
    attributes = COALESCE($7, attributes),
    updated_at = now()
WHERE id = $8
RETURNING id, email, domain, first_name, last_name, company, title, phone, website, business_id, source, lifecycle_stage, stage_changed_at, suppressed_at, suppression_reason, attributes, last_event_at, created_at, updated_at
`

type UpdateContactProfileParams struct {
	FirstName  *string
	LastName   *string
	Company    *string
	Title      *string
	Phone      *string
	Website    *string
	Attributes []byte
	ID         uuid.UUID
}

func (q *Queries) UpdateContactProfile(ctx context.Context, arg UpdateContactProfileParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContactProfile,
		arg.FirstName,
		arg.LastName,
		arg.Company,
		arg.Title,
		arg.Phone,
		arg.Website,
		arg.Attributes,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Title,
		&i.Phone,
		&i.Website,
		&i.BusinessID,
		&i.Source,
		&i.LifecycleStage,
		&i.StageChangedAt,
		&i.SuppressedAt,
		&i.SuppressionReason,
		&i.Attributes,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContact = `-- name: UpsertContact :one
INSERT INTO contacts (id, email, domain, first_name, last_name, company, title, phone, website, business_id, source)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11)
ON CONFLICT (email) DO UPDATE
SET first_name  = COALESCE(contacts.first_name, EXCLUDED.first_name),
    last_name   = COALESCE(contacts.last_name, EXCLUDED.last_name),
    company     = COALESCE(contacts.company, EXCLUDED.company),
    title       = COALESCE(contacts.title, EXCLUDED.title),
    phone       = COALESCE(contacts.phone, EXCLUDED.phone),
    website     = COALESCE(contacts.website, EXCLUDED.website),
    business_id = COALESCE(contacts.business_id, EXCLUDED.business_id),
    updated_at  = now()
RETURNING id, email, domain, first_name, last_name, company, title, phone, website, business_id, source, lifecycle_stage, stage_changed_at, suppressed_at, suppression_reason, attributes, last_event_at, created_at, updated_at
`

type UpsertContactParams struct {
	ID         uuid.UUID
	Email      string
	Domain     string
	FirstName  *string
	LastName   *string
	Company    *string
	Title      *string
	Phone      *string
	Website    *string
	BusinessID uuid.NullUUID
	Source     string
}

// Creates the contact the first time an address is seen. The no-op DO UPDATE lets one
// statement insert and return the existing row; it never overwrites the stage.
func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, upsertContact,
		arg.ID,
		arg.Email,
		arg.Domain,
		arg.FirstName,
		arg.LastName,
		arg.Company,
		arg.Title,
		arg.Phone,
		arg.Website,
		arg.BusinessID,
		arg.Source,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Title,
		&i.Phone,
		&i.Website,
		&i.BusinessID,
		&i.Source,
		&i.LifecycleStage,
		&i.StageChangedAt,
		&i.SuppressedAt,
		&i.SuppressionReason,
		&i.Attributes,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
