// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: domains.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countDomainPurchases = `-- name: CountDomainPurchases :one
SELECT count(*) FROM domain_purchases
`

func (q *Queries) CountDomainPurchases(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDomainPurchases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomainPurchase = `-- name: CreateDomainPurchase :one
INSERT INTO domain_purchases (id, auto_renew, currency, quoted_total_cents, item_count)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status, auto_renew, currency, quoted_total_cents, item_count, error, created_at, started_at, finished_at, updated_at
`

type CreateDomainPurchaseParams struct {
	ID               uuid.UUID
	AutoRenew        bool
	Currency         string
	QuotedTotalCents int64
	ItemCount        int16
}

func (q *Queries) CreateDomainPurchase(ctx context.Context, arg CreateDomainPurchaseParams) (DomainPurchase, error) {
	row := q.db.QueryRow(ctx, createDomainPurchase,
		arg.ID,
		arg.AutoRenew,
		arg.Currency,
		arg.QuotedTotalCents,
		arg.ItemCount,
	)
	var i DomainPurchase
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AutoRenew,
		&i.Currency,
		&i.QuotedTotalCents,
		&i.ItemCount,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDomainPurchaseItem = `-- name: CreateDomainPurchaseItem :one
INSERT INTO domain_purchase_items (id, purchase_id, position, domain_name, quoted_cost_cents,
                                   cost_cents, renewal_cost_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, purchase_id, position, domain_name, status, quoted_cost_cents, cost_cents, renewal_cost_cents, register_attempts, attempted_at, error_code, error_message, registered_at, expires_at, created_at, updated_at
`

type CreateDomainPurchaseItemParams struct {
	ID               uuid.UUID
	PurchaseID       uuid.UUID
	Position         int16
	DomainName       string
	QuotedCostCents  int64
	CostCents        *int64
	RenewalCostCents *int64
}

func (q *Queries) CreateDomainPurchaseItem(ctx context.Context, arg CreateDomainPurchaseItemParams) (DomainPurchaseItem, error) {
	row := q.db.QueryRow(ctx, createDomainPurchaseItem,
		arg.ID,
		arg.PurchaseID,
		arg.Position,
		arg.DomainName,
		arg.QuotedCostCents,
		arg.CostCents,
		arg.RenewalCostCents,
	)
	var i DomainPurchaseItem
	err := row.Scan(
		&i.ID,
		&i.PurchaseID,
		&i.Position,
		&i.DomainName,
		&i.Status,
		&i.QuotedCostCents,
		&i.CostCents,
		&i.RenewalCostCents,
		&i.RegisterAttempts,
		&i.AttemptedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RegisteredAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failDomainItem = `-- name: FailDomainItem :exec
UPDATE domain_purchase_items
SET status        = $1,
    error_code    = $2,
    error_message = $3,
    updated_at    = now()
WHERE id = $4 AND status IN ('pending', 'registering')
`

type FailDomainItemParams struct {
	Status       string
	ErrorCode    *string
	ErrorMessage *string
	ID           uuid.UUID
}

func (q *Queries) FailDomainItem(ctx context.Context, arg FailDomainItemParams) error {
	_, err := q.db.Exec(ctx, failDomainItem,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const finishDomainPurchase = `-- name: FinishDomainPurchase :one
UPDATE domain_purchases
SET status      = $1,
    error       = $2,
    finished_at = now(),
    updated_at  = now()
WHERE id = $3 AND status IN ('queued', 'processing')
RETURNING id, status, auto_renew, currency, quoted_total_cents, item_count, error, created_at, started_at, finished_at, updated_at
`

type FinishDomainPurchaseParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) FinishDomainPurchase(ctx context.Context, arg FinishDomainPurchaseParams) (DomainPurchase, error) {
	row := q.db.QueryRow(ctx, finishDomainPurchase, arg.Status, arg.Error, arg.ID)
	var i DomainPurchase
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AutoRenew,
		&i.Currency,
		&i.QuotedTotalCents,
		&i.ItemCount,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveDomainPurchase = `-- name: GetActiveDomainPurchase :one
SELECT id, status, auto_renew, currency, quoted_total_cents, item_count, error, created_at, started_at, finished_at, updated_at FROM domain_purchases
WHERE status IN ('queued', 'processing')
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetActiveDomainPurchase(ctx context.Context) (DomainPurchase, error) {
	row := q.db.QueryRow(ctx, getActiveDomainPurchase)
	var i DomainPurchase
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AutoRenew,
		&i.Currency,
		&i.QuotedTotalCents,
		&i.ItemCount,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainPurchase = `-- name: GetDomainPurchase :one
SELECT id, status, auto_renew, currency, quoted_total_cents, item_count, error, created_at, started_at, finished_at, updated_at FROM domain_purchases WHERE id = $1
`

func (q *Queries) GetDomainPurchase(ctx context.Context, id uuid.UUID) (DomainPurchase, error) {
	row := q.db.QueryRow(ctx, getDomainPurchase, id)
	var i DomainPurchase
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AutoRenew,
		&i.Currency,
		&i.QuotedTotalCents,
		&i.ItemCount,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrarSettings = `-- name: GetRegistrarSettings :one
SELECT id, cloudflare_account_id, updated_at FROM registrar_settings WHERE id = 1
`

func (q *Queries) GetRegistrarSettings(ctx context.Context) (RegistrarSetting, error) {
	row := q.db.QueryRow(ctx, getRegistrarSettings)
	var i RegistrarSetting
	err := row.Scan(&i.ID, &i.CloudflareAccountID, &i.UpdatedAt)
	return i, err
}

const listDomainPurchaseItems = `-- name: ListDomainPurchaseItems :many
SELECT id, purchase_id, position, domain_name, status, quoted_cost_cents, cost_cents, renewal_cost_cents, register_attempts, attempted_at, error_code, error_message, registered_at, expires_at, created_at, updated_at FROM domain_purchase_items WHERE purchase_id = $1 ORDER BY position
`

func (q *Queries) ListDomainPurchaseItems(ctx context.Context, purchaseID uuid.UUID) ([]DomainPurchaseItem, error) {
	rows, err := q.db.Query(ctx, listDomainPurchaseItems, purchaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainPurchaseItem{}
	for rows.Next() {
		var i DomainPurchaseItem
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseID,
			&i.Position,
			&i.DomainName,
			&i.Status,
			&i.QuotedCostCents,
			&i.CostCents,
			&i.RenewalCostCents,
			&i.RegisterAttempts,
			&i.AttemptedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.RegisteredAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainPurchaseItemsFor = `-- name: ListDomainPurchaseItemsFor :many
SELECT id, purchase_id, position, domain_name, status, quoted_cost_cents, cost_cents, renewal_cost_cents, register_attempts, attempted_at, error_code, error_message, registered_at, expires_at, created_at, updated_at FROM domain_purchase_items
WHERE purchase_id = ANY($1::uuid[])
ORDER BY purchase_id, position
`

func (q *Queries) ListDomainPurchaseItemsFor(ctx context.Context, purchaseIds []uuid.UUID) ([]DomainPurchaseItem, error) {
	rows, err := q.db.Query(ctx, listDomainPurchaseItemsFor, purchaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainPurchaseItem{}
	for rows.Next() {
		var i DomainPurchaseItem
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseID,
			&i.Position,
			&i.DomainName,
			&i.Status,
			&i.QuotedCostCents,
			&i.CostCents,
			&i.RenewalCostCents,
			&i.RegisterAttempts,
			&i.AttemptedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.RegisteredAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainPurchases = `-- name: ListDomainPurchases :many
SELECT id, status, auto_renew, currency, quoted_total_cents, item_count, error, created_at, started_at, finished_at, updated_at FROM domain_purchases
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListDomainPurchasesParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListDomainPurchases(ctx context.Context, arg ListDomainPurchasesParams) ([]DomainPurchase, error) {
	rows, err := q.db.Query(ctx, listDomainPurchases, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainPurchase{}
	for rows.Next() {
		var i DomainPurchase
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AutoRenew,
			&i.Currency,
			&i.QuotedTotalCents,
			&i.ItemCount,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDomainItemRegistering = `-- name: MarkDomainItemRegistering :one
UPDATE domain_purchase_items
SET status            = 'registering',
    register_attempts = register_attempts + 1,
    attempted_at      = now(),
    updated_at        = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, purchase_id, position, domain_name, status, quoted_cost_cents, cost_cents, renewal_cost_cents, register_attempts, attempted_at, error_code, error_message, registered_at, expires_at, created_at, updated_at
`

// The row says "registering" before the billable call is made, so a worker that dies
// mid-call leaves a row that is reconciled with Cloudflare instead of retried blind.
func (q *Queries) MarkDomainItemRegistering(ctx context.Context, id uuid.UUID) (DomainPurchaseItem, error) {
	row := q.db.QueryRow(ctx, markDomainItemRegistering, id)
	var i DomainPurchaseItem
	err := row.Scan(
		&i.ID,
		&i.PurchaseID,
		&i.Position,
		&i.DomainName,
		&i.Status,
		&i.QuotedCostCents,
		&i.CostCents,
		&i.RenewalCostCents,
		&i.RegisterAttempts,
		&i.AttemptedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RegisteredAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetDomainItemPending = `-- name: ResetDomainItemPending :exec
UPDATE domain_purchase_items
SET status = 'pending', updated_at = now()
WHERE id = $1 AND status = 'registering'
`

func (q *Queries) ResetDomainItemPending(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetDomainItemPending, id)
	return err
}

const setDomainItemPrice = `-- name: SetDomainItemPrice :exec
UPDATE domain_purchase_items
SET cost_cents         = $1,
    renewal_cost_cents = $2,
    updated_at         = now()
WHERE id = $3 AND status = 'pending'
`

type SetDomainItemPriceParams struct {
	CostCents        *int64
	RenewalCostCents *int64
	ID               uuid.UUID
}

func (q *Queries) SetDomainItemPrice(ctx context.Context, arg SetDomainItemPriceParams) error {
	_, err := q.db.Exec(ctx, setDomainItemPrice, arg.CostCents, arg.RenewalCostCents, arg.ID)
	return err
}

const setRegistrarAccountID = `-- name: SetRegistrarAccountID :one
UPDATE registrar_settings
SET cloudflare_account_id = $1,
    updated_at            = now()
WHERE id = 1
RETURNING id, cloudflare_account_id, updated_at
`

func (q *Queries) SetRegistrarAccountID(ctx context.Context, accountID *string) (RegistrarSetting, error) {
	row := q.db.QueryRow(ctx, setRegistrarAccountID, accountID)
	var i RegistrarSetting
	err := row.Scan(&i.ID, &i.CloudflareAccountID, &i.UpdatedAt)
	return i, err
}

const startDomainPurchase = `-- name: StartDomainPurchase :one
UPDATE domain_purchases
SET status     = 'processing',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id = $1 AND status IN ('queued', 'processing')
RETURNING id, status, auto_renew, currency, quoted_total_cents, item_count, error, created_at, started_at, finished_at, updated_at
`

func (q *Queries) StartDomainPurchase(ctx context.Context, id uuid.UUID) (DomainPurchase, error) {
	row := q.db.QueryRow(ctx, startDomainPurchase, id)
	var i DomainPurchase
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AutoRenew,
		&i.Currency,
		&i.QuotedTotalCents,
		&i.ItemCount,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const succeedDomainItem = `-- name: SucceedDomainItem :exec
UPDATE domain_purchase_items
SET status        = 'succeeded',
    registered_at = COALESCE($1, now()),
    expires_at    = $2,
    error_code    = NULL,
    error_message = NULL,
    updated_at    = now()
WHERE id = $3 AND status IN ('pending', 'registering')
`

type SucceedDomainItemParams struct {
	RegisteredAt *time.Time
	ExpiresAt    *time.Time
	ID           uuid.UUID
}

func (q *Queries) SucceedDomainItem(ctx context.Context, arg SucceedDomainItemParams) error {
	_, err := q.db.Exec(ctx, succeedDomainItem, arg.RegisteredAt, arg.ExpiresAt, arg.ID)
	return err
}
