// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: email_verifications.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const claimThirdPartySend = `-- name: ClaimThirdPartySend :one
UPDATE email_verifications
SET third_party_sent_at = now(),
    updated_at          = now()
WHERE id = $1
  AND third_party_sent_at IS NULL
RETURNING id, email, domain, pass1_score, pass1_checks, pass1_hard_fail, pass1_verified_at, pass2_score, pass2_status, pass2_raw, pass2_source_id, pass2_credits, pass2_verified_at, final_score, verification_tag, typo_suggestion, last_error, created_at, updated_at, free_score, free_scored_at, provider_results, third_party_sent_at, domain_suffixes
`

// The hard check that stops an address reaching a third party twice.
//
// It is a compare-and-set, not a read followed by a write: two concurrent runs racing
// over the same address both reach this statement, and exactly one of them updates a
// row. The loser gets no rows back and must skip. Nothing is billed before this
// succeeds, so the claim is what authorises the outbound call.
func (q *Queries) ClaimThirdPartySend(ctx context.Context, id uuid.UUID) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, claimThirdPartySend, id)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.Pass1Score,
		&i.Pass1Checks,
		&i.Pass1HardFail,
		&i.Pass1VerifiedAt,
		&i.Pass2Score,
		&i.Pass2Status,
		&i.Pass2Raw,
		&i.Pass2SourceID,
		&i.Pass2Credits,
		&i.Pass2VerifiedAt,
		&i.FinalScore,
		&i.VerificationTag,
		&i.TypoSuggestion,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FreeScore,
		&i.FreeScoredAt,
		&i.ProviderResults,
		&i.ThirdPartySentAt,
		&i.DomainSuffixes,
	)
	return i, err
}

const clearTypoSuggestion = `-- name: ClearTypoSuggestion :exec
UPDATE email_verifications
SET typo_suggestion = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) ClearTypoSuggestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTypoSuggestion, id)
	return err
}

const deleteShadowedBusinessEmails = `-- name: DeleteShadowedBusinessEmails :execrows
DELETE FROM business_emails old
WHERE old.email = $1
  AND EXISTS (SELECT 1
              FROM business_emails current
              WHERE current.business_id = old.business_id
                AND current.email = $2)
`

type DeleteShadowedBusinessEmailsParams struct {
	OldEmail string
	NewEmail string
}

// When a business already holds the corrected address, its typo'd row is dropped
// rather than updated, because (business_id, email) is unique.
func (q *Queries) DeleteShadowedBusinessEmails(ctx context.Context, arg DeleteShadowedBusinessEmailsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShadowedBusinessEmails, arg.OldEmail, arg.NewEmail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailVerification = `-- name: GetEmailVerification :one
SELECT id, email, domain, pass1_score, pass1_checks, pass1_hard_fail, pass1_verified_at, pass2_score, pass2_status, pass2_raw, pass2_source_id, pass2_credits, pass2_verified_at, final_score, verification_tag, typo_suggestion, last_error, created_at, updated_at, free_score, free_scored_at, provider_results, third_party_sent_at, domain_suffixes FROM email_verifications WHERE id = $1
`

func (q *Queries) GetEmailVerification(ctx context.Context, id uuid.UUID) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerification, id)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.Pass1Score,
		&i.Pass1Checks,
		&i.Pass1HardFail,
		&i.Pass1VerifiedAt,
		&i.Pass2Score,
		&i.Pass2Status,
		&i.Pass2Raw,
		&i.Pass2SourceID,
		&i.Pass2Credits,
		&i.Pass2VerifiedAt,
		&i.FinalScore,
		&i.VerificationTag,
		&i.TypoSuggestion,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FreeScore,
		&i.FreeScoredAt,
		&i.ProviderResults,
		&i.ThirdPartySentAt,
		&i.DomainSuffixes,
	)
	return i, err
}

const getEmailVerificationByEmail = `-- name: GetEmailVerificationByEmail :one
SELECT id, email, domain, pass1_score, pass1_checks, pass1_hard_fail, pass1_verified_at, pass2_score, pass2_status, pass2_raw, pass2_source_id, pass2_credits, pass2_verified_at, final_score, verification_tag, typo_suggestion, last_error, created_at, updated_at, free_score, free_scored_at, provider_results, third_party_sent_at, domain_suffixes FROM email_verifications WHERE email = $1
`

func (q *Queries) GetEmailVerificationByEmail(ctx context.Context, email string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByEmail, email)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.Pass1Score,
		&i.Pass1Checks,
		&i.Pass1HardFail,
		&i.Pass1VerifiedAt,
		&i.Pass2Score,
		&i.Pass2Status,
		&i.Pass2Raw,
		&i.Pass2SourceID,
		&i.Pass2Credits,
		&i.Pass2VerifiedAt,
		&i.FinalScore,
		&i.VerificationTag,
		&i.TypoSuggestion,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FreeScore,
		&i.FreeScoredAt,
		&i.ProviderResults,
		&i.ThirdPartySentAt,
		&i.DomainSuffixes,
	)
	return i, err
}

const listBusinessIDsForEmail = `-- name: ListBusinessIDsForEmail :many
SELECT DISTINCT business_id FROM business_emails WHERE email = $1
`

func (q *Queries) ListBusinessIDsForEmail(ctx context.Context, email string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listBusinessIDsForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var business_id uuid.UUID
		if err := rows.Scan(&business_id); err != nil {
			return nil, err
		}
		items = append(items, business_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessesForEmail = `-- name: ListBusinessesForEmail :many
SELECT b.id, b.name
FROM business_emails be
         JOIN businesses b ON b.id = be.business_id
WHERE be.email = $1
ORDER BY b.name, b.id
`

type ListBusinessesForEmailRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListBusinessesForEmail(ctx context.Context, email string) ([]ListBusinessesForEmailRow, error) {
	rows, err := q.db.Query(ctx, listBusinessesForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessesForEmailRow{}
	for rows.Next() {
		var i ListBusinessesForEmailRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseThirdPartySend = `-- name: ReleaseThirdPartySend :execrows
UPDATE email_verifications
SET third_party_sent_at = NULL,
    updated_at          = now()
WHERE id = $1
  AND pass2_verified_at IS NULL
`

// Gives the claim back when the call never reached the provider: a rejected API key,
// a throttle, a transport failure. Our own infrastructure failing must not spend an
// address's one and only send. The pass2_verified_at guard means a claim that did
// produce a verdict can never be released, and the database enforces that too.
func (q *Queries) ReleaseThirdPartySend(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseThirdPartySend, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retargetBusinessEmails = `-- name: RetargetBusinessEmails :execrows
UPDATE business_emails
SET email = $1
WHERE email = $2
`

type RetargetBusinessEmailsParams struct {
	NewEmail string
	OldEmail string
}

func (q *Queries) RetargetBusinessEmails(ctx context.Context, arg RetargetBusinessEmailsParams) (int64, error) {
	result, err := q.db.Exec(ctx, retargetBusinessEmails, arg.NewEmail, arg.OldEmail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVerificationError = `-- name: SetVerificationError :exec
UPDATE email_verifications
SET last_error = $1, updated_at = now()
WHERE id = $2
`

type SetVerificationErrorParams struct {
	LastError *string
	ID        uuid.UUID
}

func (q *Queries) SetVerificationError(ctx context.Context, arg SetVerificationErrorParams) error {
	_, err := q.db.Exec(ctx, setVerificationError, arg.LastError, arg.ID)
	return err
}

const updateVerificationPass1 = `-- name: UpdateVerificationPass1 :one
UPDATE email_verifications
SET pass1_score       = $1,
    pass1_checks      = $2,
    pass1_hard_fail   = $3,
    pass1_verified_at = now(),
    free_score        = $4,
    free_scored_at    = now(),
    provider_results  = $5,
    typo_suggestion   = $6,
    final_score       = $7,
    verification_tag  = $8,
    last_error        = NULL,
    updated_at        = now()
WHERE id = $9
RETURNING id, email, domain, pass1_score, pass1_checks, pass1_hard_fail, pass1_verified_at, pass2_score, pass2_status, pass2_raw, pass2_source_id, pass2_credits, pass2_verified_at, final_score, verification_tag, typo_suggestion, last_error, created_at, updated_at, free_score, free_scored_at, provider_results, third_party_sent_at, domain_suffixes
`

type UpdateVerificationPass1Params struct {
	Pass1Score      int32
	Pass1Checks     []byte
	Pass1HardFail   *string
	FreeScore       int32
	ProviderResults []byte
	TypoSuggestion  *string
	FinalScore      int32
	VerificationTag string
	ID              uuid.UUID
}

// The free stage writes the local pipeline's own breakdown and the weighted result of
// every free provider in one statement, so a row can never show a free score without
// the breakdown that explains it.
func (q *Queries) UpdateVerificationPass1(ctx context.Context, arg UpdateVerificationPass1Params) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, updateVerificationPass1,
		arg.Pass1Score,
		arg.Pass1Checks,
		arg.Pass1HardFail,
		arg.FreeScore,
		arg.ProviderResults,
		arg.TypoSuggestion,
		arg.FinalScore,
		arg.VerificationTag,
		arg.ID,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.Pass1Score,
		&i.Pass1Checks,
		&i.Pass1HardFail,
		&i.Pass1VerifiedAt,
		&i.Pass2Score,
		&i.Pass2Status,
		&i.Pass2Raw,
		&i.Pass2SourceID,
		&i.Pass2Credits,
		&i.Pass2VerifiedAt,
		&i.FinalScore,
		&i.VerificationTag,
		&i.TypoSuggestion,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FreeScore,
		&i.FreeScoredAt,
		&i.ProviderResults,
		&i.ThirdPartySentAt,
		&i.DomainSuffixes,
	)
	return i, err
}

const updateVerificationPass2 = `-- name: UpdateVerificationPass2 :one
UPDATE email_verifications
SET pass2_score       = $1,
    pass2_status      = $2,
    pass2_raw         = $3,
    pass2_source_id   = $4,
    pass2_credits     = pass2_credits + $5,
    pass2_verified_at = now(),
    final_score       = $6,
    verification_tag  = $7,
    last_error        = NULL,
    updated_at        = now()
WHERE id = $8
RETURNING id, email, domain, pass1_score, pass1_checks, pass1_hard_fail, pass1_verified_at, pass2_score, pass2_status, pass2_raw, pass2_source_id, pass2_credits, pass2_verified_at, final_score, verification_tag, typo_suggestion, last_error, created_at, updated_at, free_score, free_scored_at, provider_results, third_party_sent_at, domain_suffixes
`

type UpdateVerificationPass2Params struct {
	Pass2Score      *int32
	Pass2Status     *string
	Pass2Raw        []byte
	Pass2SourceID   uuid.NullUUID
	Credits         int32
	FinalScore      int32
	VerificationTag string
	ID              uuid.UUID
}

// A billable outcome: deliverable, risky or undeliverable. Written once and never
// again; third_party_sent_at is already held by the claim that authorised the call.
func (q *Queries) UpdateVerificationPass2(ctx context.Context, arg UpdateVerificationPass2Params) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, updateVerificationPass2,
		arg.Pass2Score,
		arg.Pass2Status,
		arg.Pass2Raw,
		arg.Pass2SourceID,
		arg.Credits,
		arg.FinalScore,
		arg.VerificationTag,
		arg.ID,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.Pass1Score,
		&i.Pass1Checks,
		&i.Pass1HardFail,
		&i.Pass1VerifiedAt,
		&i.Pass2Score,
		&i.Pass2Status,
		&i.Pass2Raw,
		&i.Pass2SourceID,
		&i.Pass2Credits,
		&i.Pass2VerifiedAt,
		&i.FinalScore,
		&i.VerificationTag,
		&i.TypoSuggestion,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FreeScore,
		&i.FreeScoredAt,
		&i.ProviderResults,
		&i.ThirdPartySentAt,
		&i.DomainSuffixes,
	)
	return i, err
}

const updateVerificationPass2Inconclusive = `-- name: UpdateVerificationPass2Inconclusive :one
UPDATE email_verifications
SET pass2_status  = $1,
    pass2_raw     = $2,
    pass2_credits = pass2_credits + $3,
    last_error    = $4,
    updated_at    = now()
WHERE id = $5
RETURNING id, email, domain, pass1_score, pass1_checks, pass1_hard_fail, pass1_verified_at, pass2_score, pass2_status, pass2_raw, pass2_source_id, pass2_credits, pass2_verified_at, final_score, verification_tag, typo_suggestion, last_error, created_at, updated_at, free_score, free_scored_at, provider_results, third_party_sent_at, domain_suffixes
`

type UpdateVerificationPass2InconclusiveParams struct {
	Pass2Status *string
	Pass2Raw    []byte
	Credits     int32
	LastError   *string
	ID          uuid.UUID
}

// "unknown" and hard errors keep the free score and store no verdict, so
// pass2_verified_at stays as it was. Whether the address may be tried again is not
// decided here but by third_party_sent_at: an answer of "unknown" came from the
// provider and keeps the lock, while a call that never arrived releases it.
func (q *Queries) UpdateVerificationPass2Inconclusive(ctx context.Context, arg UpdateVerificationPass2InconclusiveParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, updateVerificationPass2Inconclusive,
		arg.Pass2Status,
		arg.Pass2Raw,
		arg.Credits,
		arg.LastError,
		arg.ID,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.Pass1Score,
		&i.Pass1Checks,
		&i.Pass1HardFail,
		&i.Pass1VerifiedAt,
		&i.Pass2Score,
		&i.Pass2Status,
		&i.Pass2Raw,
		&i.Pass2SourceID,
		&i.Pass2Credits,
		&i.Pass2VerifiedAt,
		&i.FinalScore,
		&i.VerificationTag,
		&i.TypoSuggestion,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FreeScore,
		&i.FreeScoredAt,
		&i.ProviderResults,
		&i.ThirdPartySentAt,
		&i.DomainSuffixes,
	)
	return i, err
}

const upsertEmailVerification = `-- name: UpsertEmailVerification :one
INSERT INTO email_verifications (id, email, domain)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE SET updated_at = email_verifications.updated_at
RETURNING id, email, domain, pass1_score, pass1_checks, pass1_hard_fail, pass1_verified_at, pass2_score, pass2_status, pass2_raw, pass2_source_id, pass2_credits, pass2_verified_at, final_score, verification_tag, typo_suggestion, last_error, created_at, updated_at, free_score, free_scored_at, provider_results, third_party_sent_at, domain_suffixes
`

type UpsertEmailVerificationParams struct {
	ID     uuid.UUID
	Email  string
	Domain string
}

// Creates the row the first time an address is verified. The no-op DO UPDATE lets a
// single statement both insert and return the existing row.
func (q *Queries) UpsertEmailVerification(ctx context.Context, arg UpsertEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, upsertEmailVerification, arg.ID, arg.Email, arg.Domain)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Domain,
		&i.Pass1Score,
		&i.Pass1Checks,
		&i.Pass1HardFail,
		&i.Pass1VerifiedAt,
		&i.Pass2Score,
		&i.Pass2Status,
		&i.Pass2Raw,
		&i.Pass2SourceID,
		&i.Pass2Credits,
		&i.Pass2VerifiedAt,
		&i.FinalScore,
		&i.VerificationTag,
		&i.TypoSuggestion,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FreeScore,
		&i.FreeScoredAt,
		&i.ProviderResults,
		&i.ThirdPartySentAt,
		&i.DomainSuffixes,
	)
	return i, err
}
