// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: email_sends.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getEmailSend = `-- name: GetEmailSend :one
SELECT id, campaign_lead_id, assignment_id, campaign_id, contact_id, step, variant_id, sending_account_email, sending_account_id, instantly_email_id, provider_message_id, subject_snapshot, sent_at, first_opened_at, last_opened_at, open_count, first_clicked_at, last_clicked_at, click_count, replied_at, reply_classification, bounced_at, unsubscribed_at, source, created_at, updated_at FROM email_sends WHERE campaign_lead_id = $1 AND step = $2
`

type GetEmailSendParams struct {
	CampaignLeadID uuid.UUID
	Step           int32
}

func (q *Queries) GetEmailSend(ctx context.Context, arg GetEmailSendParams) (EmailSend, error) {
	row := q.db.QueryRow(ctx, getEmailSend, arg.CampaignLeadID, arg.Step)
	var i EmailSend
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.AssignmentID,
		&i.CampaignID,
		&i.ContactID,
		&i.Step,
		&i.VariantID,
		&i.SendingAccountEmail,
		&i.SendingAccountID,
		&i.InstantlyEmailID,
		&i.ProviderMessageID,
		&i.SubjectSnapshot,
		&i.SentAt,
		&i.FirstOpenedAt,
		&i.LastOpenedAt,
		&i.OpenCount,
		&i.FirstClickedAt,
		&i.LastClickedAt,
		&i.ClickCount,
		&i.RepliedAt,
		&i.ReplyClassification,
		&i.BouncedAt,
		&i.UnsubscribedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestEmailSendForLead = `-- name: GetLatestEmailSendForLead :one
SELECT id, campaign_lead_id, assignment_id, campaign_id, contact_id, step, variant_id, sending_account_email, sending_account_id, instantly_email_id, provider_message_id, subject_snapshot, sent_at, first_opened_at, last_opened_at, open_count, first_clicked_at, last_clicked_at, click_count, replied_at, reply_classification, bounced_at, unsubscribed_at, source, created_at, updated_at FROM email_sends WHERE campaign_lead_id = $1 ORDER BY step DESC LIMIT 1
`

func (q *Queries) GetLatestEmailSendForLead(ctx context.Context, campaignLeadID uuid.UUID) (EmailSend, error) {
	row := q.db.QueryRow(ctx, getLatestEmailSendForLead, campaignLeadID)
	var i EmailSend
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.AssignmentID,
		&i.CampaignID,
		&i.ContactID,
		&i.Step,
		&i.VariantID,
		&i.SendingAccountEmail,
		&i.SendingAccountID,
		&i.InstantlyEmailID,
		&i.ProviderMessageID,
		&i.SubjectSnapshot,
		&i.SentAt,
		&i.FirstOpenedAt,
		&i.LastOpenedAt,
		&i.OpenCount,
		&i.FirstClickedAt,
		&i.LastClickedAt,
		&i.ClickCount,
		&i.RepliedAt,
		&i.ReplyClassification,
		&i.BouncedAt,
		&i.UnsubscribedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestSendTimestampForCampaign = `-- name: LatestSendTimestampForCampaign :one
SELECT COALESCE(max(sent_at), '0001-01-01 00:00:00+00'::timestamptz)::timestamptz FROM email_sends WHERE campaign_id = $1
`

// Zero time when the campaign has no sends: max() is NULL there, and the cast
// makes sqlc scan the column into a plain time.Time.
func (q *Queries) LatestSendTimestampForCampaign(ctx context.Context, campaignID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestSendTimestampForCampaign, campaignID)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const listEmailSendsForLead = `-- name: ListEmailSendsForLead :many
SELECT id, campaign_lead_id, assignment_id, campaign_id, contact_id, step, variant_id, sending_account_email, sending_account_id, instantly_email_id, provider_message_id, subject_snapshot, sent_at, first_opened_at, last_opened_at, open_count, first_clicked_at, last_clicked_at, click_count, replied_at, reply_classification, bounced_at, unsubscribed_at, source, created_at, updated_at FROM email_sends WHERE campaign_lead_id = $1 ORDER BY step
`

func (q *Queries) ListEmailSendsForLead(ctx context.Context, campaignLeadID uuid.UUID) ([]EmailSend, error) {
	rows, err := q.db.Query(ctx, listEmailSendsForLead, campaignLeadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailSend{}
	for rows.Next() {
		var i EmailSend
		if err := rows.Scan(
			&i.ID,
			&i.CampaignLeadID,
			&i.AssignmentID,
			&i.CampaignID,
			&i.ContactID,
			&i.Step,
			&i.VariantID,
			&i.SendingAccountEmail,
			&i.SendingAccountID,
			&i.InstantlyEmailID,
			&i.ProviderMessageID,
			&i.SubjectSnapshot,
			&i.SentAt,
			&i.FirstOpenedAt,
			&i.LastOpenedAt,
			&i.OpenCount,
			&i.FirstClickedAt,
			&i.LastClickedAt,
			&i.ClickCount,
			&i.RepliedAt,
			&i.ReplyClassification,
			&i.BouncedAt,
			&i.UnsubscribedAt,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSendBounce = `-- name: RecordSendBounce :exec
UPDATE email_sends SET bounced_at = COALESCE(bounced_at, $1), updated_at = now() WHERE id = $2
`

type RecordSendBounceParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) RecordSendBounce(ctx context.Context, arg RecordSendBounceParams) error {
	_, err := q.db.Exec(ctx, recordSendBounce, arg.At, arg.ID)
	return err
}

const recordSendClick = `-- name: RecordSendClick :exec
UPDATE email_sends
SET first_clicked_at = COALESCE(first_clicked_at, $1),
    last_clicked_at  = GREATEST(COALESCE(last_clicked_at, $1), $1),
    click_count      = click_count + 1,
    updated_at       = now()
WHERE id = $2
`

type RecordSendClickParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) RecordSendClick(ctx context.Context, arg RecordSendClickParams) error {
	_, err := q.db.Exec(ctx, recordSendClick, arg.At, arg.ID)
	return err
}

const recordSendOpen = `-- name: RecordSendOpen :exec
UPDATE email_sends
SET first_opened_at = COALESCE(first_opened_at, $1),
    last_opened_at  = GREATEST(COALESCE(last_opened_at, $1), $1),
    open_count      = open_count + 1,
    updated_at      = now()
WHERE id = $2
`

type RecordSendOpenParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) RecordSendOpen(ctx context.Context, arg RecordSendOpenParams) error {
	_, err := q.db.Exec(ctx, recordSendOpen, arg.At, arg.ID)
	return err
}

const recordSendReply = `-- name: RecordSendReply :exec
UPDATE email_sends
SET replied_at           = COALESCE(replied_at, $1),
    reply_classification = CASE
        WHEN reply_classification IS NULL OR reply_classification IN ('unknown', 'neutral') THEN $2
        ELSE reply_classification END,
    updated_at = now()
WHERE id = $3
`

type RecordSendReplyParams struct {
	At             *time.Time
	Classification *string
	ID             uuid.UUID
}

func (q *Queries) RecordSendReply(ctx context.Context, arg RecordSendReplyParams) error {
	_, err := q.db.Exec(ctx, recordSendReply, arg.At, arg.Classification, arg.ID)
	return err
}

const recordSendUnsubscribe = `-- name: RecordSendUnsubscribe :exec
UPDATE email_sends SET unsubscribed_at = COALESCE(unsubscribed_at, $1), updated_at = now() WHERE id = $2
`

type RecordSendUnsubscribeParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) RecordSendUnsubscribe(ctx context.Context, arg RecordSendUnsubscribeParams) error {
	_, err := q.db.Exec(ctx, recordSendUnsubscribe, arg.At, arg.ID)
	return err
}

const setSendReplyClassification = `-- name: SetSendReplyClassification :exec
UPDATE email_sends SET reply_classification = $1, updated_at = now() WHERE id = $2
`

type SetSendReplyClassificationParams struct {
	Classification *string
	ID             uuid.UUID
}

func (q *Queries) SetSendReplyClassification(ctx context.Context, arg SetSendReplyClassificationParams) error {
	_, err := q.db.Exec(ctx, setSendReplyClassification, arg.Classification, arg.ID)
	return err
}

const upsertEmailSend = `-- name: UpsertEmailSend :one
INSERT INTO email_sends (id, campaign_lead_id, assignment_id, campaign_id, contact_id, step, variant_id,
                         sending_account_email, sending_account_id, instantly_email_id, provider_message_id,
                         subject_snapshot, sent_at, source)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11,
        $12, $13, $14)
ON CONFLICT (campaign_lead_id, step) DO UPDATE
SET assignment_id         = COALESCE(email_sends.assignment_id, EXCLUDED.assignment_id),
    variant_id            = COALESCE(email_sends.variant_id, EXCLUDED.variant_id),
    sending_account_email = COALESCE(email_sends.sending_account_email, EXCLUDED.sending_account_email),
    sending_account_id    = COALESCE(email_sends.sending_account_id, EXCLUDED.sending_account_id),
    instantly_email_id    = COALESCE(email_sends.instantly_email_id, EXCLUDED.instantly_email_id),
    provider_message_id   = COALESCE(email_sends.provider_message_id, EXCLUDED.provider_message_id),
    subject_snapshot      = COALESCE(email_sends.subject_snapshot, EXCLUDED.subject_snapshot),
    sent_at               = LEAST(email_sends.sent_at, EXCLUDED.sent_at),
    updated_at            = now()
RETURNING id, campaign_lead_id, assignment_id, campaign_id, contact_id, step, variant_id, sending_account_email, sending_account_id, instantly_email_id, provider_message_id, subject_snapshot, sent_at, first_opened_at, last_opened_at, open_count, first_clicked_at, last_clicked_at, click_count, replied_at, reply_classification, bounced_at, unsubscribed_at, source, created_at, updated_at
`

type UpsertEmailSendParams struct {
	ID                  uuid.UUID
	CampaignLeadID      uuid.UUID
	AssignmentID        uuid.NullUUID
	CampaignID          uuid.UUID
	ContactID           uuid.UUID
	Step                int32
	VariantID           uuid.NullUUID
	SendingAccountEmail *string
	SendingAccountID    uuid.NullUUID
	InstantlyEmailID    *string
	ProviderMessageID   *string
	SubjectSnapshot     *string
	SentAt              time.Time
	Source              string
}

// One send per lead per step. A second report of the same send (webhook then
// reconcile) fills in what was missing rather than creating a duplicate.
func (q *Queries) UpsertEmailSend(ctx context.Context, arg UpsertEmailSendParams) (EmailSend, error) {
	row := q.db.QueryRow(ctx, upsertEmailSend,
		arg.ID,
		arg.CampaignLeadID,
		arg.AssignmentID,
		arg.CampaignID,
		arg.ContactID,
		arg.Step,
		arg.VariantID,
		arg.SendingAccountEmail,
		arg.SendingAccountID,
		arg.InstantlyEmailID,
		arg.ProviderMessageID,
		arg.SubjectSnapshot,
		arg.SentAt,
		arg.Source,
	)
	var i EmailSend
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.AssignmentID,
		&i.CampaignID,
		&i.ContactID,
		&i.Step,
		&i.VariantID,
		&i.SendingAccountEmail,
		&i.SendingAccountID,
		&i.InstantlyEmailID,
		&i.ProviderMessageID,
		&i.SubjectSnapshot,
		&i.SentAt,
		&i.FirstOpenedAt,
		&i.LastOpenedAt,
		&i.OpenCount,
		&i.FirstClickedAt,
		&i.LastClickedAt,
		&i.ClickCount,
		&i.RepliedAt,
		&i.ReplyClassification,
		&i.BouncedAt,
		&i.UnsubscribedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
