// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: email_content.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addVariantComponent = `-- name: AddVariantComponent :exec
INSERT INTO email_variant_components (variant_id, component_id, position, slot) VALUES ($1, $2, $3, $4)
`

type AddVariantComponentParams struct {
	VariantID   uuid.UUID
	ComponentID uuid.UUID
	Position    int32
	Slot        string
}

func (q *Queries) AddVariantComponent(ctx context.Context, arg AddVariantComponentParams) error {
	_, err := q.db.Exec(ctx, addVariantComponent,
		arg.VariantID,
		arg.ComponentID,
		arg.Position,
		arg.Slot,
	)
	return err
}

const countEmailComponents = `-- name: CountEmailComponents :one
SELECT count(*) FROM email_components
WHERE (cardinality($1::text[]) = 0 OR type = ANY($1::text[]))
  AND (cardinality($2::text[]) = 0 OR status = ANY($2::text[]))
  AND ($3::text IS NULL OR $3::text = ANY(tags))
  AND ($4::text IS NULL OR name ILIKE '%' || $4::text || '%' OR body ILIKE '%' || $4::text || '%')
`

type CountEmailComponentsParams struct {
	Types    []string
	Statuses []string
	Tag      *string
	Q        *string
}

func (q *Queries) CountEmailComponents(ctx context.Context, arg CountEmailComponentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailComponents,
		arg.Types,
		arg.Statuses,
		arg.Tag,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmailVariants = `-- name: CountEmailVariants :one
SELECT count(*) FROM email_variants
WHERE (cardinality($1::text[]) = 0 OR status = ANY($1::text[]))
  AND ($2::int IS NULL OR step = $2::int)
  AND ($3::text IS NULL OR name ILIKE '%' || $3::text || '%')
`

type CountEmailVariantsParams struct {
	Statuses []string
	Step     *int32
	Q        *string
}

func (q *Queries) CountEmailVariants(ctx context.Context, arg CountEmailVariantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailVariants, arg.Statuses, arg.Step, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLockedAssignmentsForComponent = `-- name: CountLockedAssignmentsForComponent :one
SELECT count(*) FROM variant_assignments WHERE locked_at IS NOT NULL AND $1::uuid = ANY(component_ids)
`

func (q *Queries) CountLockedAssignmentsForComponent(ctx context.Context, componentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLockedAssignmentsForComponent, componentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLockedAssignmentsForVariant = `-- name: CountLockedAssignmentsForVariant :one
SELECT count(*) FROM variant_assignments WHERE variant_id = $1 AND locked_at IS NOT NULL
`

func (q *Queries) CountLockedAssignmentsForVariant(ctx context.Context, variantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLockedAssignmentsForVariant, variantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailComponent = `-- name: CreateEmailComponent :one
INSERT INTO email_components (id, type, name, body, status, tags, language, ai_generation_id, placeholders)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
RETURNING id, type, name, body, status, tags, language, ai_generation_id, placeholders, created_at, updated_at, archived_at
`

type CreateEmailComponentParams struct {
	ID             uuid.UUID
	Type           string
	Name           string
	Body           string
	Status         string
	Tags           []string
	Language       string
	AiGenerationID uuid.NullUUID
	Placeholders   []string
}

func (q *Queries) CreateEmailComponent(ctx context.Context, arg CreateEmailComponentParams) (EmailComponent, error) {
	row := q.db.QueryRow(ctx, createEmailComponent,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Body,
		arg.Status,
		arg.Tags,
		arg.Language,
		arg.AiGenerationID,
		arg.Placeholders,
	)
	var i EmailComponent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Body,
		&i.Status,
		&i.Tags,
		&i.Language,
		&i.AiGenerationID,
		&i.Placeholders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createEmailVariant = `-- name: CreateEmailVariant :one
INSERT INTO email_variants (id, name, step, status, subject_template, body_template, component_ids, ai_generation_id, notes)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
RETURNING id, name, step, status, subject_template, body_template, component_ids, ai_generation_id, notes, created_at, updated_at, archived_at
`

type CreateEmailVariantParams struct {
	ID              uuid.UUID
	Name            string
	Step            int32
	Status          string
	SubjectTemplate string
	BodyTemplate    string
	ComponentIds    []uuid.UUID
	AiGenerationID  uuid.NullUUID
	Notes           *string
}

func (q *Queries) CreateEmailVariant(ctx context.Context, arg CreateEmailVariantParams) (EmailVariant, error) {
	row := q.db.QueryRow(ctx, createEmailVariant,
		arg.ID,
		arg.Name,
		arg.Step,
		arg.Status,
		arg.SubjectTemplate,
		arg.BodyTemplate,
		arg.ComponentIds,
		arg.AiGenerationID,
		arg.Notes,
	)
	var i EmailVariant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Step,
		&i.Status,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.ComponentIds,
		&i.AiGenerationID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getEmailComponent = `-- name: GetEmailComponent :one
SELECT id, type, name, body, status, tags, language, ai_generation_id, placeholders, created_at, updated_at, archived_at FROM email_components WHERE id = $1
`

func (q *Queries) GetEmailComponent(ctx context.Context, id uuid.UUID) (EmailComponent, error) {
	row := q.db.QueryRow(ctx, getEmailComponent, id)
	var i EmailComponent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Body,
		&i.Status,
		&i.Tags,
		&i.Language,
		&i.AiGenerationID,
		&i.Placeholders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getEmailVariant = `-- name: GetEmailVariant :one
SELECT id, name, step, status, subject_template, body_template, component_ids, ai_generation_id, notes, created_at, updated_at, archived_at FROM email_variants WHERE id = $1
`

func (q *Queries) GetEmailVariant(ctx context.Context, id uuid.UUID) (EmailVariant, error) {
	row := q.db.QueryRow(ctx, getEmailVariant, id)
	var i EmailVariant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Step,
		&i.Status,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.ComponentIds,
		&i.AiGenerationID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listEmailComponents = `-- name: ListEmailComponents :many
SELECT id, type, name, body, status, tags, language, ai_generation_id, placeholders, created_at, updated_at, archived_at FROM email_components
WHERE (cardinality($1::text[]) = 0 OR type = ANY($1::text[]))
  AND (cardinality($2::text[]) = 0 OR status = ANY($2::text[]))
  AND ($3::text IS NULL OR $3::text = ANY(tags))
  AND ($4::text IS NULL OR name ILIKE '%' || $4::text || '%' OR body ILIKE '%' || $4::text || '%')
ORDER BY type, created_at DESC
LIMIT $6 OFFSET $5
`

type ListEmailComponentsParams struct {
	Types    []string
	Statuses []string
	Tag      *string
	Q        *string
	Off      int32
	Lim      int32
}

func (q *Queries) ListEmailComponents(ctx context.Context, arg ListEmailComponentsParams) ([]EmailComponent, error) {
	rows, err := q.db.Query(ctx, listEmailComponents,
		arg.Types,
		arg.Statuses,
		arg.Tag,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailComponent{}
	for rows.Next() {
		var i EmailComponent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Body,
			&i.Status,
			&i.Tags,
			&i.Language,
			&i.AiGenerationID,
			&i.Placeholders,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailComponentsByIDs = `-- name: ListEmailComponentsByIDs :many
SELECT id, type, name, body, status, tags, language, ai_generation_id, placeholders, created_at, updated_at, archived_at FROM email_components WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListEmailComponentsByIDs(ctx context.Context, ids []uuid.UUID) ([]EmailComponent, error) {
	rows, err := q.db.Query(ctx, listEmailComponentsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailComponent{}
	for rows.Next() {
		var i EmailComponent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Body,
			&i.Status,
			&i.Tags,
			&i.Language,
			&i.AiGenerationID,
			&i.Placeholders,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailVariants = `-- name: ListEmailVariants :many
SELECT id, name, step, status, subject_template, body_template, component_ids, ai_generation_id, notes, created_at, updated_at, archived_at FROM email_variants
WHERE (cardinality($1::text[]) = 0 OR status = ANY($1::text[]))
  AND ($2::int IS NULL OR step = $2::int)
  AND ($3::text IS NULL OR name ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListEmailVariantsParams struct {
	Statuses []string
	Step     *int32
	Q        *string
	Off      int32
	Lim      int32
}

func (q *Queries) ListEmailVariants(ctx context.Context, arg ListEmailVariantsParams) ([]EmailVariant, error) {
	rows, err := q.db.Query(ctx, listEmailVariants,
		arg.Statuses,
		arg.Step,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailVariant{}
	for rows.Next() {
		var i EmailVariant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Step,
			&i.Status,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.ComponentIds,
			&i.AiGenerationID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailVariantsByIDs = `-- name: ListEmailVariantsByIDs :many
SELECT id, name, step, status, subject_template, body_template, component_ids, ai_generation_id, notes, created_at, updated_at, archived_at FROM email_variants WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListEmailVariantsByIDs(ctx context.Context, ids []uuid.UUID) ([]EmailVariant, error) {
	rows, err := q.db.Query(ctx, listEmailVariantsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailVariant{}
	for rows.Next() {
		var i EmailVariant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Step,
			&i.Status,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.ComponentIds,
			&i.AiGenerationID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantComponents = `-- name: ListVariantComponents :many
SELECT vc.position, vc.slot, c.id, c.type, c.name, c.body, c.status, c.tags, c.language, c.ai_generation_id, c.placeholders, c.created_at, c.updated_at, c.archived_at FROM email_variant_components vc
JOIN email_components c ON c.id = vc.component_id
WHERE vc.variant_id = $1
ORDER BY vc.position
`

type ListVariantComponentsRow struct {
	Position       int32
	Slot           string
	ID             uuid.UUID
	Type           string
	Name           string
	Body           string
	Status         string
	Tags           []string
	Language       string
	AiGenerationID uuid.NullUUID
	Placeholders   []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ArchivedAt     *time.Time
}

func (q *Queries) ListVariantComponents(ctx context.Context, variantID uuid.UUID) ([]ListVariantComponentsRow, error) {
	rows, err := q.db.Query(ctx, listVariantComponents, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantComponentsRow{}
	for rows.Next() {
		var i ListVariantComponentsRow
		if err := rows.Scan(
			&i.Position,
			&i.Slot,
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Body,
			&i.Status,
			&i.Tags,
			&i.Language,
			&i.AiGenerationID,
			&i.Placeholders,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsUsingComponent = `-- name: ListVariantsUsingComponent :many
SELECT v.id, v.name, v.step, v.status, v.subject_template, v.body_template, v.component_ids, v.ai_generation_id, v.notes, v.created_at, v.updated_at, v.archived_at FROM email_variants v
JOIN email_variant_components vc ON vc.variant_id = v.id
WHERE vc.component_id = $1
ORDER BY v.created_at DESC
`

func (q *Queries) ListVariantsUsingComponent(ctx context.Context, componentID uuid.UUID) ([]EmailVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsUsingComponent, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailVariant{}
	for rows.Next() {
		var i EmailVariant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Step,
			&i.Status,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.ComponentIds,
			&i.AiGenerationID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceVariantComponents = `-- name: ReplaceVariantComponents :exec
DELETE FROM email_variant_components WHERE variant_id = $1
`

func (q *Queries) ReplaceVariantComponents(ctx context.Context, variantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceVariantComponents, variantID)
	return err
}

const setEmailComponentStatus = `-- name: SetEmailComponentStatus :one
UPDATE email_components
SET status = $1,
    archived_at = CASE WHEN $1 = 'archived' THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, type, name, body, status, tags, language, ai_generation_id, placeholders, created_at, updated_at, archived_at
`

type SetEmailComponentStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetEmailComponentStatus(ctx context.Context, arg SetEmailComponentStatusParams) (EmailComponent, error) {
	row := q.db.QueryRow(ctx, setEmailComponentStatus, arg.Status, arg.ID)
	var i EmailComponent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Body,
		&i.Status,
		&i.Tags,
		&i.Language,
		&i.AiGenerationID,
		&i.Placeholders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const setEmailVariantStatus = `-- name: SetEmailVariantStatus :one
UPDATE email_variants
SET status = $1,
    archived_at = CASE WHEN $1 = 'archived' THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, name, step, status, subject_template, body_template, component_ids, ai_generation_id, notes, created_at, updated_at, archived_at
`

type SetEmailVariantStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetEmailVariantStatus(ctx context.Context, arg SetEmailVariantStatusParams) (EmailVariant, error) {
	row := q.db.QueryRow(ctx, setEmailVariantStatus, arg.Status, arg.ID)
	var i EmailVariant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Step,
		&i.Status,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.ComponentIds,
		&i.AiGenerationID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateEmailComponent = `-- name: UpdateEmailComponent :one
UPDATE email_components
SET name         = COALESCE($1, name),
    body         = COALESCE($2, body),
    tags         = COALESCE($3, tags),
    language     = COALESCE($4, language),
    placeholders = COALESCE($5, placeholders),
    updated_at   = now()
WHERE id = $6
RETURNING id, type, name, body, status, tags, language, ai_generation_id, placeholders, created_at, updated_at, archived_at
`

type UpdateEmailComponentParams struct {
	Name         *string
	Body         *string
	Tags         []string
	Language     *string
	Placeholders []string
	ID           uuid.UUID
}

func (q *Queries) UpdateEmailComponent(ctx context.Context, arg UpdateEmailComponentParams) (EmailComponent, error) {
	row := q.db.QueryRow(ctx, updateEmailComponent,
		arg.Name,
		arg.Body,
		arg.Tags,
		arg.Language,
		arg.Placeholders,
		arg.ID,
	)
	var i EmailComponent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Body,
		&i.Status,
		&i.Tags,
		&i.Language,
		&i.AiGenerationID,
		&i.Placeholders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateEmailVariant = `-- name: UpdateEmailVariant :one
UPDATE email_variants
SET name             = COALESCE($1, name),
    step             = COALESCE($2, step),
    subject_template = COALESCE($3, subject_template),
    body_template    = COALESCE($4, body_template),
    component_ids    = COALESCE($5, component_ids),
    notes            = COALESCE($6, notes),
    updated_at       = now()
WHERE id = $7
RETURNING id, name, step, status, subject_template, body_template, component_ids, ai_generation_id, notes, created_at, updated_at, archived_at
`

type UpdateEmailVariantParams struct {
	Name            *string
	Step            *int32
	SubjectTemplate *string
	BodyTemplate    *string
	ComponentIds    []uuid.UUID
	Notes           *string
	ID              uuid.UUID
}

func (q *Queries) UpdateEmailVariant(ctx context.Context, arg UpdateEmailVariantParams) (EmailVariant, error) {
	row := q.db.QueryRow(ctx, updateEmailVariant,
		arg.Name,
		arg.Step,
		arg.SubjectTemplate,
		arg.BodyTemplate,
		arg.ComponentIds,
		arg.Notes,
		arg.ID,
	)
	var i EmailVariant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Step,
		&i.Status,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.ComponentIds,
		&i.AiGenerationID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
