// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: global_exclusions.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createGlobalExclusion = `-- name: CreateGlobalExclusion :one
INSERT INTO global_exclusions (id, kind, value, display_value, match_mode, reason, source, source_ref_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
RETURNING id, kind, value, display_value, match_mode, reason, source, source_ref_id, created_at, removed_at, removed_note
`

type CreateGlobalExclusionParams struct {
	ID           uuid.UUID
	Kind         string
	Value        string
	DisplayValue string
	MatchMode    string
	Reason       *string
	Source       string
	SourceRefID  uuid.NullUUID
}

func (q *Queries) CreateGlobalExclusion(ctx context.Context, arg CreateGlobalExclusionParams) (GlobalExclusion, error) {
	row := q.db.QueryRow(ctx, createGlobalExclusion,
		arg.ID,
		arg.Kind,
		arg.Value,
		arg.DisplayValue,
		arg.MatchMode,
		arg.Reason,
		arg.Source,
		arg.SourceRefID,
	)
	var i GlobalExclusion
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Value,
		&i.DisplayValue,
		&i.MatchMode,
		&i.Reason,
		&i.Source,
		&i.SourceRefID,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.RemovedNote,
	)
	return i, err
}

const excludeLiveCampaignLeads = `-- name: ExcludeLiveCampaignLeads :many
UPDATE campaign_leads cl
SET status = 'excluded', claimed_at = NULL, last_push_error = 'globally excluded', updated_at = now()
FROM contacts c
WHERE c.id = cl.contact_id
  AND cl.status IN ('pending', 'pushing', 'active', 'paused')
  AND EXISTS (SELECT 1 FROM global_excluded_addresses x WHERE x.email = c.email)
RETURNING cl.id, cl.campaign_id, cl.contact_id, cl.business_id, cl.status, cl.instantly_lead_id, cl.instantly_status, cl.interest_status, cl.interest_label, cl.claimed_at, cl.pushed_at, cl.push_attempts, cl.last_push_error, cl.custom_vars, cl.last_contacted_at, cl.last_opened_at, cl.last_clicked_at, cl.last_replied_at, cl.open_count, cl.click_count, cl.reply_count, cl.created_at, cl.updated_at
`

// The exclusion sweep: every lead that is still waiting or in flight and whose
// contact is now globally excluded stops. Finished and replied leads are history
// and are left as they are.
func (q *Queries) ExcludeLiveCampaignLeads(ctx context.Context) ([]CampaignLead, error) {
	rows, err := q.db.Query(ctx, excludeLiveCampaignLeads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLead{}
	for rows.Next() {
		var i CampaignLead
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.BusinessID,
			&i.Status,
			&i.InstantlyLeadID,
			&i.InstantlyStatus,
			&i.InterestStatus,
			&i.InterestLabel,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.PushAttempts,
			&i.LastPushError,
			&i.CustomVars,
			&i.LastContactedAt,
			&i.LastOpenedAt,
			&i.LastClickedAt,
			&i.LastRepliedAt,
			&i.OpenCount,
			&i.ClickCount,
			&i.ReplyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exclusionCompanyKey = `-- name: ExclusionCompanyKey :one
SELECT coalesce(exclusion_company_key($1::text), '')::text AS key
`

// The company match key is computed by the same function the generated columns
// use, so a rule and the rows it should match can never be normalised differently.
func (q *Queries) ExclusionCompanyKey(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, exclusionCompanyKey, name)
	var key string
	err := row.Scan(&key)
	return key, err
}

const findActiveGlobalExclusion = `-- name: FindActiveGlobalExclusion :one
SELECT id, kind, value, display_value, match_mode, reason, source, source_ref_id, created_at, removed_at, removed_note FROM global_exclusions WHERE kind = $1 AND value = $2 AND removed_at IS NULL
`

type FindActiveGlobalExclusionParams struct {
	Kind  string
	Value string
}

func (q *Queries) FindActiveGlobalExclusion(ctx context.Context, arg FindActiveGlobalExclusionParams) (GlobalExclusion, error) {
	row := q.db.QueryRow(ctx, findActiveGlobalExclusion, arg.Kind, arg.Value)
	var i GlobalExclusion
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Value,
		&i.DisplayValue,
		&i.MatchMode,
		&i.Reason,
		&i.Source,
		&i.SourceRefID,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.RemovedNote,
	)
	return i, err
}

const getGlobalExclusion = `-- name: GetGlobalExclusion :one
SELECT id, kind, value, display_value, match_mode, reason, source, source_ref_id, created_at, removed_at, removed_note FROM global_exclusions WHERE id = $1
`

func (q *Queries) GetGlobalExclusion(ctx context.Context, id uuid.UUID) (GlobalExclusion, error) {
	row := q.db.QueryRow(ctx, getGlobalExclusion, id)
	var i GlobalExclusion
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Value,
		&i.DisplayValue,
		&i.MatchMode,
		&i.Reason,
		&i.Source,
		&i.SourceRefID,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.RemovedNote,
	)
	return i, err
}

const removeGlobalExclusion = `-- name: RemoveGlobalExclusion :one
UPDATE global_exclusions
SET removed_at = now(), removed_note = $1
WHERE id = $2 AND removed_at IS NULL
RETURNING id, kind, value, display_value, match_mode, reason, source, source_ref_id, created_at, removed_at, removed_note
`

type RemoveGlobalExclusionParams struct {
	Note *string
	ID   uuid.UUID
}

func (q *Queries) RemoveGlobalExclusion(ctx context.Context, arg RemoveGlobalExclusionParams) (GlobalExclusion, error) {
	row := q.db.QueryRow(ctx, removeGlobalExclusion, arg.Note, arg.ID)
	var i GlobalExclusion
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Value,
		&i.DisplayValue,
		&i.MatchMode,
		&i.Reason,
		&i.Source,
		&i.SourceRefID,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.RemovedNote,
	)
	return i, err
}

const restoreExcludedCampaignLeads = `-- name: RestoreExcludedCampaignLeads :many
UPDATE campaign_leads cl
SET status = 'pending', last_push_error = NULL, updated_at = now()
FROM contacts c, campaigns camp
WHERE c.id = cl.contact_id AND camp.id = cl.campaign_id
  AND cl.status = 'excluded' AND cl.pushed_at IS NULL AND cl.instantly_lead_id IS NULL
  AND camp.status NOT IN ('completed', 'failed', 'archived')
  AND c.suppressed_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM global_excluded_addresses x WHERE x.email = c.email)
RETURNING cl.id, cl.campaign_id, cl.contact_id, cl.business_id, cl.status, cl.instantly_lead_id, cl.instantly_status, cl.interest_status, cl.interest_label, cl.claimed_at, cl.pushed_at, cl.push_attempts, cl.last_push_error, cl.custom_vars, cl.last_contacted_at, cl.last_opened_at, cl.last_clicked_at, cl.last_replied_at, cl.open_count, cl.click_count, cl.reply_count, cl.created_at, cl.updated_at
`

// When a rule is removed, a lead it took out that never reached the provider goes
// back to pending, unless its contact is suppressed, another rule still covers it,
// or its campaign is over. A lead that was pushed stays excluded: it was removed
// from Instantly and has to be imported again deliberately.
func (q *Queries) RestoreExcludedCampaignLeads(ctx context.Context) ([]CampaignLead, error) {
	rows, err := q.db.Query(ctx, restoreExcludedCampaignLeads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLead{}
	for rows.Next() {
		var i CampaignLead
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.BusinessID,
			&i.Status,
			&i.InstantlyLeadID,
			&i.InstantlyStatus,
			&i.InterestStatus,
			&i.InterestLabel,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.PushAttempts,
			&i.LastPushError,
			&i.CustomVars,
			&i.LastContactedAt,
			&i.LastOpenedAt,
			&i.LastClickedAt,
			&i.LastRepliedAt,
			&i.OpenCount,
			&i.ClickCount,
			&i.ReplyCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
