// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: instantly_cleanup.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addCleanupRunCounts = `-- name: AddCleanupRunCounts :exec
UPDATE instantly_cleanup_runs
SET removed      = removed + $1,
    already_gone = already_gone + $2,
    failed       = failed + $3
WHERE id = $4
`

type AddCleanupRunCountsParams struct {
	Removed     int32
	AlreadyGone int32
	Failed      int32
	ID          uuid.UUID
}

func (q *Queries) AddCleanupRunCounts(ctx context.Context, arg AddCleanupRunCountsParams) error {
	_, err := q.db.Exec(ctx, addCleanupRunCounts,
		arg.Removed,
		arg.AlreadyGone,
		arg.Failed,
		arg.ID,
	)
	return err
}

const countCleanupRuns = `-- name: CountCleanupRuns :one
SELECT count(*) FROM instantly_cleanup_runs
`

func (q *Queries) CountCleanupRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCleanupRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCleanupRun = `-- name: CreateCleanupRun :one
INSERT INTO instantly_cleanup_runs (id, trigger, scope, min_idle_days, include_replied, campaign_ids, max_leads, selected, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6::uuid[], $7, $8, $9)
RETURNING id, trigger, status, scope, min_idle_days, include_replied, campaign_ids, max_leads, selected, removed, already_gone, failed, error, created_at, started_at, finished_at
`

type CreateCleanupRunParams struct {
	ID             uuid.UUID
	Trigger        string
	Scope          string
	MinIdleDays    int32
	IncludeReplied bool
	CampaignIds    []uuid.UUID
	MaxLeads       *int32
	Selected       int32
	CreatedAt      time.Time
}

// The partial unique index refuses a second run while one is queued or running.
// created_at comes from the service clock: every batch measures the idle window
// from it, so it must agree with the clock the preview and the count used.
func (q *Queries) CreateCleanupRun(ctx context.Context, arg CreateCleanupRunParams) (InstantlyCleanupRun, error) {
	row := q.db.QueryRow(ctx, createCleanupRun,
		arg.ID,
		arg.Trigger,
		arg.Scope,
		arg.MinIdleDays,
		arg.IncludeReplied,
		arg.CampaignIds,
		arg.MaxLeads,
		arg.Selected,
		arg.CreatedAt,
	)
	var i InstantlyCleanupRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Status,
		&i.Scope,
		&i.MinIdleDays,
		&i.IncludeReplied,
		&i.CampaignIds,
		&i.MaxLeads,
		&i.Selected,
		&i.Removed,
		&i.AlreadyGone,
		&i.Failed,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishCleanupRun = `-- name: FinishCleanupRun :one
UPDATE instantly_cleanup_runs
SET status = $1, error = $2, finished_at = $3
WHERE id = $4 AND status IN ('queued', 'running')
RETURNING id, trigger, status, scope, min_idle_days, include_replied, campaign_ids, max_leads, selected, removed, already_gone, failed, error, created_at, started_at, finished_at
`

type FinishCleanupRunParams struct {
	Status string
	Error  *string
	At     *time.Time
	ID     uuid.UUID
}

func (q *Queries) FinishCleanupRun(ctx context.Context, arg FinishCleanupRunParams) (InstantlyCleanupRun, error) {
	row := q.db.QueryRow(ctx, finishCleanupRun,
		arg.Status,
		arg.Error,
		arg.At,
		arg.ID,
	)
	var i InstantlyCleanupRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Status,
		&i.Scope,
		&i.MinIdleDays,
		&i.IncludeReplied,
		&i.CampaignIds,
		&i.MaxLeads,
		&i.Selected,
		&i.Removed,
		&i.AlreadyGone,
		&i.Failed,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getActiveCleanupRun = `-- name: GetActiveCleanupRun :one
SELECT id, trigger, status, scope, min_idle_days, include_replied, campaign_ids, max_leads, selected, removed, already_gone, failed, error, created_at, started_at, finished_at FROM instantly_cleanup_runs WHERE status IN ('queued', 'running') ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveCleanupRun(ctx context.Context) (InstantlyCleanupRun, error) {
	row := q.db.QueryRow(ctx, getActiveCleanupRun)
	var i InstantlyCleanupRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Status,
		&i.Scope,
		&i.MinIdleDays,
		&i.IncludeReplied,
		&i.CampaignIds,
		&i.MaxLeads,
		&i.Selected,
		&i.Removed,
		&i.AlreadyGone,
		&i.Failed,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getCleanupRun = `-- name: GetCleanupRun :one
SELECT id, trigger, status, scope, min_idle_days, include_replied, campaign_ids, max_leads, selected, removed, already_gone, failed, error, created_at, started_at, finished_at FROM instantly_cleanup_runs WHERE id = $1
`

func (q *Queries) GetCleanupRun(ctx context.Context, id uuid.UUID) (InstantlyCleanupRun, error) {
	row := q.db.QueryRow(ctx, getCleanupRun, id)
	var i InstantlyCleanupRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Status,
		&i.Scope,
		&i.MinIdleDays,
		&i.IncludeReplied,
		&i.CampaignIds,
		&i.MaxLeads,
		&i.Selected,
		&i.Removed,
		&i.AlreadyGone,
		&i.Failed,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestCleanupRun = `-- name: GetLatestCleanupRun :one
SELECT id, trigger, status, scope, min_idle_days, include_replied, campaign_ids, max_leads, selected, removed, already_gone, failed, error, created_at, started_at, finished_at FROM instantly_cleanup_runs ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestCleanupRun(ctx context.Context) (InstantlyCleanupRun, error) {
	row := q.db.QueryRow(ctx, getLatestCleanupRun)
	var i InstantlyCleanupRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Status,
		&i.Scope,
		&i.MinIdleDays,
		&i.IncludeReplied,
		&i.CampaignIds,
		&i.MaxLeads,
		&i.Selected,
		&i.Removed,
		&i.AlreadyGone,
		&i.Failed,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listCleanupRuns = `-- name: ListCleanupRuns :many
SELECT id, trigger, status, scope, min_idle_days, include_replied, campaign_ids, max_leads, selected, removed, already_gone, failed, error, created_at, started_at, finished_at FROM instantly_cleanup_runs ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListCleanupRunsParams struct {
	Off int32
	Lim int32
}

func (q *Queries) ListCleanupRuns(ctx context.Context, arg ListCleanupRunsParams) ([]InstantlyCleanupRun, error) {
	rows, err := q.db.Query(ctx, listCleanupRuns, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstantlyCleanupRun{}
	for rows.Next() {
		var i InstantlyCleanupRun
		if err := rows.Scan(
			&i.ID,
			&i.Trigger,
			&i.Status,
			&i.Scope,
			&i.MinIdleDays,
			&i.IncludeReplied,
			&i.CampaignIds,
			&i.MaxLeads,
			&i.Selected,
			&i.Removed,
			&i.AlreadyGone,
			&i.Failed,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startCleanupRun = `-- name: StartCleanupRun :one
UPDATE instantly_cleanup_runs
SET status = 'running', started_at = COALESCE(started_at, $1)
WHERE id = $2 AND status IN ('queued', 'running')
RETURNING id, trigger, status, scope, min_idle_days, include_replied, campaign_ids, max_leads, selected, removed, already_gone, failed, error, created_at, started_at, finished_at
`

type StartCleanupRunParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) StartCleanupRun(ctx context.Context, arg StartCleanupRunParams) (InstantlyCleanupRun, error) {
	row := q.db.QueryRow(ctx, startCleanupRun, arg.At, arg.ID)
	var i InstantlyCleanupRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Status,
		&i.Scope,
		&i.MinIdleDays,
		&i.IncludeReplied,
		&i.CampaignIds,
		&i.MaxLeads,
		&i.Selected,
		&i.Removed,
		&i.AlreadyGone,
		&i.Failed,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
