// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job_queries.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const advanceProviderRunIngest = `-- name: AdvanceProviderRunIngest :exec
UPDATE job_queries
SET ingested_offset = $1,
    listings_found  = $2
WHERE id = $3
`

type AdvanceProviderRunIngestParams struct {
	IngestedOffset int32
	ListingsFound  int32
	ID             uuid.UUID
}

func (q *Queries) AdvanceProviderRunIngest(ctx context.Context, arg AdvanceProviderRunIngestParams) error {
	_, err := q.db.Exec(ctx, advanceProviderRunIngest, arg.IngestedOffset, arg.ListingsFound, arg.ID)
	return err
}

const cancelPendingJobQueries = `-- name: CancelPendingJobQueries :exec
UPDATE job_queries
SET status = 'cancelled', run_state = 'finished', finished_at = now()
WHERE job_id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) CancelPendingJobQueries(ctx context.Context, jobID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelPendingJobQueries, jobID)
	return err
}

const claimProviderRunSlot = `-- name: ClaimProviderRunSlot :execrows
UPDATE job_queries
SET status = 'running', run_state = 'starting', started_at = now()
WHERE id = $1 AND run_state = 'none'
`

func (q *Queries) ClaimProviderRunSlot(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimProviderRunSlot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveProviderRuns = `-- name: CountActiveProviderRuns :one
SELECT count(*)
FROM job_queries jq
         JOIN jobs j ON j.id = jq.job_id
WHERE j.source_id = $1
  AND jq.run_state IN ('starting', 'polling')
  -- A query that reached a terminal state holds no slot even if its run state was
  -- never tidied up, so a lost queue entry cannot occupy the account forever.
  AND jq.status NOT IN ('done', 'failed', 'cancelled')
`

func (q *Queries) CountActiveProviderRuns(ctx context.Context, sourceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProviderRuns, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingJobQueries = `-- name: CountPendingJobQueries :one
SELECT count(*) FROM job_queries
WHERE job_id = $1 AND status NOT IN ('done', 'failed', 'cancelled')
`

func (q *Queries) CountPendingJobQueries(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingJobQueries, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJobQuery = `-- name: CreateJobQuery :one
INSERT INTO job_queries (id, job_id, term, terms, city, state)
VALUES ($1, $2, $3, $4,
        $5, $6)
ON CONFLICT (job_id, term, city, state) DO UPDATE SET terms = EXCLUDED.terms
RETURNING id, job_id, term, city, state, status, listings_found, provider_run_id, error, created_at, started_at, finished_at, terms, dataset_id, run_state, run_status, ingested_offset, resurrected, cost_cents
`

type CreateJobQueryParams struct {
	ID    uuid.UUID
	JobID uuid.UUID
	Term  string
	Terms []string
	City  string
	State string
}

func (q *Queries) CreateJobQuery(ctx context.Context, arg CreateJobQueryParams) (JobQuery, error) {
	row := q.db.QueryRow(ctx, createJobQuery,
		arg.ID,
		arg.JobID,
		arg.Term,
		arg.Terms,
		arg.City,
		arg.State,
	)
	var i JobQuery
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Term,
		&i.City,
		&i.State,
		&i.Status,
		&i.ListingsFound,
		&i.ProviderRunID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Terms,
		&i.DatasetID,
		&i.RunState,
		&i.RunStatus,
		&i.IngestedOffset,
		&i.Resurrected,
		&i.CostCents,
	)
	return i, err
}

const getJobQuery = `-- name: GetJobQuery :one
SELECT id, job_id, term, city, state, status, listings_found, provider_run_id, error, created_at, started_at, finished_at, terms, dataset_id, run_state, run_status, ingested_offset, resurrected, cost_cents FROM job_queries WHERE id = $1
`

func (q *Queries) GetJobQuery(ctx context.Context, id uuid.UUID) (JobQuery, error) {
	row := q.db.QueryRow(ctx, getJobQuery, id)
	var i JobQuery
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Term,
		&i.City,
		&i.State,
		&i.Status,
		&i.ListingsFound,
		&i.ProviderRunID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Terms,
		&i.DatasetID,
		&i.RunState,
		&i.RunStatus,
		&i.IngestedOffset,
		&i.Resurrected,
		&i.CostCents,
	)
	return i, err
}

const listJobQueries = `-- name: ListJobQueries :many
SELECT id, job_id, term, city, state, status, listings_found, provider_run_id, error, created_at, started_at, finished_at, terms, dataset_id, run_state, run_status, ingested_offset, resurrected, cost_cents FROM job_queries WHERE job_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListJobQueries(ctx context.Context, jobID uuid.UUID) ([]JobQuery, error) {
	rows, err := q.db.Query(ctx, listJobQueries, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobQuery{}
	for rows.Next() {
		var i JobQuery
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Term,
			&i.City,
			&i.State,
			&i.Status,
			&i.ListingsFound,
			&i.ProviderRunID,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Terms,
			&i.DatasetID,
			&i.RunState,
			&i.RunStatus,
			&i.IngestedOffset,
			&i.Resurrected,
			&i.CostCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderRunIDsForSource = `-- name: ListProviderRunIDsForSource :many
SELECT DISTINCT jq.provider_run_id
FROM job_queries jq
         JOIN jobs j ON j.id = jq.job_id
WHERE j.source_id = $1
  AND jq.provider_run_id IS NOT NULL
`

func (q *Queries) ListProviderRunIDsForSource(ctx context.Context, sourceID uuid.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listProviderRunIDsForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var provider_run_id *string
		if err := rows.Scan(&provider_run_id); err != nil {
			return nil, err
		}
		items = append(items, provider_run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProviderRunSlots = `-- name: LockProviderRunSlots :exec

SELECT pg_advisory_xact_lock($1::bigint)
`

// Asynchronous provider runs.
//
// The claim below is what stops a retry from paying for a second run: a row leaves
// 'none' exactly once, and only a row in 'none' may start one.
func (q *Queries) LockProviderRunSlots(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockProviderRunSlots, key)
	return err
}

const markJobQueryDone = `-- name: MarkJobQueryDone :exec
UPDATE job_queries
SET status         = 'done',
    run_state      = 'finished',
    listings_found = $1,
    provider_run_id = COALESCE($2, provider_run_id),
    cost_cents     = $3,
    finished_at    = now()
WHERE id = $4
`

type MarkJobQueryDoneParams struct {
	ListingsFound int32
	ProviderRunID *string
	CostCents     int64
	ID            uuid.UUID
}

func (q *Queries) MarkJobQueryDone(ctx context.Context, arg MarkJobQueryDoneParams) error {
	_, err := q.db.Exec(ctx, markJobQueryDone,
		arg.ListingsFound,
		arg.ProviderRunID,
		arg.CostCents,
		arg.ID,
	)
	return err
}

const markJobQueryFailed = `-- name: MarkJobQueryFailed :exec
UPDATE job_queries
SET status = $1, run_state = 'finished', error = $2,
    finished_at = now()
WHERE id = $3
`

type MarkJobQueryFailedParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) MarkJobQueryFailed(ctx context.Context, arg MarkJobQueryFailedParams) error {
	_, err := q.db.Exec(ctx, markJobQueryFailed, arg.Status, arg.Error, arg.ID)
	return err
}

const markJobQueryRunning = `-- name: MarkJobQueryRunning :exec
UPDATE job_queries
SET status = 'running', started_at = now()
WHERE id = $1
`

func (q *Queries) MarkJobQueryRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markJobQueryRunning, id)
	return err
}

const markProviderRunResurrected = `-- name: MarkProviderRunResurrected :exec
UPDATE job_queries
SET resurrected = true, run_state = 'polling'
WHERE id = $1
`

func (q *Queries) MarkProviderRunResurrected(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markProviderRunResurrected, id)
	return err
}

const releaseProviderRunSlot = `-- name: ReleaseProviderRunSlot :exec
UPDATE job_queries
SET run_state = 'none'
WHERE id = $1 AND run_state = 'starting' AND provider_run_id IS NULL
`

func (q *Queries) ReleaseProviderRunSlot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseProviderRunSlot, id)
	return err
}

const saveProviderRun = `-- name: SaveProviderRun :exec
UPDATE job_queries
SET provider_run_id = $1,
    dataset_id      = $2,
    run_status      = $3,
    run_state       = 'polling'
WHERE id = $4
`

type SaveProviderRunParams struct {
	ProviderRunID *string
	DatasetID     *string
	RunStatus     *string
	ID            uuid.UUID
}

func (q *Queries) SaveProviderRun(ctx context.Context, arg SaveProviderRunParams) error {
	_, err := q.db.Exec(ctx, saveProviderRun,
		arg.ProviderRunID,
		arg.DatasetID,
		arg.RunStatus,
		arg.ID,
	)
	return err
}

const setProviderRunStatus = `-- name: SetProviderRunStatus :exec
UPDATE job_queries
SET run_status = $1,
    run_state  = $2
WHERE id = $3
`

type SetProviderRunStatusParams struct {
	RunStatus *string
	RunState  string
	ID        uuid.UUID
}

func (q *Queries) SetProviderRunStatus(ctx context.Context, arg SetProviderRunStatusParams) error {
	_, err := q.db.Exec(ctx, setProviderRunStatus, arg.RunStatus, arg.RunState, arg.ID)
	return err
}
