// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job_events.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const insertJobEvent = `-- name: InsertJobEvent :one
INSERT INTO job_events (job_id, type, data)
VALUES ($1, $2, $3)
RETURNING id, ts
`

type InsertJobEventParams struct {
	JobID uuid.UUID
	Type  string
	Data  []byte
}

type InsertJobEventRow struct {
	ID int64
	Ts time.Time
}

func (q *Queries) InsertJobEvent(ctx context.Context, arg InsertJobEventParams) (InsertJobEventRow, error) {
	row := q.db.QueryRow(ctx, insertJobEvent, arg.JobID, arg.Type, arg.Data)
	var i InsertJobEventRow
	err := row.Scan(&i.ID, &i.Ts)
	return i, err
}

const listJobEventsAfter = `-- name: ListJobEventsAfter :many
SELECT id, job_id, ts, type, data
FROM job_events
WHERE job_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListJobEventsAfterParams struct {
	JobID   uuid.UUID
	AfterID int64
	Lim     int32
}

func (q *Queries) ListJobEventsAfter(ctx context.Context, arg ListJobEventsAfterParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEventsAfter, arg.JobID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Ts,
			&i.Type,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentJobEvents = `-- name: ListRecentJobEvents :many
SELECT id, job_id, ts, type, data
FROM job_events
WHERE job_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListRecentJobEventsParams struct {
	JobID uuid.UUID
	Lim   int32
}

func (q *Queries) ListRecentJobEvents(ctx context.Context, arg ListRecentJobEventsParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listRecentJobEvents, arg.JobID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Ts,
			&i.Type,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneJobEvents = `-- name: PruneJobEvents :execrows
DELETE FROM job_events WHERE ts < now() - make_interval(days => $1::int)
`

func (q *Queries) PruneJobEvents(ctx context.Context, maxAgeDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, pruneJobEvents, maxAgeDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
