// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const bumpJobStats = `-- name: BumpJobStats :exec
UPDATE jobs
SET stats = jsonb_set(stats, ARRAY[$1::text],
                      to_jsonb(COALESCE((stats ->> $1::text)::bigint, 0)
                                   + $2::bigint))
WHERE id = $3
`

type BumpJobStatsParams struct {
	Key   string
	Delta int64
	ID    uuid.UUID
}

func (q *Queries) BumpJobStats(ctx context.Context, arg BumpJobStatsParams) error {
	_, err := q.db.Exec(ctx, bumpJobStats, arg.Key, arg.Delta, arg.ID)
	return err
}

const cancelJob = `-- name: CancelJob :one
UPDATE jobs
SET status      = 'cancelled',
    finished_at = now()
WHERE id = $1
  AND status IN ('queued', 'running')
RETURNING id, name, status, source_id, config, stats, error, created_at, started_at, finished_at
`

func (q *Queries) CancelJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, cancelJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.SourceID,
		&i.Config,
		&i.Stats,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, name, source_id, config, stats, status)
VALUES ($1, $2, $3, $4,
        $5, 'queued')
RETURNING id, name, status, source_id, config, stats, error, created_at, started_at, finished_at
`

type CreateJobParams struct {
	ID       uuid.UUID
	Name     string
	SourceID uuid.UUID
	Config   []byte
	Stats    []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Name,
		arg.SourceID,
		arg.Config,
		arg.Stats,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.SourceID,
		&i.Config,
		&i.Stats,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :execrows
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT j.id, j.name, j.status, j.source_id, j.config, j.stats, j.error, j.created_at, j.started_at, j.finished_at, s.name AS source_name, s.kind AS source_kind
FROM jobs j
         JOIN sources s ON s.id = j.source_id
WHERE j.id = $1
`

type GetJobRow struct {
	ID         uuid.UUID
	Name       string
	Status     string
	SourceID   uuid.UUID
	Config     []byte
	Stats      []byte
	Error      *string
	CreatedAt  time.Time
	StartedAt  *time.Time
	FinishedAt *time.Time
	SourceName string
	SourceKind string
}

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (GetJobRow, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.SourceID,
		&i.Config,
		&i.Stats,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SourceName,
		&i.SourceKind,
	)
	return i, err
}

const getJobStats = `-- name: GetJobStats :one
SELECT stats FROM jobs WHERE id = $1
`

func (q *Queries) GetJobStats(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getJobStats, id)
	var stats []byte
	err := row.Scan(&stats)
	return stats, err
}

const getJobStatus = `-- name: GetJobStatus :one
SELECT status FROM jobs WHERE id = $1
`

func (q *Queries) GetJobStatus(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getJobStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const markJobRunning = `-- name: MarkJobRunning :exec
UPDATE jobs
SET status     = 'running',
    started_at = COALESCE(started_at, now())
WHERE id = $1
  AND status = 'queued'
`

func (q *Queries) MarkJobRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markJobRunning, id)
	return err
}

const markJobTerminal = `-- name: MarkJobTerminal :exec
UPDATE jobs
SET status      = $1,
    error       = $2,
    finished_at = now()
WHERE id = $3
  AND status IN ('queued', 'running')
`

type MarkJobTerminalParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) MarkJobTerminal(ctx context.Context, arg MarkJobTerminalParams) error {
	_, err := q.db.Exec(ctx, markJobTerminal, arg.Status, arg.Error, arg.ID)
	return err
}

const recomputeJobStats = `-- name: RecomputeJobStats :one
WITH q AS (SELECT count(*)                                             AS total,
                  count(*) FILTER (WHERE jq.status IN ('done', 'failed', 'cancelled')) AS done,
                  count(*) FILTER (WHERE jq.status = 'failed')         AS failed,
                  COALESCE(sum(jq.listings_found), 0)                  AS listings
           FROM job_queries jq
           WHERE jq.job_id = $1),
     b AS (SELECT count(*)                                                       AS sites_total,
                  count(*) FILTER (WHERE bu.last_crawled_at IS NOT NULL)         AS sites_crawled
           FROM job_results jr
                    JOIN businesses bu ON bu.id = jr.business_id
           WHERE jr.job_id = $1
             AND bu.website IS NOT NULL
             AND bu.website <> ''),
     e AS (SELECT count(*) AS emails
           FROM job_results jr
                    JOIN business_emails be ON be.business_id = jr.business_id
           WHERE jr.job_id = $1)
SELECT q.total::bigint         AS queries_total,
       q.done::bigint          AS queries_done,
       q.failed::bigint        AS queries_failed,
       q.listings::bigint      AS listings_found,
       b.sites_total::bigint   AS sites_total,
       b.sites_crawled::bigint AS sites_crawled,
       e.emails::bigint        AS emails_found
FROM q, b, e
`

type RecomputeJobStatsRow struct {
	QueriesTotal  int64
	QueriesDone   int64
	QueriesFailed int64
	ListingsFound int64
	SitesTotal    int64
	SitesCrawled  int64
	EmailsFound   int64
}

func (q *Queries) RecomputeJobStats(ctx context.Context, jid uuid.UUID) (RecomputeJobStatsRow, error) {
	row := q.db.QueryRow(ctx, recomputeJobStats, jid)
	var i RecomputeJobStatsRow
	err := row.Scan(
		&i.QueriesTotal,
		&i.QueriesDone,
		&i.QueriesFailed,
		&i.ListingsFound,
		&i.SitesTotal,
		&i.SitesCrawled,
		&i.EmailsFound,
	)
	return i, err
}

const setJobStats = `-- name: SetJobStats :exec
UPDATE jobs SET stats = $1 WHERE id = $2
`

type SetJobStatsParams struct {
	Stats []byte
	ID    uuid.UUID
}

func (q *Queries) SetJobStats(ctx context.Context, arg SetJobStatsParams) error {
	_, err := q.db.Exec(ctx, setJobStats, arg.Stats, arg.ID)
	return err
}
