// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: newsletter.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const claimNewsletterSubscription = `-- name: ClaimNewsletterSubscription :one
UPDATE newsletter_subscriptions
SET sync_status = 'syncing', claimed_at = now(), sync_attempts = sync_attempts + 1, updated_at = now()
WHERE id = $1 AND sync_status IN ('queued', 'failed')
RETURNING id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at
`

// Compare-and-set: only a queued or failed subscription can be picked up.
func (q *Queries) ClaimNewsletterSubscription(ctx context.Context, id uuid.UUID) (NewsletterSubscription, error) {
	row := q.db.QueryRow(ctx, claimNewsletterSubscription, id)
	var i NewsletterSubscription
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AudienceID,
		&i.ConsentID,
		&i.RequestedStatus,
		&i.Status,
		&i.SyncStatus,
		&i.SubscriberHash,
		&i.UniqueEmailID,
		&i.MailchimpContactID,
		&i.WebID,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.SyncAttempts,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.UnsubscribeReason,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearDefaultNewsletterAudience = `-- name: ClearDefaultNewsletterAudience :exec
UPDATE newsletter_audiences SET is_default = false, updated_at = now() WHERE is_default
`

func (q *Queries) ClearDefaultNewsletterAudience(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultNewsletterAudience)
	return err
}

const countNewsletterEligibleContacts = `-- name: CountNewsletterEligibleContacts :one
SELECT count(*) FROM contacts c
WHERE c.lifecycle_stage IN ('permission_requested', 'permission_captured', 'newsletter_eligible')
  AND ($1::uuid IS NULL
       OR c.id IN (SELECT contact_id FROM campaign_leads WHERE campaign_id = $1::uuid))
`

func (q *Queries) CountNewsletterEligibleContacts(ctx context.Context, campaignID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNewsletterEligibleContacts, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewsletterSubscriptions = `-- name: CountNewsletterSubscriptions :one
SELECT count(*) FROM newsletter_subscriptions s
JOIN contacts c ON c.id = s.contact_id
WHERE (cardinality($1::text[]) = 0 OR s.status = ANY($1::text[]))
  AND (cardinality($2::text[]) = 0 OR s.sync_status = ANY($2::text[]))
  AND ($3::uuid IS NULL OR s.audience_id = $3::uuid)
  AND ($4::text IS NULL OR c.email::text ILIKE '%' || $4::text || '%')
`

type CountNewsletterSubscriptionsParams struct {
	Statuses     []string
	SyncStatuses []string
	AudienceID   uuid.NullUUID
	Q            *string
}

func (q *Queries) CountNewsletterSubscriptions(ctx context.Context, arg CountNewsletterSubscriptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewsletterSubscriptions,
		arg.Statuses,
		arg.SyncStatuses,
		arg.AudienceID,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewsletterSubscriptionsByStatus = `-- name: CountNewsletterSubscriptionsByStatus :many
SELECT status, count(*)::bigint AS total FROM newsletter_subscriptions GROUP BY status
`

type CountNewsletterSubscriptionsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountNewsletterSubscriptionsByStatus(ctx context.Context) ([]CountNewsletterSubscriptionsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countNewsletterSubscriptionsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNewsletterSubscriptionsByStatusRow{}
	for rows.Next() {
		var i CountNewsletterSubscriptionsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNewsletterSubscription = `-- name: CreateNewsletterSubscription :one
INSERT INTO newsletter_subscriptions (id, contact_id, audience_id, consent_id, requested_status, subscriber_hash, tags)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
ON CONFLICT (contact_id, audience_id) DO NOTHING
RETURNING id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at
`

type CreateNewsletterSubscriptionParams struct {
	ID              uuid.UUID
	ContactID       uuid.UUID
	AudienceID      uuid.UUID
	ConsentID       uuid.NullUUID
	RequestedStatus string
	SubscriberHash  *string
	Tags            []string
}

func (q *Queries) CreateNewsletterSubscription(ctx context.Context, arg CreateNewsletterSubscriptionParams) (NewsletterSubscription, error) {
	row := q.db.QueryRow(ctx, createNewsletterSubscription,
		arg.ID,
		arg.ContactID,
		arg.AudienceID,
		arg.ConsentID,
		arg.RequestedStatus,
		arg.SubscriberHash,
		arg.Tags,
	)
	var i NewsletterSubscription
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AudienceID,
		&i.ConsentID,
		&i.RequestedStatus,
		&i.Status,
		&i.SyncStatus,
		&i.SubscriberHash,
		&i.UniqueEmailID,
		&i.MailchimpContactID,
		&i.WebID,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.SyncAttempts,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.UnsubscribeReason,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failNewsletterSubscription = `-- name: FailNewsletterSubscription :exec
UPDATE newsletter_subscriptions
SET sync_status = 'failed', claimed_at = NULL, last_error = $1, updated_at = now()
WHERE id = $2
`

type FailNewsletterSubscriptionParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) FailNewsletterSubscription(ctx context.Context, arg FailNewsletterSubscriptionParams) error {
	_, err := q.db.Exec(ctx, failNewsletterSubscription, arg.Error, arg.ID)
	return err
}

const getDefaultNewsletterAudience = `-- name: GetDefaultNewsletterAudience :one
SELECT id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at FROM newsletter_audiences WHERE is_default LIMIT 1
`

func (q *Queries) GetDefaultNewsletterAudience(ctx context.Context) (NewsletterAudience, error) {
	row := q.db.QueryRow(ctx, getDefaultNewsletterAudience)
	var i NewsletterAudience
	err := row.Scan(
		&i.ID,
		&i.MailchimpListID,
		&i.Name,
		&i.DoubleOptin,
		&i.AllowSingleOptIn,
		&i.DefaultTags,
		&i.WebhookToken,
		&i.WebhookID,
		&i.WebhookSecretEnc,
		&i.WebhookUrl,
		&i.MemberCount,
		&i.Stats,
		&i.IsDefault,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterAudience = `-- name: GetNewsletterAudience :one
SELECT id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at FROM newsletter_audiences WHERE id = $1
`

func (q *Queries) GetNewsletterAudience(ctx context.Context, id uuid.UUID) (NewsletterAudience, error) {
	row := q.db.QueryRow(ctx, getNewsletterAudience, id)
	var i NewsletterAudience
	err := row.Scan(
		&i.ID,
		&i.MailchimpListID,
		&i.Name,
		&i.DoubleOptin,
		&i.AllowSingleOptIn,
		&i.DefaultTags,
		&i.WebhookToken,
		&i.WebhookID,
		&i.WebhookSecretEnc,
		&i.WebhookUrl,
		&i.MemberCount,
		&i.Stats,
		&i.IsDefault,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterAudienceByListID = `-- name: GetNewsletterAudienceByListID :one
SELECT id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at FROM newsletter_audiences WHERE mailchimp_list_id = $1
`

func (q *Queries) GetNewsletterAudienceByListID(ctx context.Context, mailchimpListID string) (NewsletterAudience, error) {
	row := q.db.QueryRow(ctx, getNewsletterAudienceByListID, mailchimpListID)
	var i NewsletterAudience
	err := row.Scan(
		&i.ID,
		&i.MailchimpListID,
		&i.Name,
		&i.DoubleOptin,
		&i.AllowSingleOptIn,
		&i.DefaultTags,
		&i.WebhookToken,
		&i.WebhookID,
		&i.WebhookSecretEnc,
		&i.WebhookUrl,
		&i.MemberCount,
		&i.Stats,
		&i.IsDefault,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterAudienceByToken = `-- name: GetNewsletterAudienceByToken :one
SELECT id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at FROM newsletter_audiences WHERE webhook_token = $1
`

func (q *Queries) GetNewsletterAudienceByToken(ctx context.Context, webhookToken *string) (NewsletterAudience, error) {
	row := q.db.QueryRow(ctx, getNewsletterAudienceByToken, webhookToken)
	var i NewsletterAudience
	err := row.Scan(
		&i.ID,
		&i.MailchimpListID,
		&i.Name,
		&i.DoubleOptin,
		&i.AllowSingleOptIn,
		&i.DefaultTags,
		&i.WebhookToken,
		&i.WebhookID,
		&i.WebhookSecretEnc,
		&i.WebhookUrl,
		&i.MemberCount,
		&i.Stats,
		&i.IsDefault,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterSubscription = `-- name: GetNewsletterSubscription :one
SELECT id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at FROM newsletter_subscriptions WHERE id = $1
`

func (q *Queries) GetNewsletterSubscription(ctx context.Context, id uuid.UUID) (NewsletterSubscription, error) {
	row := q.db.QueryRow(ctx, getNewsletterSubscription, id)
	var i NewsletterSubscription
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AudienceID,
		&i.ConsentID,
		&i.RequestedStatus,
		&i.Status,
		&i.SyncStatus,
		&i.SubscriberHash,
		&i.UniqueEmailID,
		&i.MailchimpContactID,
		&i.WebID,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.SyncAttempts,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.UnsubscribeReason,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterSubscriptionByContact = `-- name: GetNewsletterSubscriptionByContact :one
SELECT id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at FROM newsletter_subscriptions WHERE contact_id = $1 AND audience_id = $2
`

type GetNewsletterSubscriptionByContactParams struct {
	ContactID  uuid.UUID
	AudienceID uuid.UUID
}

func (q *Queries) GetNewsletterSubscriptionByContact(ctx context.Context, arg GetNewsletterSubscriptionByContactParams) (NewsletterSubscription, error) {
	row := q.db.QueryRow(ctx, getNewsletterSubscriptionByContact, arg.ContactID, arg.AudienceID)
	var i NewsletterSubscription
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AudienceID,
		&i.ConsentID,
		&i.RequestedStatus,
		&i.Status,
		&i.SyncStatus,
		&i.SubscriberHash,
		&i.UniqueEmailID,
		&i.MailchimpContactID,
		&i.WebID,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.SyncAttempts,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.UnsubscribeReason,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterSubscriptionByHash = `-- name: GetNewsletterSubscriptionByHash :one
SELECT id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at FROM newsletter_subscriptions WHERE audience_id = $1 AND subscriber_hash = $2
`

type GetNewsletterSubscriptionByHashParams struct {
	AudienceID     uuid.UUID
	SubscriberHash *string
}

func (q *Queries) GetNewsletterSubscriptionByHash(ctx context.Context, arg GetNewsletterSubscriptionByHashParams) (NewsletterSubscription, error) {
	row := q.db.QueryRow(ctx, getNewsletterSubscriptionByHash, arg.AudienceID, arg.SubscriberHash)
	var i NewsletterSubscription
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AudienceID,
		&i.ConsentID,
		&i.RequestedStatus,
		&i.Status,
		&i.SyncStatus,
		&i.SubscriberHash,
		&i.UniqueEmailID,
		&i.MailchimpContactID,
		&i.WebID,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.SyncAttempts,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.UnsubscribeReason,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNewsletterAudiences = `-- name: ListNewsletterAudiences :many
SELECT id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at FROM newsletter_audiences ORDER BY is_default DESC, name
`

func (q *Queries) ListNewsletterAudiences(ctx context.Context) ([]NewsletterAudience, error) {
	rows, err := q.db.Query(ctx, listNewsletterAudiences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsletterAudience{}
	for rows.Next() {
		var i NewsletterAudience
		if err := rows.Scan(
			&i.ID,
			&i.MailchimpListID,
			&i.Name,
			&i.DoubleOptin,
			&i.AllowSingleOptIn,
			&i.DefaultTags,
			&i.WebhookToken,
			&i.WebhookID,
			&i.WebhookSecretEnc,
			&i.WebhookUrl,
			&i.MemberCount,
			&i.Stats,
			&i.IsDefault,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterEligibleContacts = `-- name: ListNewsletterEligibleContacts :many
SELECT c.id, c.email, c.domain, c.first_name, c.last_name, c.company, c.title, c.phone, c.website, c.business_id, c.source, c.lifecycle_stage, c.stage_changed_at, c.suppressed_at, c.suppression_reason, c.attributes, c.last_event_at, c.created_at, c.updated_at, c.domain_suffixes, c.website_suffixes, c.company_key, c.company_prefixes, cc.id AS consent_id, cc.source AS consent_source, cc.captured_at AS consent_captured_at
FROM contacts c
LEFT JOIN contact_consents cc ON cc.contact_id = c.id AND cc.revoked_at IS NULL
WHERE c.lifecycle_stage IN ('permission_requested', 'permission_captured', 'newsletter_eligible')
  AND ($1::uuid IS NULL
       OR c.id IN (SELECT contact_id FROM campaign_leads WHERE campaign_id = $1::uuid))
ORDER BY c.stage_changed_at DESC
LIMIT $3 OFFSET $2
`

type ListNewsletterEligibleContactsParams struct {
	CampaignID uuid.NullUUID
	Off        int32
	Lim        int32
}

type ListNewsletterEligibleContactsRow struct {
	ID                uuid.UUID
	Email             string
	Domain            string
	FirstName         *string
	LastName          *string
	Company           *string
	Title             *string
	Phone             *string
	Website           *string
	BusinessID        uuid.NullUUID
	Source            string
	LifecycleStage    string
	StageChangedAt    time.Time
	SuppressedAt      *time.Time
	SuppressionReason *string
	Attributes        []byte
	LastEventAt       *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DomainSuffixes    []string
	WebsiteSuffixes   []string
	CompanyKey        *string
	CompanyPrefixes   []string
	ConsentID         uuid.NullUUID
	ConsentSource     *string
	ConsentCapturedAt *time.Time
}

// Contacts who could be pushed now, and those one step short with the reason why.
func (q *Queries) ListNewsletterEligibleContacts(ctx context.Context, arg ListNewsletterEligibleContactsParams) ([]ListNewsletterEligibleContactsRow, error) {
	rows, err := q.db.Query(ctx, listNewsletterEligibleContacts, arg.CampaignID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewsletterEligibleContactsRow{}
	for rows.Next() {
		var i ListNewsletterEligibleContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Domain,
			&i.FirstName,
			&i.LastName,
			&i.Company,
			&i.Title,
			&i.Phone,
			&i.Website,
			&i.BusinessID,
			&i.Source,
			&i.LifecycleStage,
			&i.StageChangedAt,
			&i.SuppressedAt,
			&i.SuppressionReason,
			&i.Attributes,
			&i.LastEventAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainSuffixes,
			&i.WebsiteSuffixes,
			&i.CompanyKey,
			&i.CompanyPrefixes,
			&i.ConsentID,
			&i.ConsentSource,
			&i.ConsentCapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterSubscriptions = `-- name: ListNewsletterSubscriptions :many
SELECT s.id, s.contact_id, s.audience_id, s.consent_id, s.requested_status, s.status, s.sync_status, s.subscriber_hash, s.unique_email_id, s.mailchimp_contact_id, s.web_id, s.claimed_at, s.pushed_at, s.last_synced_at, s.last_error, s.sync_attempts, s.subscribed_at, s.unsubscribed_at, s.unsubscribe_reason, s.tags, s.created_at, s.updated_at, c.email::text AS email, c.lifecycle_stage, a.name AS audience_name
FROM newsletter_subscriptions s
JOIN contacts c ON c.id = s.contact_id
JOIN newsletter_audiences a ON a.id = s.audience_id
WHERE (cardinality($1::text[]) = 0 OR s.status = ANY($1::text[]))
  AND (cardinality($2::text[]) = 0 OR s.sync_status = ANY($2::text[]))
  AND ($3::uuid IS NULL OR s.audience_id = $3::uuid)
  AND ($4::text IS NULL OR c.email::text ILIKE '%' || $4::text || '%')
ORDER BY s.updated_at DESC, s.id DESC
LIMIT $6 OFFSET $5
`

type ListNewsletterSubscriptionsParams struct {
	Statuses     []string
	SyncStatuses []string
	AudienceID   uuid.NullUUID
	Q            *string
	Off          int32
	Lim          int32
}

type ListNewsletterSubscriptionsRow struct {
	ID                 uuid.UUID
	ContactID          uuid.UUID
	AudienceID         uuid.UUID
	ConsentID          uuid.NullUUID
	RequestedStatus    string
	Status             string
	SyncStatus         string
	SubscriberHash     *string
	UniqueEmailID      *string
	MailchimpContactID *string
	WebID              *int64
	ClaimedAt          *time.Time
	PushedAt           *time.Time
	LastSyncedAt       *time.Time
	LastError          *string
	SyncAttempts       int32
	SubscribedAt       *time.Time
	UnsubscribedAt     *time.Time
	UnsubscribeReason  *string
	Tags               []string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Email              string
	LifecycleStage     string
	AudienceName       string
}

func (q *Queries) ListNewsletterSubscriptions(ctx context.Context, arg ListNewsletterSubscriptionsParams) ([]ListNewsletterSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listNewsletterSubscriptions,
		arg.Statuses,
		arg.SyncStatuses,
		arg.AudienceID,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewsletterSubscriptionsRow{}
	for rows.Next() {
		var i ListNewsletterSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.AudienceID,
			&i.ConsentID,
			&i.RequestedStatus,
			&i.Status,
			&i.SyncStatus,
			&i.SubscriberHash,
			&i.UniqueEmailID,
			&i.MailchimpContactID,
			&i.WebID,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.LastSyncedAt,
			&i.LastError,
			&i.SyncAttempts,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.UnsubscribeReason,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.LifecycleStage,
			&i.AudienceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterSubscriptionsForContact = `-- name: ListNewsletterSubscriptionsForContact :many
SELECT id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at FROM newsletter_subscriptions WHERE contact_id = $1 ORDER BY created_at
`

func (q *Queries) ListNewsletterSubscriptionsForContact(ctx context.Context, contactID uuid.UUID) ([]NewsletterSubscription, error) {
	rows, err := q.db.Query(ctx, listNewsletterSubscriptionsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsletterSubscription{}
	for rows.Next() {
		var i NewsletterSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.AudienceID,
			&i.ConsentID,
			&i.RequestedStatus,
			&i.Status,
			&i.SyncStatus,
			&i.SubscriberHash,
			&i.UniqueEmailID,
			&i.MailchimpContactID,
			&i.WebID,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.LastSyncedAt,
			&i.LastError,
			&i.SyncAttempts,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.UnsubscribeReason,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsletterSubscriptionsToReconcile = `-- name: ListNewsletterSubscriptionsToReconcile :many
SELECT id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at FROM newsletter_subscriptions
WHERE sync_status = 'synced' AND status IN ('pending', 'subscribed')
  AND (last_synced_at IS NULL OR last_synced_at < $1)
ORDER BY last_synced_at NULLS FIRST
LIMIT $2
`

type ListNewsletterSubscriptionsToReconcileParams struct {
	Before *time.Time
	Lim    int32
}

func (q *Queries) ListNewsletterSubscriptionsToReconcile(ctx context.Context, arg ListNewsletterSubscriptionsToReconcileParams) ([]NewsletterSubscription, error) {
	rows, err := q.db.Query(ctx, listNewsletterSubscriptionsToReconcile, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsletterSubscription{}
	for rows.Next() {
		var i NewsletterSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.AudienceID,
			&i.ConsentID,
			&i.RequestedStatus,
			&i.Status,
			&i.SyncStatus,
			&i.SubscriberHash,
			&i.UniqueEmailID,
			&i.MailchimpContactID,
			&i.WebID,
			&i.ClaimedAt,
			&i.PushedAt,
			&i.LastSyncedAt,
			&i.LastError,
			&i.SyncAttempts,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.UnsubscribeReason,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNewsletterSubscriptionSynced = `-- name: MarkNewsletterSubscriptionSynced :one
UPDATE newsletter_subscriptions
SET sync_status = 'synced', claimed_at = NULL, last_error = NULL, pushed_at = COALESCE(pushed_at, now()),
    last_synced_at = now(), status = $1, requested_status = $2,
    subscriber_hash = COALESCE($3, subscriber_hash),
    unique_email_id = COALESCE($4, unique_email_id),
    mailchimp_contact_id = COALESCE($5, mailchimp_contact_id),
    web_id = COALESCE($6, web_id),
    subscribed_at = CASE WHEN $1 = 'subscribed' THEN COALESCE(subscribed_at, now()) ELSE subscribed_at END,
    unsubscribed_at = CASE WHEN $1 IN ('unsubscribed', 'cleaned') THEN COALESCE(unsubscribed_at, now()) ELSE unsubscribed_at END,
    updated_at = now()
WHERE id = $7
RETURNING id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at
`

type MarkNewsletterSubscriptionSyncedParams struct {
	Status             string
	RequestedStatus    string
	SubscriberHash     *string
	UniqueEmailID      *string
	MailchimpContactID *string
	WebID              *int64
	ID                 uuid.UUID
}

func (q *Queries) MarkNewsletterSubscriptionSynced(ctx context.Context, arg MarkNewsletterSubscriptionSyncedParams) (NewsletterSubscription, error) {
	row := q.db.QueryRow(ctx, markNewsletterSubscriptionSynced,
		arg.Status,
		arg.RequestedStatus,
		arg.SubscriberHash,
		arg.UniqueEmailID,
		arg.MailchimpContactID,
		arg.WebID,
		arg.ID,
	)
	var i NewsletterSubscription
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AudienceID,
		&i.ConsentID,
		&i.RequestedStatus,
		&i.Status,
		&i.SyncStatus,
		&i.SubscriberHash,
		&i.UniqueEmailID,
		&i.MailchimpContactID,
		&i.WebID,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.SyncAttempts,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.UnsubscribeReason,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mirrorNewsletterSubscriptionStatus = `-- name: MirrorNewsletterSubscriptionStatus :one
UPDATE newsletter_subscriptions
SET status = $1,
    unsubscribe_reason = COALESCE($2, unsubscribe_reason),
    unique_email_id = COALESCE($3, unique_email_id),
    mailchimp_contact_id = COALESCE($4, mailchimp_contact_id),
    web_id = COALESCE($5, web_id),
    subscribed_at = CASE WHEN $1 = 'subscribed' THEN COALESCE(subscribed_at, $6) ELSE subscribed_at END,
    unsubscribed_at = CASE WHEN $1 IN ('unsubscribed', 'cleaned') THEN COALESCE(unsubscribed_at, $6) ELSE unsubscribed_at END,
    last_synced_at = now(), updated_at = now()
WHERE id = $7
RETURNING id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at
`

type MirrorNewsletterSubscriptionStatusParams struct {
	Status             string
	UnsubscribeReason  *string
	UniqueEmailID      *string
	MailchimpContactID *string
	WebID              *int64
	At                 *time.Time
	ID                 uuid.UUID
}

// A webhook or a reconcile telling us what Mailchimp now says.
func (q *Queries) MirrorNewsletterSubscriptionStatus(ctx context.Context, arg MirrorNewsletterSubscriptionStatusParams) (NewsletterSubscription, error) {
	row := q.db.QueryRow(ctx, mirrorNewsletterSubscriptionStatus,
		arg.Status,
		arg.UnsubscribeReason,
		arg.UniqueEmailID,
		arg.MailchimpContactID,
		arg.WebID,
		arg.At,
		arg.ID,
	)
	var i NewsletterSubscription
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AudienceID,
		&i.ConsentID,
		&i.RequestedStatus,
		&i.Status,
		&i.SyncStatus,
		&i.SubscriberHash,
		&i.UniqueEmailID,
		&i.MailchimpContactID,
		&i.WebID,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.SyncAttempts,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.UnsubscribeReason,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueNewsletterSubscription = `-- name: RequeueNewsletterSubscription :one
UPDATE newsletter_subscriptions
SET sync_status = 'queued', claimed_at = NULL, last_error = $1,
    requested_status = COALESCE($2, requested_status), updated_at = now()
WHERE id = $3
RETURNING id, contact_id, audience_id, consent_id, requested_status, status, sync_status, subscriber_hash, unique_email_id, mailchimp_contact_id, web_id, claimed_at, pushed_at, last_synced_at, last_error, sync_attempts, subscribed_at, unsubscribed_at, unsubscribe_reason, tags, created_at, updated_at
`

type RequeueNewsletterSubscriptionParams struct {
	Error           *string
	RequestedStatus *string
	ID              uuid.UUID
}

func (q *Queries) RequeueNewsletterSubscription(ctx context.Context, arg RequeueNewsletterSubscriptionParams) (NewsletterSubscription, error) {
	row := q.db.QueryRow(ctx, requeueNewsletterSubscription, arg.Error, arg.RequestedStatus, arg.ID)
	var i NewsletterSubscription
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AudienceID,
		&i.ConsentID,
		&i.RequestedStatus,
		&i.Status,
		&i.SyncStatus,
		&i.SubscriberHash,
		&i.UniqueEmailID,
		&i.MailchimpContactID,
		&i.WebID,
		&i.ClaimedAt,
		&i.PushedAt,
		&i.LastSyncedAt,
		&i.LastError,
		&i.SyncAttempts,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.UnsubscribeReason,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDefaultNewsletterAudience = `-- name: SetDefaultNewsletterAudience :one
UPDATE newsletter_audiences SET is_default = true, updated_at = now() WHERE id = $1 RETURNING id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at
`

func (q *Queries) SetDefaultNewsletterAudience(ctx context.Context, id uuid.UUID) (NewsletterAudience, error) {
	row := q.db.QueryRow(ctx, setDefaultNewsletterAudience, id)
	var i NewsletterAudience
	err := row.Scan(
		&i.ID,
		&i.MailchimpListID,
		&i.Name,
		&i.DoubleOptin,
		&i.AllowSingleOptIn,
		&i.DefaultTags,
		&i.WebhookToken,
		&i.WebhookID,
		&i.WebhookSecretEnc,
		&i.WebhookUrl,
		&i.MemberCount,
		&i.Stats,
		&i.IsDefault,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setNewsletterAudienceSyncError = `-- name: SetNewsletterAudienceSyncError :exec
UPDATE newsletter_audiences SET last_sync_error = $1, updated_at = now() WHERE id = $2
`

type SetNewsletterAudienceSyncErrorParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) SetNewsletterAudienceSyncError(ctx context.Context, arg SetNewsletterAudienceSyncErrorParams) error {
	_, err := q.db.Exec(ctx, setNewsletterAudienceSyncError, arg.Error, arg.ID)
	return err
}

const setNewsletterAudienceWebhook = `-- name: SetNewsletterAudienceWebhook :one
UPDATE newsletter_audiences
SET webhook_token = $1, webhook_id = $2,
    webhook_secret_enc = $3, webhook_url = $4, updated_at = now()
WHERE id = $5
RETURNING id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at
`

type SetNewsletterAudienceWebhookParams struct {
	Token      *string
	WebhookID  *string
	SecretEnc  []byte
	WebhookUrl *string
	ID         uuid.UUID
}

func (q *Queries) SetNewsletterAudienceWebhook(ctx context.Context, arg SetNewsletterAudienceWebhookParams) (NewsletterAudience, error) {
	row := q.db.QueryRow(ctx, setNewsletterAudienceWebhook,
		arg.Token,
		arg.WebhookID,
		arg.SecretEnc,
		arg.WebhookUrl,
		arg.ID,
	)
	var i NewsletterAudience
	err := row.Scan(
		&i.ID,
		&i.MailchimpListID,
		&i.Name,
		&i.DoubleOptin,
		&i.AllowSingleOptIn,
		&i.DefaultTags,
		&i.WebhookToken,
		&i.WebhookID,
		&i.WebhookSecretEnc,
		&i.WebhookUrl,
		&i.MemberCount,
		&i.Stats,
		&i.IsDefault,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNewsletterAudienceSettings = `-- name: UpdateNewsletterAudienceSettings :one
UPDATE newsletter_audiences
SET allow_single_opt_in = COALESCE($1, allow_single_opt_in),
    default_tags        = COALESCE($2, default_tags),
    updated_at          = now()
WHERE id = $3
RETURNING id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at
`

type UpdateNewsletterAudienceSettingsParams struct {
	AllowSingleOptIn *bool
	DefaultTags      []string
	ID               uuid.UUID
}

func (q *Queries) UpdateNewsletterAudienceSettings(ctx context.Context, arg UpdateNewsletterAudienceSettingsParams) (NewsletterAudience, error) {
	row := q.db.QueryRow(ctx, updateNewsletterAudienceSettings, arg.AllowSingleOptIn, arg.DefaultTags, arg.ID)
	var i NewsletterAudience
	err := row.Scan(
		&i.ID,
		&i.MailchimpListID,
		&i.Name,
		&i.DoubleOptin,
		&i.AllowSingleOptIn,
		&i.DefaultTags,
		&i.WebhookToken,
		&i.WebhookID,
		&i.WebhookSecretEnc,
		&i.WebhookUrl,
		&i.MemberCount,
		&i.Stats,
		&i.IsDefault,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNewsletterAudience = `-- name: UpsertNewsletterAudience :one
INSERT INTO newsletter_audiences (id, mailchimp_list_id, name, double_optin, member_count, stats, last_synced_at)
VALUES ($1, $2, $3, $4,
        $5, $6, now())
ON CONFLICT (mailchimp_list_id) DO UPDATE
SET name = EXCLUDED.name, double_optin = EXCLUDED.double_optin, member_count = EXCLUDED.member_count,
    stats = EXCLUDED.stats, last_synced_at = now(), last_sync_error = NULL, updated_at = now()
RETURNING id, mailchimp_list_id, name, double_optin, allow_single_opt_in, default_tags, webhook_token, webhook_id, webhook_secret_enc, webhook_url, member_count, stats, is_default, last_synced_at, last_sync_error, created_at, updated_at
`

type UpsertNewsletterAudienceParams struct {
	ID              uuid.UUID
	MailchimpListID string
	Name            string
	DoubleOptin     bool
	MemberCount     *int32
	Stats           []byte
}

func (q *Queries) UpsertNewsletterAudience(ctx context.Context, arg UpsertNewsletterAudienceParams) (NewsletterAudience, error) {
	row := q.db.QueryRow(ctx, upsertNewsletterAudience,
		arg.ID,
		arg.MailchimpListID,
		arg.Name,
		arg.DoubleOptin,
		arg.MemberCount,
		arg.Stats,
	)
	var i NewsletterAudience
	err := row.Scan(
		&i.ID,
		&i.MailchimpListID,
		&i.Name,
		&i.DoubleOptin,
		&i.AllowSingleOptIn,
		&i.DefaultTags,
		&i.WebhookToken,
		&i.WebhookID,
		&i.WebhookSecretEnc,
		&i.WebhookUrl,
		&i.MemberCount,
		&i.Stats,
		&i.IsDefault,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
