// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// A launched campaign's variants become active content.
	ActivateCampaignVariants(ctx context.Context, campaignID uuid.UUID) error
	AddCampaignSendingAccount(ctx context.Context, arg AddCampaignSendingAccountParams) error
	AddCampaignVariant(ctx context.Context, arg AddCampaignVariantParams) error
	AddVariantComponent(ctx context.Context, arg AddVariantComponentParams) error
	AdvanceProviderRunIngest(ctx context.Context, arg AdvanceProviderRunIngestParams) error
	ArchiveCampaign(ctx context.Context, id uuid.UUID) (Campaign, error)
	BulkSetSuppressed(ctx context.Context, arg BulkSetSuppressedParams) (int64, error)
	BumpCampaignWeightsVersion(ctx context.Context, id uuid.UUID) (int32, error)
	BumpJobStats(ctx context.Context, arg BumpJobStatsParams) error
	CancelJob(ctx context.Context, id uuid.UUID) (Job, error)
	CancelPendingJobQueries(ctx context.Context, jobID uuid.UUID) error
	CancelPendingVerificationRunItems(ctx context.Context, runID uuid.UUID) error
	CancelVerificationRun(ctx context.Context, id uuid.UUID) (VerificationRun, error)
	// A compare-and-set: only a ready campaign can start launching, and only once.
	ClaimCampaignLaunch(ctx context.Context, id uuid.UUID) (Campaign, error)
	// Compare-and-set: only a queued or failed subscription can be picked up.
	ClaimNewsletterSubscription(ctx context.Context, id uuid.UUID) (NewsletterSubscription, error)
	// The push claim. A lead is claimed only while it is pending and its contact is not
	// suppressed, so a suppressed contact is never handed to the provider.
	ClaimPendingCampaignLeads(ctx context.Context, arg ClaimPendingCampaignLeadsParams) ([]CampaignLead, error)
	ClaimProviderRunSlot(ctx context.Context, id uuid.UUID) (int64, error)
	// The hard check that stops an address reaching a third party twice.
	//
	// It is a compare-and-set, not a read followed by a write: two concurrent runs racing
	// over the same address both reach this statement, and exactly one of them updates a
	// row. The loser gets no rows back and must skip. Nothing is billed before this
	// succeeds, so the claim is what authorises the outbound call.
	ClaimThirdPartySend(ctx context.Context, id uuid.UUID) (EmailVerification, error)
	ClearCampaignVariants(ctx context.Context, campaignID uuid.UUID) error
	ClearDefaultNewsletterAudience(ctx context.Context) error
	ClearPrimaryEmail(ctx context.Context, businessID uuid.UUID) error
	ClearTypoSuggestion(ctx context.Context, id uuid.UUID) error
	ContactHasEvent(ctx context.Context, arg ContactHasEventParams) (bool, error)
	CopyJobResults(ctx context.Context, arg CopyJobResultsParams) (int64, error)
	CountAIGenerations(ctx context.Context, campaignID uuid.NullUUID) (int64, error)
	CountActiveProviderRuns(ctx context.Context, sourceID uuid.UUID) (int64, error)
	CountActiveVerificationRuns(ctx context.Context) (int64, error)
	CountActivity(ctx context.Context, arg CountActivityParams) (int64, error)
	CountAssignmentsByVariant(ctx context.Context, campaignID uuid.UUID) ([]CountAssignmentsByVariantRow, error)
	CountCampaignContactsByStage(ctx context.Context, campaignID uuid.UUID) ([]CountCampaignContactsByStageRow, error)
	CountCampaignLeadsByStatus(ctx context.Context, campaignID uuid.UUID) ([]CountCampaignLeadsByStatusRow, error)
	// "Ever reached" counts survive a later terminal stage: a contact that replied and
	// then unsubscribed still replied.
	CountCampaignLeadsEverReached(ctx context.Context, campaignID uuid.NullUUID) ([]CountCampaignLeadsEverReachedRow, error)
	CountCampaignsByStatus(ctx context.Context) ([]CountCampaignsByStatusRow, error)
	CountContactEvents(ctx context.Context, contactID uuid.UUID) (int64, error)
	CountContactsByStage(ctx context.Context) ([]CountContactsByStageRow, error)
	CountEmailComponents(ctx context.Context, arg CountEmailComponentsParams) (int64, error)
	CountEmailVariants(ctx context.Context, arg CountEmailVariantsParams) (int64, error)
	// Addresses on the master list that have never been through the free stage, whether
	// or not a verification row exists for them yet.
	CountEmailsNeedingSelfVerification(ctx context.Context) (int64, error)
	CountJobResults(ctx context.Context, jobID uuid.UUID) (int64, error)
	CountJobSitesTotal(ctx context.Context, jobID uuid.UUID) (int64, error)
	CountLockedAssignmentsForCampaign(ctx context.Context, campaignID uuid.UUID) (int64, error)
	CountLockedAssignmentsForCampaignVariant(ctx context.Context, arg CountLockedAssignmentsForCampaignVariantParams) (int64, error)
	CountLockedAssignmentsForComponent(ctx context.Context, componentID uuid.UUID) (int64, error)
	CountLockedAssignmentsForVariant(ctx context.Context, variantID uuid.UUID) (int64, error)
	CountNewsletterEligibleContacts(ctx context.Context, campaignID uuid.NullUUID) (int64, error)
	CountNewsletterSubscriptions(ctx context.Context, arg CountNewsletterSubscriptionsParams) (int64, error)
	CountNewsletterSubscriptionsByStatus(ctx context.Context) ([]CountNewsletterSubscriptionsByStatusRow, error)
	CountPendingCampaignLeads(ctx context.Context, campaignID uuid.UUID) (int64, error)
	CountPendingJobQueries(ctx context.Context, jobID uuid.UUID) (int64, error)
	CountPendingVerificationRunItems(ctx context.Context, runID uuid.UUID) (int64, error)
	CountProviderEvents(ctx context.Context, arg CountProviderEventsParams) (int64, error)
	// max() is NULL when the provider has no events at all, and the cast makes sqlc
	// scan it into a plain time.Time, so the coalesce keeps that case from failing.
	// The fallback is Go's zero time: callers read it as "never received".
	CountProviderEventsSummary(ctx context.Context, provider string) (CountProviderEventsSummaryRow, error)
	// Inside the paid band and never sent to a third party. The band has both a floor
	// (below it an address is not worth paying for) and a ceiling (at or above it the
	// free providers are already confident enough that paying adds nothing); the send
	// lock is absolute and outranks both.
	CountQualifyingForThirdParty(ctx context.Context, arg CountQualifyingForThirdPartyParams) (int64, error)
	CountSyncRuns(ctx context.Context, kind *string) (int64, error)
	CountVerificationRuns(ctx context.Context, arg CountVerificationRunsParams) (int64, error)
	CreateAIGeneration(ctx context.Context, arg CreateAIGenerationParams) (AiGeneration, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateContactConsent(ctx context.Context, arg CreateContactConsentParams) (ContactConsent, error)
	CreateContactSuppression(ctx context.Context, arg CreateContactSuppressionParams) (ContactSuppression, error)
	CreateEmailComponent(ctx context.Context, arg CreateEmailComponentParams) (EmailComponent, error)
	CreateEmailVariant(ctx context.Context, arg CreateEmailVariantParams) (EmailVariant, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateJobQuery(ctx context.Context, arg CreateJobQueryParams) (JobQuery, error)
	CreateNewsletterSubscription(ctx context.Context, arg CreateNewsletterSubscriptionParams) (NewsletterSubscription, error)
	CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (SyncRun, error)
	CreateVariantAssignment(ctx context.Context, arg CreateVariantAssignmentParams) (VariantAssignment, error)
	CreateVerificationRun(ctx context.Context, arg CreateVerificationRunParams) (VerificationRun, error)
	DeleteCampaignLead(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteJob(ctx context.Context, id uuid.UUID) (int64, error)
	// When a business already holds the corrected address, its typo'd row is dropped
	// rather than updated, because (business_id, email) is unique.
	DeleteShadowedBusinessEmails(ctx context.Context, arg DeleteShadowedBusinessEmailsParams) (int64, error)
	DeleteUnlockedAssignmentsForLead(ctx context.Context, campaignLeadID uuid.UUID) error
	EmailsPerJob(ctx context.Context, lim int32) ([]EmailsPerJobRow, error)
	FailNewsletterSubscription(ctx context.Context, arg FailNewsletterSubscriptionParams) error
	FindBusinessByDomain(ctx context.Context, domain *string) (Business, error)
	FindBusinessByPhoneZip(ctx context.Context, arg FindBusinessByPhoneZipParams) (Business, error)
	FindFreshCrawledSibling(ctx context.Context, arg FindFreshCrawledSiblingParams) (uuid.UUID, error)
	FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error
	GetAIGeneration(ctx context.Context, id uuid.UUID) (AiGeneration, error)
	GetActiveConsent(ctx context.Context, contactID uuid.UUID) (ContactConsent, error)
	GetActiveSuppression(ctx context.Context, contactID uuid.UUID) (ContactSuppression, error)
	GetBusiness(ctx context.Context, id uuid.UUID) (GetBusinessRow, error)
	GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error)
	GetCampaignByInstantlyID(ctx context.Context, instantlyCampaignID *string) (Campaign, error)
	GetCampaignLead(ctx context.Context, id uuid.UUID) (CampaignLead, error)
	GetCampaignLeadByContact(ctx context.Context, arg GetCampaignLeadByContactParams) (CampaignLead, error)
	GetCampaignLeadByInstantlyID(ctx context.Context, arg GetCampaignLeadByInstantlyIDParams) (CampaignLead, error)
	GetCampaignSettings(ctx context.Context) (CampaignSetting, error)
	GetContact(ctx context.Context, id uuid.UUID) (Contact, error)
	GetContactByEmail(ctx context.Context, email string) (Contact, error)
	GetContactConsent(ctx context.Context, id uuid.UUID) (ContactConsent, error)
	GetContactSuppression(ctx context.Context, id uuid.UUID) (ContactSuppression, error)
	GetDefaultNewsletterAudience(ctx context.Context) (NewsletterAudience, error)
	GetEmailComponent(ctx context.Context, id uuid.UUID) (EmailComponent, error)
	GetEmailSend(ctx context.Context, arg GetEmailSendParams) (EmailSend, error)
	GetEmailVariant(ctx context.Context, id uuid.UUID) (EmailVariant, error)
	GetEmailVerification(ctx context.Context, id uuid.UUID) (EmailVerification, error)
	GetEmailVerificationByEmail(ctx context.Context, email string) (EmailVerification, error)
	GetJob(ctx context.Context, id uuid.UUID) (GetJobRow, error)
	GetJobQuery(ctx context.Context, id uuid.UUID) (JobQuery, error)
	GetJobStats(ctx context.Context, id uuid.UUID) ([]byte, error)
	GetJobStatus(ctx context.Context, id uuid.UUID) (string, error)
	GetLatestEmailSendForLead(ctx context.Context, campaignLeadID uuid.UUID) (EmailSend, error)
	GetNewsletterAudience(ctx context.Context, id uuid.UUID) (NewsletterAudience, error)
	GetNewsletterAudienceByListID(ctx context.Context, mailchimpListID string) (NewsletterAudience, error)
	GetNewsletterAudienceByToken(ctx context.Context, webhookToken *string) (NewsletterAudience, error)
	GetNewsletterSubscription(ctx context.Context, id uuid.UUID) (NewsletterSubscription, error)
	GetNewsletterSubscriptionByContact(ctx context.Context, arg GetNewsletterSubscriptionByContactParams) (NewsletterSubscription, error)
	GetNewsletterSubscriptionByHash(ctx context.Context, arg GetNewsletterSubscriptionByHashParams) (NewsletterSubscription, error)
	GetProviderEvent(ctx context.Context, id uuid.UUID) (ProviderEvent, error)
	GetSendingAccount(ctx context.Context, id uuid.UUID) (SendingAccount, error)
	GetSendingAccountByEmail(ctx context.Context, email string) (SendingAccount, error)
	GetSource(ctx context.Context, id uuid.UUID) (Source, error)
	GetVariantAssignment(ctx context.Context, arg GetVariantAssignmentParams) (VariantAssignment, error)
	GetVariantAssignmentByID(ctx context.Context, id uuid.UUID) (VariantAssignment, error)
	GetVerificationDomain(ctx context.Context, domain string) (VerificationDomain, error)
	GetVerificationRun(ctx context.Context, id uuid.UUID) (VerificationRun, error)
	GetVerificationSettings(ctx context.Context) (VerificationSetting, error)
	InsertBusiness(ctx context.Context, arg InsertBusinessParams) (Business, error)
	InsertBusinessEmail(ctx context.Context, arg InsertBusinessEmailParams) (BusinessEmail, error)
	InsertCampaignLead(ctx context.Context, arg InsertCampaignLeadParams) (CampaignLead, error)
	InsertContactEvent(ctx context.Context, arg InsertContactEventParams) (ContactEvent, error)
	InsertJobEvent(ctx context.Context, arg InsertJobEventParams) (InsertJobEventRow, error)
	// The dedupe key makes a redelivery a no-op: no row comes back, and nothing is queued.
	InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (ProviderEvent, error)
	InsertVerificationRunItems(ctx context.Context, arg InsertVerificationRunItemsParams) (int64, error)
	LastFinishedVerificationRun(ctx context.Context, pass string) (VerificationRun, error)
	LastSyncRun(ctx context.Context, kind string) (SyncRun, error)
	// Zero time when the campaign has no events: max() is NULL there, and the cast
	// makes sqlc scan the column into a plain time.Time.
	LatestCampaignActivityAt(ctx context.Context, campaignID uuid.NullUUID) (time.Time, error)
	LatestCampaignAnalyticsSnapshot(ctx context.Context, arg LatestCampaignAnalyticsSnapshotParams) (CampaignAnalyticsSnapshot, error)
	// Zero time when the campaign has no sends: max() is NULL there, and the cast
	// makes sqlc scan the column into a plain time.Time.
	LatestSendTimestampForCampaign(ctx context.Context, campaignID uuid.UUID) (time.Time, error)
	LiftContactSuppression(ctx context.Context, arg LiftContactSuppressionParams) (Contact, error)
	LiftSuppression(ctx context.Context, arg LiftSuppressionParams) (ContactSuppression, error)
	ListAIGenerations(ctx context.Context, arg ListAIGenerationsParams) ([]AiGeneration, error)
	ListActiveCampaignVariantsForStep(ctx context.Context, arg ListActiveCampaignVariantsForStepParams) ([]ListActiveCampaignVariantsForStepRow, error)
	ListActivity(ctx context.Context, arg ListActivityParams) ([]ContactEvent, error)
	ListBusinessEmails(ctx context.Context, businessID uuid.UUID) ([]BusinessEmail, error)
	// The detail view needs each address's verification alongside it; the LEFT JOIN keeps
	// addresses that have never been through Pass 1.
	ListBusinessEmailsWithVerification(ctx context.Context, businessID uuid.UUID) ([]ListBusinessEmailsWithVerificationRow, error)
	ListBusinessIDsForEmail(ctx context.Context, email string) ([]uuid.UUID, error)
	ListBusinessesForEmail(ctx context.Context, email string) ([]ListBusinessesForEmailRow, error)
	ListCampaignAnalyticsSnapshots(ctx context.Context, arg ListCampaignAnalyticsSnapshotsParams) ([]CampaignAnalyticsSnapshot, error)
	ListCampaignLeadContactIDs(ctx context.Context, campaignID uuid.UUID) ([]uuid.UUID, error)
	ListCampaignLeadEvents(ctx context.Context, campaignLeadID uuid.NullUUID) ([]ContactEvent, error)
	ListCampaignLeadsForContact(ctx context.Context, contactID uuid.UUID) ([]CampaignLead, error)
	ListCampaignSendingAccounts(ctx context.Context, campaignID uuid.UUID) ([]SendingAccount, error)
	ListCampaignVariants(ctx context.Context, campaignID uuid.UUID) ([]ListCampaignVariantsRow, error)
	ListCampaignsByStatus(ctx context.Context, statuses []string) ([]Campaign, error)
	ListCampaignsForSendingAccount(ctx context.Context, sendingAccountID uuid.UUID) ([]Campaign, error)
	ListCampaignsUsingVariant(ctx context.Context, variantID uuid.UUID) ([]Campaign, error)
	ListContactConsents(ctx context.Context, contactID uuid.UUID) ([]ContactConsent, error)
	ListContactEvents(ctx context.Context, arg ListContactEventsParams) ([]ContactEvent, error)
	ListContactSuppressions(ctx context.Context, contactID uuid.UUID) ([]ContactSuppression, error)
	ListEmailComponents(ctx context.Context, arg ListEmailComponentsParams) ([]EmailComponent, error)
	ListEmailComponentsByIDs(ctx context.Context, ids []uuid.UUID) ([]EmailComponent, error)
	ListEmailSendsForLead(ctx context.Context, campaignLeadID uuid.UUID) ([]EmailSend, error)
	ListEmailVariants(ctx context.Context, arg ListEmailVariantsParams) ([]EmailVariant, error)
	ListEmailVariantsByIDs(ctx context.Context, ids []uuid.UUID) ([]EmailVariant, error)
	ListJobCrawlTargets(ctx context.Context, jid uuid.UUID) ([]ListJobCrawlTargetsRow, error)
	ListJobEventsAfter(ctx context.Context, arg ListJobEventsAfterParams) ([]JobEvent, error)
	ListJobQueries(ctx context.Context, jobID uuid.UUID) ([]JobQuery, error)
	ListNewsletterAudiences(ctx context.Context) ([]NewsletterAudience, error)
	// Contacts who could be pushed now, and those one step short with the reason why.
	ListNewsletterEligibleContacts(ctx context.Context, arg ListNewsletterEligibleContactsParams) ([]ListNewsletterEligibleContactsRow, error)
	ListNewsletterSubscriptions(ctx context.Context, arg ListNewsletterSubscriptionsParams) ([]ListNewsletterSubscriptionsRow, error)
	ListNewsletterSubscriptionsForContact(ctx context.Context, contactID uuid.UUID) ([]NewsletterSubscription, error)
	ListNewsletterSubscriptionsToReconcile(ctx context.Context, arg ListNewsletterSubscriptionsToReconcileParams) ([]NewsletterSubscription, error)
	ListProviderEvents(ctx context.Context, arg ListProviderEventsParams) ([]ProviderEvent, error)
	ListProviderRunIDsForSource(ctx context.Context, sourceID uuid.UUID) ([]*string, error)
	ListPushedCampaignLeads(ctx context.Context, campaignID uuid.UUID) ([]CampaignLead, error)
	// Every lead of a contact that reached the provider, whatever state it is in now.
	// Suppression uses this rather than the rows it just stopped, because a lead can
	// already be terminal (bounced, unsubscribed) and still be sitting in Instantly.
	ListPushedCampaignLeadsForContact(ctx context.Context, contactID uuid.UUID) ([]CampaignLead, error)
	ListQueuedVerificationRunItems(ctx context.Context, runID uuid.UUID) ([]uuid.UUID, error)
	ListRecentJobEvents(ctx context.Context, arg ListRecentJobEventsParams) ([]JobEvent, error)
	ListSendingAccountStatsDaily(ctx context.Context, arg ListSendingAccountStatsDailyParams) ([]SendingAccountStatsDaily, error)
	ListSendingAccounts(ctx context.Context, arg ListSendingAccountsParams) ([]SendingAccount, error)
	ListSendingAccountsByIDs(ctx context.Context, ids []uuid.UUID) ([]SendingAccount, error)
	ListSources(ctx context.Context) ([]Source, error)
	ListSyncRuns(ctx context.Context, arg ListSyncRunsParams) ([]SyncRun, error)
	ListVariantAssignmentsForLead(ctx context.Context, campaignLeadID uuid.UUID) ([]VariantAssignment, error)
	ListVariantComponents(ctx context.Context, variantID uuid.UUID) ([]ListVariantComponentsRow, error)
	ListVariantsUsingComponent(ctx context.Context, componentID uuid.UUID) ([]EmailVariant, error)
	ListVerificationRuns(ctx context.Context, arg ListVerificationRunsParams) ([]VerificationRun, error)
	// Asynchronous provider runs.
	//
	// The claim below is what stops a retry from paying for a second run: a row leaves
	// 'none' exactly once, and only a row in 'none' may start one.
	LockProviderRunSlots(ctx context.Context, key int64) error
	LockVariantAssignments(ctx context.Context, campaignLeadID uuid.UUID) error
	MarkBusinessCrawled(ctx context.Context, id uuid.UUID) error
	MarkCampaignActive(ctx context.Context, id uuid.UUID) (Campaign, error)
	MarkCampaignCompleted(ctx context.Context, id uuid.UUID) (Campaign, error)
	MarkCampaignFailed(ctx context.Context, arg MarkCampaignFailedParams) (Campaign, error)
	MarkCampaignLeadPushed(ctx context.Context, arg MarkCampaignLeadPushedParams) (CampaignLead, error)
	MarkCampaignLeadStatus(ctx context.Context, arg MarkCampaignLeadStatusParams) (CampaignLead, error)
	MarkCampaignLeadTerminal(ctx context.Context, arg MarkCampaignLeadTerminalParams) error
	MarkCampaignPaused(ctx context.Context, id uuid.UUID) (Campaign, error)
	MarkCampaignReady(ctx context.Context, id uuid.UUID) (Campaign, error)
	MarkJobQueryDone(ctx context.Context, arg MarkJobQueryDoneParams) error
	MarkJobQueryFailed(ctx context.Context, arg MarkJobQueryFailedParams) error
	MarkJobQueryRunning(ctx context.Context, id uuid.UUID) error
	MarkJobRunning(ctx context.Context, id uuid.UUID) error
	MarkJobTerminal(ctx context.Context, arg MarkJobTerminalParams) error
	MarkNewsletterSubscriptionSynced(ctx context.Context, arg MarkNewsletterSubscriptionSyncedParams) (NewsletterSubscription, error)
	MarkProviderEventAttempt(ctx context.Context, arg MarkProviderEventAttemptParams) error
	MarkProviderEventProcessed(ctx context.Context, arg MarkProviderEventProcessedParams) error
	MarkProviderRunResurrected(ctx context.Context, id uuid.UUID) error
	MarkVerificationRunItem(ctx context.Context, arg MarkVerificationRunItemParams) error
	MarkVerificationRunRunning(ctx context.Context, id uuid.UUID) error
	MarkVerificationRunTerminal(ctx context.Context, arg MarkVerificationRunTerminalParams) error
	// A webhook or a reconcile telling us what Mailchimp now says.
	MirrorNewsletterSubscriptionStatus(ctx context.Context, arg MirrorNewsletterSubscriptionStatusParams) (NewsletterSubscription, error)
	PruneJobEvents(ctx context.Context, maxAgeDays int32) (int64, error)
	RecomputeCampaignCounts(ctx context.Context, id uuid.UUID) (Campaign, error)
	RecomputeJobStats(ctx context.Context, jid uuid.UUID) (RecomputeJobStatsRow, error)
	RecomputeVerificationRunStats(ctx context.Context, id uuid.UUID) (VerificationRun, error)
	RecordCampaignLeadClick(ctx context.Context, arg RecordCampaignLeadClickParams) error
	RecordCampaignLeadContact(ctx context.Context, arg RecordCampaignLeadContactParams) error
	RecordCampaignLeadOpen(ctx context.Context, arg RecordCampaignLeadOpenParams) error
	RecordCampaignLeadReply(ctx context.Context, arg RecordCampaignLeadReplyParams) error
	RecordSendBounce(ctx context.Context, arg RecordSendBounceParams) error
	RecordSendClick(ctx context.Context, arg RecordSendClickParams) error
	RecordSendOpen(ctx context.Context, arg RecordSendOpenParams) error
	RecordSendReply(ctx context.Context, arg RecordSendReplyParams) error
	RecordSendUnsubscribe(ctx context.Context, arg RecordSendUnsubscribeParams) error
	ReleaseCampaignLeadClaims(ctx context.Context, arg ReleaseCampaignLeadClaimsParams) (int64, error)
	ReleaseProviderRunSlot(ctx context.Context, id uuid.UUID) error
	// Gives the claim back when the call never reached the provider: a rejected API key,
	// a throttle, a transport failure. Our own infrastructure failing must not spend an
	// address's one and only send. The pass2_verified_at guard means a claim that did
	// produce a verdict can never be released, and the database enforces that too.
	ReleaseThirdPartySend(ctx context.Context, id uuid.UUID) (int64, error)
	ReplaceVariantComponents(ctx context.Context, variantID uuid.UUID) error
	RequeueNewsletterSubscription(ctx context.Context, arg RequeueNewsletterSubscriptionParams) (NewsletterSubscription, error)
	ResetProviderEvent(ctx context.Context, id uuid.UUID) (ProviderEvent, error)
	RetargetBusinessEmails(ctx context.Context, arg RetargetBusinessEmailsParams) (int64, error)
	RevokeConsent(ctx context.Context, arg RevokeConsentParams) (ContactConsent, error)
	SaveProviderRun(ctx context.Context, arg SaveProviderRunParams) error
	ScraperCounters(ctx context.Context) (ScraperCountersRow, error)
	SetAIGenerationFailed(ctx context.Context, arg SetAIGenerationFailedParams) error
	SetAIGenerationImported(ctx context.Context, arg SetAIGenerationImportedParams) (AiGeneration, error)
	SetAIGenerationParsed(ctx context.Context, arg SetAIGenerationParsedParams) (AiGeneration, error)
	SetCampaignInstantlyID(ctx context.Context, arg SetCampaignInstantlyIDParams) (Campaign, error)
	SetCampaignLeadInterest(ctx context.Context, arg SetCampaignLeadInterestParams) error
	SetCampaignLeadProviderState(ctx context.Context, arg SetCampaignLeadProviderStateParams) error
	SetCampaignProviderState(ctx context.Context, arg SetCampaignProviderStateParams) error
	SetCampaignSendingAccounts(ctx context.Context, campaignID uuid.UUID) error
	SetCampaignStatus(ctx context.Context, arg SetCampaignStatusParams) (Campaign, error)
	SetCampaignSyncError(ctx context.Context, arg SetCampaignSyncErrorParams) error
	// The trigger enforces the rules; this statement only moves the pointer.
	SetContactStage(ctx context.Context, arg SetContactStageParams) (Contact, error)
	SetDefaultAudience(ctx context.Context, audienceID uuid.NullUUID) error
	SetDefaultNewsletterAudience(ctx context.Context, id uuid.UUID) (NewsletterAudience, error)
	SetEmailComponentStatus(ctx context.Context, arg SetEmailComponentStatusParams) (EmailComponent, error)
	SetEmailVariantStatus(ctx context.Context, arg SetEmailVariantStatusParams) (EmailVariant, error)
	SetInstantlyWebhook(ctx context.Context, arg SetInstantlyWebhookParams) (CampaignSetting, error)
	SetInstantlyWebhookStatus(ctx context.Context, arg SetInstantlyWebhookStatusParams) error
	SetJobStats(ctx context.Context, arg SetJobStatsParams) error
	SetNewsletterAudienceSyncError(ctx context.Context, arg SetNewsletterAudienceSyncErrorParams) error
	SetNewsletterAudienceWebhook(ctx context.Context, arg SetNewsletterAudienceWebhookParams) (NewsletterAudience, error)
	SetPrimaryEmail(ctx context.Context, id uuid.UUID) error
	SetProviderRunStatus(ctx context.Context, arg SetProviderRunStatusParams) error
	SetSendReplyClassification(ctx context.Context, arg SetSendReplyClassificationParams) error
	SetSourceTestResult(ctx context.Context, arg SetSourceTestResultParams) error
	SetVerificationError(ctx context.Context, arg SetVerificationErrorParams) error
	SetVerificationRunTotal(ctx context.Context, arg SetVerificationRunTotalParams) error
	// Provider-reported totals per account over a window, for the accounts list.
	SumSendingAccountStats(ctx context.Context, since pgtype.Date) ([]SumSendingAccountStatsRow, error)
	// Every non-terminal lead of a suppressed contact stops where it is.
	SuppressCampaignLeadsForContact(ctx context.Context, contactID uuid.UUID) ([]CampaignLead, error)
	SuppressContact(ctx context.Context, arg SuppressContactParams) (Contact, error)
	TouchContactEvent(ctx context.Context, arg TouchContactEventParams) error
	UpdateBusinessFlags(ctx context.Context, arg UpdateBusinessFlagsParams) (uuid.UUID, error)
	UpdateBusinessFromListing(ctx context.Context, arg UpdateBusinessFromListingParams) (Business, error)
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error)
	UpdateContactProfile(ctx context.Context, arg UpdateContactProfileParams) (Contact, error)
	UpdateEmailComponent(ctx context.Context, arg UpdateEmailComponentParams) (EmailComponent, error)
	UpdateEmailVariant(ctx context.Context, arg UpdateEmailVariantParams) (EmailVariant, error)
	UpdateNewsletterAudienceSettings(ctx context.Context, arg UpdateNewsletterAudienceSettingsParams) (NewsletterAudience, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
	// The free stage writes the local pipeline's own breakdown and the weighted result of
	// every free provider in one statement, so a row can never show a free score without
	// the breakdown that explains it.
	UpdateVerificationPass1(ctx context.Context, arg UpdateVerificationPass1Params) (EmailVerification, error)
	// A billable outcome: deliverable, risky or undeliverable. Written once and never
	// again; third_party_sent_at is already held by the claim that authorised the call.
	UpdateVerificationPass2(ctx context.Context, arg UpdateVerificationPass2Params) (EmailVerification, error)
	// "unknown" and hard errors keep the free score and store no verdict, so
	// pass2_verified_at stays as it was. Whether the address may be tried again is not
	// decided here but by third_party_sent_at: an answer of "unknown" came from the
	// provider and keeps the lock, while a call that never arrived releases it.
	UpdateVerificationPass2Inconclusive(ctx context.Context, arg UpdateVerificationPass2InconclusiveParams) (EmailVerification, error)
	UpsertBusinessByPlaceID(ctx context.Context, arg UpsertBusinessByPlaceIDParams) (Business, error)
	UpsertCampaignAnalyticsSnapshot(ctx context.Context, arg UpsertCampaignAnalyticsSnapshotParams) error
	// Creates the contact the first time an address is seen. The no-op DO UPDATE lets one
	// statement insert and return the existing row; it never overwrites the stage.
	UpsertContact(ctx context.Context, arg UpsertContactParams) (Contact, error)
	// One send per lead per step. A second report of the same send (webhook then
	// reconcile) fills in what was missing rather than creating a duplicate.
	UpsertEmailSend(ctx context.Context, arg UpsertEmailSendParams) (EmailSend, error)
	// Creates the row the first time an address is verified. The no-op DO UPDATE lets a
	// single statement both insert and return the existing row.
	UpsertEmailVerification(ctx context.Context, arg UpsertEmailVerificationParams) (EmailVerification, error)
	UpsertJobResult(ctx context.Context, arg UpsertJobResultParams) error
	UpsertNewsletterAudience(ctx context.Context, arg UpsertNewsletterAudienceParams) (NewsletterAudience, error)
	UpsertSendingAccount(ctx context.Context, arg UpsertSendingAccountParams) (SendingAccount, error)
	UpsertSendingAccountStatsDaily(ctx context.Context, arg UpsertSendingAccountStatsDailyParams) error
	UpsertVerificationDNS(ctx context.Context, arg UpsertVerificationDNSParams) (VerificationDomain, error)
	UpsertVerificationRDAP(ctx context.Context, arg UpsertVerificationRDAPParams) error
	// One row, always id 1. The service validates the weights before calling this; the
	// column constraints only catch the thresholds, because "the weights total 100" is
	// not expressible against a JSONB object without a function.
	UpsertVerificationSettings(ctx context.Context, arg UpsertVerificationSettingsParams) (VerificationSetting, error)
	VerificationCounters(ctx context.Context) (VerificationCountersRow, error)
}

var _ Querier = (*Queries)(nil)
