// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scrape_categories.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createScrapeCategory = `-- name: CreateScrapeCategory :one
INSERT INTO scrape_categories (id, name, terms)
VALUES ($1, $2, $3::text[])
RETURNING id, name, terms, is_default, created_at, updated_at
`

type CreateScrapeCategoryParams struct {
	ID    uuid.UUID
	Name  string
	Terms []string
}

func (q *Queries) CreateScrapeCategory(ctx context.Context, arg CreateScrapeCategoryParams) (ScrapeCategory, error) {
	row := q.db.QueryRow(ctx, createScrapeCategory, arg.ID, arg.Name, arg.Terms)
	var i ScrapeCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Terms,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScrapeCategory = `-- name: DeleteScrapeCategory :execrows
DELETE FROM scrape_categories WHERE id = $1 AND NOT is_default
`

func (q *Queries) DeleteScrapeCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScrapeCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScrapeCategory = `-- name: GetScrapeCategory :one
SELECT id, name, terms, is_default, created_at, updated_at FROM scrape_categories WHERE id = $1
`

func (q *Queries) GetScrapeCategory(ctx context.Context, id uuid.UUID) (ScrapeCategory, error) {
	row := q.db.QueryRow(ctx, getScrapeCategory, id)
	var i ScrapeCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Terms,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScrapeCategories = `-- name: ListScrapeCategories :many
SELECT id, name, terms, is_default, created_at, updated_at FROM scrape_categories ORDER BY is_default DESC, created_at, lower(name)
`

// Defaults first, in seed order, then the user's own categories by name.
func (q *Queries) ListScrapeCategories(ctx context.Context) ([]ScrapeCategory, error) {
	rows, err := q.db.Query(ctx, listScrapeCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapeCategory{}
	for rows.Next() {
		var i ScrapeCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Terms,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScrapeCategory = `-- name: UpdateScrapeCategory :one
UPDATE scrape_categories
SET name       = COALESCE($1, name),
    terms      = COALESCE($2::text[], terms),
    updated_at = now()
WHERE id = $3
RETURNING id, name, terms, is_default, created_at, updated_at
`

type UpdateScrapeCategoryParams struct {
	Name  *string
	Terms []string
	ID    uuid.UUID
}

func (q *Queries) UpdateScrapeCategory(ctx context.Context, arg UpdateScrapeCategoryParams) (ScrapeCategory, error) {
	row := q.db.QueryRow(ctx, updateScrapeCategory, arg.Name, arg.Terms, arg.ID)
	var i ScrapeCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Terms,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
