// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sending_accounts.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSendingAccount = `-- name: GetSendingAccount :one
SELECT id, email, first_name, last_name, provider_code, status, warmup_status, daily_limit, sending_gap, warmup_score, status_message, tracking_domain, tracking_domain_status, setup_pending, is_managed, raw, last_synced_at, created_at, updated_at FROM sending_accounts WHERE id = $1
`

func (q *Queries) GetSendingAccount(ctx context.Context, id uuid.UUID) (SendingAccount, error) {
	row := q.db.QueryRow(ctx, getSendingAccount, id)
	var i SendingAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ProviderCode,
		&i.Status,
		&i.WarmupStatus,
		&i.DailyLimit,
		&i.SendingGap,
		&i.WarmupScore,
		&i.StatusMessage,
		&i.TrackingDomain,
		&i.TrackingDomainStatus,
		&i.SetupPending,
		&i.IsManaged,
		&i.Raw,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSendingAccountByEmail = `-- name: GetSendingAccountByEmail :one
SELECT id, email, first_name, last_name, provider_code, status, warmup_status, daily_limit, sending_gap, warmup_score, status_message, tracking_domain, tracking_domain_status, setup_pending, is_managed, raw, last_synced_at, created_at, updated_at FROM sending_accounts WHERE email = $1
`

func (q *Queries) GetSendingAccountByEmail(ctx context.Context, email string) (SendingAccount, error) {
	row := q.db.QueryRow(ctx, getSendingAccountByEmail, email)
	var i SendingAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ProviderCode,
		&i.Status,
		&i.WarmupStatus,
		&i.DailyLimit,
		&i.SendingGap,
		&i.WarmupScore,
		&i.StatusMessage,
		&i.TrackingDomain,
		&i.TrackingDomainStatus,
		&i.SetupPending,
		&i.IsManaged,
		&i.Raw,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSendingAccountStatsDaily = `-- name: ListSendingAccountStatsDaily :many
SELECT sending_account_id, day, sent, bounced, contacted, new_leads_contacted, opened, unique_opened, replies, unique_replies, clicks, unique_clicks, fetched_at FROM sending_account_stats_daily
WHERE sending_account_id = $1 AND day >= $2
ORDER BY day
`

type ListSendingAccountStatsDailyParams struct {
	SendingAccountID uuid.UUID
	Since            pgtype.Date
}

func (q *Queries) ListSendingAccountStatsDaily(ctx context.Context, arg ListSendingAccountStatsDailyParams) ([]SendingAccountStatsDaily, error) {
	rows, err := q.db.Query(ctx, listSendingAccountStatsDaily, arg.SendingAccountID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SendingAccountStatsDaily{}
	for rows.Next() {
		var i SendingAccountStatsDaily
		if err := rows.Scan(
			&i.SendingAccountID,
			&i.Day,
			&i.Sent,
			&i.Bounced,
			&i.Contacted,
			&i.NewLeadsContacted,
			&i.Opened,
			&i.UniqueOpened,
			&i.Replies,
			&i.UniqueReplies,
			&i.Clicks,
			&i.UniqueClicks,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendingAccounts = `-- name: ListSendingAccounts :many
SELECT id, email, first_name, last_name, provider_code, status, warmup_status, daily_limit, sending_gap, warmup_score, status_message, tracking_domain, tracking_domain_status, setup_pending, is_managed, raw, last_synced_at, created_at, updated_at FROM sending_accounts
WHERE ($1::int IS NULL OR status = $1::int)
  AND ($2::text IS NULL OR email::text ILIKE '%' || $2::text || '%')
ORDER BY email
`

type ListSendingAccountsParams struct {
	Status *int32
	Q      *string
}

func (q *Queries) ListSendingAccounts(ctx context.Context, arg ListSendingAccountsParams) ([]SendingAccount, error) {
	rows, err := q.db.Query(ctx, listSendingAccounts, arg.Status, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SendingAccount{}
	for rows.Next() {
		var i SendingAccount
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.ProviderCode,
			&i.Status,
			&i.WarmupStatus,
			&i.DailyLimit,
			&i.SendingGap,
			&i.WarmupScore,
			&i.StatusMessage,
			&i.TrackingDomain,
			&i.TrackingDomainStatus,
			&i.SetupPending,
			&i.IsManaged,
			&i.Raw,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendingAccountsByIDs = `-- name: ListSendingAccountsByIDs :many
SELECT id, email, first_name, last_name, provider_code, status, warmup_status, daily_limit, sending_gap, warmup_score, status_message, tracking_domain, tracking_domain_status, setup_pending, is_managed, raw, last_synced_at, created_at, updated_at FROM sending_accounts WHERE id = ANY($1::uuid[]) ORDER BY email
`

func (q *Queries) ListSendingAccountsByIDs(ctx context.Context, ids []uuid.UUID) ([]SendingAccount, error) {
	rows, err := q.db.Query(ctx, listSendingAccountsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SendingAccount{}
	for rows.Next() {
		var i SendingAccount
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.ProviderCode,
			&i.Status,
			&i.WarmupStatus,
			&i.DailyLimit,
			&i.SendingGap,
			&i.WarmupScore,
			&i.StatusMessage,
			&i.TrackingDomain,
			&i.TrackingDomainStatus,
			&i.SetupPending,
			&i.IsManaged,
			&i.Raw,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSendingAccountStats = `-- name: SumSendingAccountStats :many
SELECT sending_account_id,
       COALESCE(sum(sent), 0)::bigint      AS sent,
       COALESCE(sum(bounced), 0)::bigint   AS bounced,
       COALESCE(sum(replies), 0)::bigint   AS replies,
       COALESCE(sum(unique_replies), 0)::bigint AS unique_replies,
       max(day)::date                      AS last_day
FROM sending_account_stats_daily
WHERE day >= $1
GROUP BY sending_account_id
`

type SumSendingAccountStatsRow struct {
	SendingAccountID uuid.UUID
	Sent             int64
	Bounced          int64
	Replies          int64
	UniqueReplies    int64
	LastDay          pgtype.Date
}

// Provider-reported totals per account over a window, for the accounts list.
func (q *Queries) SumSendingAccountStats(ctx context.Context, since pgtype.Date) ([]SumSendingAccountStatsRow, error) {
	rows, err := q.db.Query(ctx, sumSendingAccountStats, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumSendingAccountStatsRow{}
	for rows.Next() {
		var i SumSendingAccountStatsRow
		if err := rows.Scan(
			&i.SendingAccountID,
			&i.Sent,
			&i.Bounced,
			&i.Replies,
			&i.UniqueReplies,
			&i.LastDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSendingAccount = `-- name: UpsertSendingAccount :one
INSERT INTO sending_accounts (id, email, first_name, last_name, provider_code, status, warmup_status, daily_limit,
                              sending_gap, warmup_score, status_message, tracking_domain, tracking_domain_status,
                              setup_pending, is_managed, raw, last_synced_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11, $12,
        $13, $14, $15, $16, now())
ON CONFLICT (email) DO UPDATE
SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, provider_code = EXCLUDED.provider_code,
    status = EXCLUDED.status, warmup_status = EXCLUDED.warmup_status, daily_limit = EXCLUDED.daily_limit,
    sending_gap = EXCLUDED.sending_gap, warmup_score = EXCLUDED.warmup_score, status_message = EXCLUDED.status_message,
    tracking_domain = EXCLUDED.tracking_domain, tracking_domain_status = EXCLUDED.tracking_domain_status,
    setup_pending = EXCLUDED.setup_pending, is_managed = EXCLUDED.is_managed, raw = EXCLUDED.raw,
    last_synced_at = now(), updated_at = now()
RETURNING id, email, first_name, last_name, provider_code, status, warmup_status, daily_limit, sending_gap, warmup_score, status_message, tracking_domain, tracking_domain_status, setup_pending, is_managed, raw, last_synced_at, created_at, updated_at
`

type UpsertSendingAccountParams struct {
	ID                   uuid.UUID
	Email                string
	FirstName            *string
	LastName             *string
	ProviderCode         *int32
	Status               int32
	WarmupStatus         *int32
	DailyLimit           *int32
	SendingGap           *int32
	WarmupScore          *int32
	StatusMessage        *string
	TrackingDomain       *string
	TrackingDomainStatus *string
	SetupPending         bool
	IsManaged            bool
	Raw                  []byte
}

func (q *Queries) UpsertSendingAccount(ctx context.Context, arg UpsertSendingAccountParams) (SendingAccount, error) {
	row := q.db.QueryRow(ctx, upsertSendingAccount,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.ProviderCode,
		arg.Status,
		arg.WarmupStatus,
		arg.DailyLimit,
		arg.SendingGap,
		arg.WarmupScore,
		arg.StatusMessage,
		arg.TrackingDomain,
		arg.TrackingDomainStatus,
		arg.SetupPending,
		arg.IsManaged,
		arg.Raw,
	)
	var i SendingAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ProviderCode,
		&i.Status,
		&i.WarmupStatus,
		&i.DailyLimit,
		&i.SendingGap,
		&i.WarmupScore,
		&i.StatusMessage,
		&i.TrackingDomain,
		&i.TrackingDomainStatus,
		&i.SetupPending,
		&i.IsManaged,
		&i.Raw,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSendingAccountStatsDaily = `-- name: UpsertSendingAccountStatsDaily :exec
INSERT INTO sending_account_stats_daily (sending_account_id, day, sent, bounced, contacted, new_leads_contacted,
                                         opened, unique_opened, replies, unique_replies, clicks, unique_clicks, fetched_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11, $12, now())
ON CONFLICT (sending_account_id, day) DO UPDATE
SET sent = EXCLUDED.sent, bounced = EXCLUDED.bounced, contacted = EXCLUDED.contacted,
    new_leads_contacted = EXCLUDED.new_leads_contacted, opened = EXCLUDED.opened, unique_opened = EXCLUDED.unique_opened,
    replies = EXCLUDED.replies, unique_replies = EXCLUDED.unique_replies, clicks = EXCLUDED.clicks,
    unique_clicks = EXCLUDED.unique_clicks, fetched_at = now()
`

type UpsertSendingAccountStatsDailyParams struct {
	SendingAccountID  uuid.UUID
	Day               pgtype.Date
	Sent              int32
	Bounced           int32
	Contacted         int32
	NewLeadsContacted int32
	Opened            int32
	UniqueOpened      int32
	Replies           int32
	UniqueReplies     int32
	Clicks            int32
	UniqueClicks      int32
}

func (q *Queries) UpsertSendingAccountStatsDaily(ctx context.Context, arg UpsertSendingAccountStatsDailyParams) error {
	_, err := q.db.Exec(ctx, upsertSendingAccountStatsDaily,
		arg.SendingAccountID,
		arg.Day,
		arg.Sent,
		arg.Bounced,
		arg.Contacted,
		arg.NewLeadsContacted,
		arg.Opened,
		arg.UniqueOpened,
		arg.Replies,
		arg.UniqueReplies,
		arg.Clicks,
		arg.UniqueClicks,
	)
	return err
}
