// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sources.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const getSource = `-- name: GetSource :one
SELECT id, kind, name, api_key_enc, cost_per_1k_cents, enabled, last_tested_at, last_test_ok, created_at, updated_at, role, max_active_runs FROM sources WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ApiKeyEnc,
		&i.CostPer1kCents,
		&i.Enabled,
		&i.LastTestedAt,
		&i.LastTestOk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.MaxActiveRuns,
	)
	return i, err
}

const getSourceByKind = `-- name: GetSourceByKind :one
SELECT id, kind, name, api_key_enc, cost_per_1k_cents, enabled, last_tested_at, last_test_ok, created_at, updated_at, role, max_active_runs FROM sources WHERE kind = $1
`

func (q *Queries) GetSourceByKind(ctx context.Context, kind string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByKind, kind)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ApiKeyEnc,
		&i.CostPer1kCents,
		&i.Enabled,
		&i.LastTestedAt,
		&i.LastTestOk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.MaxActiveRuns,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, kind, name, api_key_enc, cost_per_1k_cents, enabled, last_tested_at, last_test_ok, created_at, updated_at, role, max_active_runs FROM sources ORDER BY name
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.ApiKeyEnc,
			&i.CostPer1kCents,
			&i.Enabled,
			&i.LastTestedAt,
			&i.LastTestOk,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.MaxActiveRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSourceTestResult = `-- name: SetSourceTestResult :exec
UPDATE sources
SET last_tested_at = now(),
    last_test_ok   = $1,
    updated_at     = now()
WHERE id = $2
`

type SetSourceTestResultParams struct {
	Ok *bool
	ID uuid.UUID
}

func (q *Queries) SetSourceTestResult(ctx context.Context, arg SetSourceTestResultParams) error {
	_, err := q.db.Exec(ctx, setSourceTestResult, arg.Ok, arg.ID)
	return err
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET name              = COALESCE($1, name),
    cost_per_1k_cents = COALESCE($2, cost_per_1k_cents),
    enabled           = COALESCE($3, enabled),
    max_active_runs   = COALESCE($4, max_active_runs),
    api_key_enc       = CASE WHEN $5::boolean THEN $6
                             ELSE api_key_enc END,
    updated_at        = now()
WHERE id = $7
RETURNING id, kind, name, api_key_enc, cost_per_1k_cents, enabled, last_tested_at, last_test_ok, created_at, updated_at, role, max_active_runs
`

type UpdateSourceParams struct {
	Name           *string
	CostPer1kCents *int32
	Enabled        *bool
	MaxActiveRuns  *int32
	SetKey         bool
	ApiKeyEnc      []byte
	ID             uuid.UUID
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.Name,
		arg.CostPer1kCents,
		arg.Enabled,
		arg.MaxActiveRuns,
		arg.SetKey,
		arg.ApiKeyEnc,
		arg.ID,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.ApiKeyEnc,
		&i.CostPer1kCents,
		&i.Enabled,
		&i.LastTestedAt,
		&i.LastTestOk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.MaxActiveRuns,
	)
	return i, err
}
