// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stats.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const emailsPerJob = `-- name: EmailsPerJob :many
SELECT j.id, j.name, COALESCE(e.emails, 0)::bigint AS emails
FROM (SELECT id, name, created_at FROM jobs ORDER BY created_at DESC LIMIT $1) j
         LEFT JOIN LATERAL (
    SELECT count(*) AS emails
    FROM job_results jr
             JOIN business_emails be ON be.business_id = jr.business_id
    WHERE jr.job_id = j.id
    ) e ON true
ORDER BY j.created_at
`

type EmailsPerJobRow struct {
	ID     uuid.UUID
	Name   string
	Emails int64
}

func (q *Queries) EmailsPerJob(ctx context.Context, lim int32) ([]EmailsPerJobRow, error) {
	rows, err := q.db.Query(ctx, emailsPerJob, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailsPerJobRow{}
	for rows.Next() {
		var i EmailsPerJobRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Emails); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scraperCounters = `-- name: ScraperCounters :one
SELECT (SELECT count(*) FROM businesses WHERE NOT suppressed)::bigint            AS businesses,
       (SELECT count(DISTINCT business_id) FROM business_emails)::bigint         AS with_email,
       (SELECT count(*) FROM business_emails)::bigint                            AS emails_total,
       (SELECT count(*) FROM jobs)::bigint                                       AS jobs_total
`

type ScraperCountersRow struct {
	Businesses  int64
	WithEmail   int64
	EmailsTotal int64
	JobsTotal   int64
}

func (q *Queries) ScraperCounters(ctx context.Context) (ScraperCountersRow, error) {
	row := q.db.QueryRow(ctx, scraperCounters)
	var i ScraperCountersRow
	err := row.Scan(
		&i.Businesses,
		&i.WithEmail,
		&i.EmailsTotal,
		&i.JobsTotal,
	)
	return i, err
}
