// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: variant_assignments.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const countAssignmentsByVariant = `-- name: CountAssignmentsByVariant :many
SELECT va.variant_id, va.step, count(*)::bigint AS total
FROM variant_assignments va
JOIN campaign_leads cl ON cl.id = va.campaign_lead_id
WHERE cl.campaign_id = $1
GROUP BY va.variant_id, va.step
`

type CountAssignmentsByVariantRow struct {
	VariantID uuid.UUID
	Step      int32
	Total     int64
}

func (q *Queries) CountAssignmentsByVariant(ctx context.Context, campaignID uuid.UUID) ([]CountAssignmentsByVariantRow, error) {
	rows, err := q.db.Query(ctx, countAssignmentsByVariant, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAssignmentsByVariantRow{}
	for rows.Next() {
		var i CountAssignmentsByVariantRow
		if err := rows.Scan(&i.VariantID, &i.Step, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLockedAssignmentsForCampaign = `-- name: CountLockedAssignmentsForCampaign :one
SELECT count(*) FROM variant_assignments va
JOIN campaign_leads cl ON cl.id = va.campaign_lead_id
WHERE cl.campaign_id = $1 AND va.locked_at IS NOT NULL
`

func (q *Queries) CountLockedAssignmentsForCampaign(ctx context.Context, campaignID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLockedAssignmentsForCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLockedAssignmentsForCampaignVariant = `-- name: CountLockedAssignmentsForCampaignVariant :one
SELECT count(*) FROM variant_assignments va
JOIN campaign_leads cl ON cl.id = va.campaign_lead_id
WHERE cl.campaign_id = $1 AND va.variant_id = $2 AND va.locked_at IS NOT NULL
`

type CountLockedAssignmentsForCampaignVariantParams struct {
	CampaignID uuid.UUID
	VariantID  uuid.UUID
}

func (q *Queries) CountLockedAssignmentsForCampaignVariant(ctx context.Context, arg CountLockedAssignmentsForCampaignVariantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLockedAssignmentsForCampaignVariant, arg.CampaignID, arg.VariantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVariantAssignment = `-- name: CreateVariantAssignment :one
INSERT INTO variant_assignments (id, campaign_lead_id, step, variant_id, weights_version, seed_hash, rendered_subject,
                                 rendered_body, component_ids, subject_component_id, hook_component_id, cta_component_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11, $12)
ON CONFLICT (campaign_lead_id, step) DO UPDATE SET assigned_at = variant_assignments.assigned_at
RETURNING id, campaign_lead_id, step, variant_id, weights_version, seed_hash, rendered_subject, rendered_body, component_ids, subject_component_id, hook_component_id, cta_component_id, assigned_at, locked_at
`

type CreateVariantAssignmentParams struct {
	ID                 uuid.UUID
	CampaignLeadID     uuid.UUID
	Step               int32
	VariantID          uuid.UUID
	WeightsVersion     int32
	SeedHash           string
	RenderedSubject    string
	RenderedBody       string
	ComponentIds       []uuid.UUID
	SubjectComponentID uuid.NullUUID
	HookComponentID    uuid.NullUUID
	CtaComponentID     uuid.NullUUID
}

func (q *Queries) CreateVariantAssignment(ctx context.Context, arg CreateVariantAssignmentParams) (VariantAssignment, error) {
	row := q.db.QueryRow(ctx, createVariantAssignment,
		arg.ID,
		arg.CampaignLeadID,
		arg.Step,
		arg.VariantID,
		arg.WeightsVersion,
		arg.SeedHash,
		arg.RenderedSubject,
		arg.RenderedBody,
		arg.ComponentIds,
		arg.SubjectComponentID,
		arg.HookComponentID,
		arg.CtaComponentID,
	)
	var i VariantAssignment
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.Step,
		&i.VariantID,
		&i.WeightsVersion,
		&i.SeedHash,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.ComponentIds,
		&i.SubjectComponentID,
		&i.HookComponentID,
		&i.CtaComponentID,
		&i.AssignedAt,
		&i.LockedAt,
	)
	return i, err
}

const deleteUnlockedAssignmentsForLead = `-- name: DeleteUnlockedAssignmentsForLead :exec
DELETE FROM variant_assignments WHERE campaign_lead_id = $1 AND locked_at IS NULL
`

func (q *Queries) DeleteUnlockedAssignmentsForLead(ctx context.Context, campaignLeadID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnlockedAssignmentsForLead, campaignLeadID)
	return err
}

const getVariantAssignment = `-- name: GetVariantAssignment :one
SELECT id, campaign_lead_id, step, variant_id, weights_version, seed_hash, rendered_subject, rendered_body, component_ids, subject_component_id, hook_component_id, cta_component_id, assigned_at, locked_at FROM variant_assignments WHERE campaign_lead_id = $1 AND step = $2
`

type GetVariantAssignmentParams struct {
	CampaignLeadID uuid.UUID
	Step           int32
}

func (q *Queries) GetVariantAssignment(ctx context.Context, arg GetVariantAssignmentParams) (VariantAssignment, error) {
	row := q.db.QueryRow(ctx, getVariantAssignment, arg.CampaignLeadID, arg.Step)
	var i VariantAssignment
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.Step,
		&i.VariantID,
		&i.WeightsVersion,
		&i.SeedHash,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.ComponentIds,
		&i.SubjectComponentID,
		&i.HookComponentID,
		&i.CtaComponentID,
		&i.AssignedAt,
		&i.LockedAt,
	)
	return i, err
}

const getVariantAssignmentByID = `-- name: GetVariantAssignmentByID :one
SELECT id, campaign_lead_id, step, variant_id, weights_version, seed_hash, rendered_subject, rendered_body, component_ids, subject_component_id, hook_component_id, cta_component_id, assigned_at, locked_at FROM variant_assignments WHERE id = $1
`

func (q *Queries) GetVariantAssignmentByID(ctx context.Context, id uuid.UUID) (VariantAssignment, error) {
	row := q.db.QueryRow(ctx, getVariantAssignmentByID, id)
	var i VariantAssignment
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.Step,
		&i.VariantID,
		&i.WeightsVersion,
		&i.SeedHash,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.ComponentIds,
		&i.SubjectComponentID,
		&i.HookComponentID,
		&i.CtaComponentID,
		&i.AssignedAt,
		&i.LockedAt,
	)
	return i, err
}

const listVariantAssignmentsForLead = `-- name: ListVariantAssignmentsForLead :many
SELECT id, campaign_lead_id, step, variant_id, weights_version, seed_hash, rendered_subject, rendered_body, component_ids, subject_component_id, hook_component_id, cta_component_id, assigned_at, locked_at FROM variant_assignments WHERE campaign_lead_id = $1 ORDER BY step
`

func (q *Queries) ListVariantAssignmentsForLead(ctx context.Context, campaignLeadID uuid.UUID) ([]VariantAssignment, error) {
	rows, err := q.db.Query(ctx, listVariantAssignmentsForLead, campaignLeadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantAssignment{}
	for rows.Next() {
		var i VariantAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CampaignLeadID,
			&i.Step,
			&i.VariantID,
			&i.WeightsVersion,
			&i.SeedHash,
			&i.RenderedSubject,
			&i.RenderedBody,
			&i.ComponentIds,
			&i.SubjectComponentID,
			&i.HookComponentID,
			&i.CtaComponentID,
			&i.AssignedAt,
			&i.LockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVariantAssignments = `-- name: LockVariantAssignments :exec
UPDATE variant_assignments SET locked_at = now() WHERE campaign_lead_id = $1 AND locked_at IS NULL
`

func (q *Queries) LockVariantAssignments(ctx context.Context, campaignLeadID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockVariantAssignments, campaignLeadID)
	return err
}
