// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verification_domains.sql

package dbgen

import (
	"context"
	"time"
)

const getVerificationDomain = `-- name: GetVerificationDomain :one
SELECT domain, has_mx, has_a, has_spf, has_dmarc, mx_hosts, registered_at, rdap_checked_at, dns_checked_at FROM verification_domains WHERE domain = $1
`

func (q *Queries) GetVerificationDomain(ctx context.Context, domain string) (VerificationDomain, error) {
	row := q.db.QueryRow(ctx, getVerificationDomain, domain)
	var i VerificationDomain
	err := row.Scan(
		&i.Domain,
		&i.HasMx,
		&i.HasA,
		&i.HasSpf,
		&i.HasDmarc,
		&i.MxHosts,
		&i.RegisteredAt,
		&i.RdapCheckedAt,
		&i.DnsCheckedAt,
	)
	return i, err
}

const upsertVerificationDNS = `-- name: UpsertVerificationDNS :one
INSERT INTO verification_domains (domain, has_mx, has_a, has_spf, has_dmarc, mx_hosts,
                                  dns_checked_at)
VALUES ($1, $2, $3, $4,
        $5, $6, now())
ON CONFLICT (domain) DO UPDATE
    SET has_mx         = EXCLUDED.has_mx,
        has_a          = EXCLUDED.has_a,
        has_spf        = EXCLUDED.has_spf,
        has_dmarc      = EXCLUDED.has_dmarc,
        mx_hosts       = EXCLUDED.mx_hosts,
        dns_checked_at = now()
RETURNING domain, has_mx, has_a, has_spf, has_dmarc, mx_hosts, registered_at, rdap_checked_at, dns_checked_at
`

type UpsertVerificationDNSParams struct {
	Domain   string
	HasMx    bool
	HasA     bool
	HasSpf   bool
	HasDmarc bool
	MxHosts  []string
}

func (q *Queries) UpsertVerificationDNS(ctx context.Context, arg UpsertVerificationDNSParams) (VerificationDomain, error) {
	row := q.db.QueryRow(ctx, upsertVerificationDNS,
		arg.Domain,
		arg.HasMx,
		arg.HasA,
		arg.HasSpf,
		arg.HasDmarc,
		arg.MxHosts,
	)
	var i VerificationDomain
	err := row.Scan(
		&i.Domain,
		&i.HasMx,
		&i.HasA,
		&i.HasSpf,
		&i.HasDmarc,
		&i.MxHosts,
		&i.RegisteredAt,
		&i.RdapCheckedAt,
		&i.DnsCheckedAt,
	)
	return i, err
}

const upsertVerificationRDAP = `-- name: UpsertVerificationRDAP :exec
INSERT INTO verification_domains (domain, registered_at, rdap_checked_at)
VALUES ($1, $2, now())
ON CONFLICT (domain) DO UPDATE
    SET registered_at   = EXCLUDED.registered_at,
        rdap_checked_at = now()
`

type UpsertVerificationRDAPParams struct {
	Domain       string
	RegisteredAt *time.Time
}

func (q *Queries) UpsertVerificationRDAP(ctx context.Context, arg UpsertVerificationRDAPParams) error {
	_, err := q.db.Exec(ctx, upsertVerificationRDAP, arg.Domain, arg.RegisteredAt)
	return err
}
