// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verification_runs.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const cancelPendingVerificationRunItems = `-- name: CancelPendingVerificationRunItems :exec
UPDATE verification_run_items
SET status = 'skipped', error = 'run cancelled', finished_at = now()
WHERE run_id = $1 AND status = 'queued'
`

func (q *Queries) CancelPendingVerificationRunItems(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelPendingVerificationRunItems, runID)
	return err
}

const cancelVerificationRun = `-- name: CancelVerificationRun :one
UPDATE verification_runs
SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id, pass, status, filter, total, done, failed, skipped, credits_used, est_cost_cents, source_id, error, created_at, started_at, finished_at, auto
`

func (q *Queries) CancelVerificationRun(ctx context.Context, id uuid.UUID) (VerificationRun, error) {
	row := q.db.QueryRow(ctx, cancelVerificationRun, id)
	var i VerificationRun
	err := row.Scan(
		&i.ID,
		&i.Pass,
		&i.Status,
		&i.Filter,
		&i.Total,
		&i.Done,
		&i.Failed,
		&i.Skipped,
		&i.CreditsUsed,
		&i.EstCostCents,
		&i.SourceID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Auto,
	)
	return i, err
}

const countActiveVerificationRuns = `-- name: CountActiveVerificationRuns :one
SELECT count(*) FROM verification_runs WHERE status IN ('queued', 'running')
`

func (q *Queries) CountActiveVerificationRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVerificationRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingVerificationRunItems = `-- name: CountPendingVerificationRunItems :one
SELECT count(*) FROM verification_run_items WHERE run_id = $1 AND status = 'queued'
`

func (q *Queries) CountPendingVerificationRunItems(ctx context.Context, runID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingVerificationRunItems, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentActiveRunsForPass = `-- name: CountRecentActiveRunsForPass :one
SELECT count(*) FROM verification_runs
WHERE pass = $1
  AND status IN ('queued', 'running')
  AND created_at > $2
`

type CountRecentActiveRunsForPassParams struct {
	Pass  string
	Since time.Time
}

// What the auto sweep waits on. Only runs created inside the window count, so a run
// that wedged mid-flight cannot switch automatic verification off for good.
func (q *Queries) CountRecentActiveRunsForPass(ctx context.Context, arg CountRecentActiveRunsForPassParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentActiveRunsForPass, arg.Pass, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVerificationRuns = `-- name: CountVerificationRuns :one
SELECT count(*) FROM verification_runs
WHERE ($1::text IS NULL OR pass = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
`

type CountVerificationRunsParams struct {
	Pass   *string
	Status *string
}

func (q *Queries) CountVerificationRuns(ctx context.Context, arg CountVerificationRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVerificationRuns, arg.Pass, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVerificationRun = `-- name: CreateVerificationRun :one
INSERT INTO verification_runs (id, pass, filter, est_cost_cents, source_id, auto)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, pass, status, filter, total, done, failed, skipped, credits_used, est_cost_cents, source_id, error, created_at, started_at, finished_at, auto
`

type CreateVerificationRunParams struct {
	ID           uuid.UUID
	Pass         string
	Filter       []byte
	EstCostCents int64
	SourceID     uuid.NullUUID
	Auto         bool
}

func (q *Queries) CreateVerificationRun(ctx context.Context, arg CreateVerificationRunParams) (VerificationRun, error) {
	row := q.db.QueryRow(ctx, createVerificationRun,
		arg.ID,
		arg.Pass,
		arg.Filter,
		arg.EstCostCents,
		arg.SourceID,
		arg.Auto,
	)
	var i VerificationRun
	err := row.Scan(
		&i.ID,
		&i.Pass,
		&i.Status,
		&i.Filter,
		&i.Total,
		&i.Done,
		&i.Failed,
		&i.Skipped,
		&i.CreditsUsed,
		&i.EstCostCents,
		&i.SourceID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Auto,
	)
	return i, err
}

const getVerificationRun = `-- name: GetVerificationRun :one
SELECT id, pass, status, filter, total, done, failed, skipped, credits_used, est_cost_cents, source_id, error, created_at, started_at, finished_at, auto FROM verification_runs WHERE id = $1
`

func (q *Queries) GetVerificationRun(ctx context.Context, id uuid.UUID) (VerificationRun, error) {
	row := q.db.QueryRow(ctx, getVerificationRun, id)
	var i VerificationRun
	err := row.Scan(
		&i.ID,
		&i.Pass,
		&i.Status,
		&i.Filter,
		&i.Total,
		&i.Done,
		&i.Failed,
		&i.Skipped,
		&i.CreditsUsed,
		&i.EstCostCents,
		&i.SourceID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Auto,
	)
	return i, err
}

const insertVerificationRunItems = `-- name: InsertVerificationRunItems :execrows
INSERT INTO verification_run_items (run_id, verification_id)
SELECT $1::uuid, unnest($2::uuid[])
ON CONFLICT (run_id, verification_id) DO NOTHING
`

type InsertVerificationRunItemsParams struct {
	RunID           uuid.UUID
	VerificationIds []uuid.UUID
}

func (q *Queries) InsertVerificationRunItems(ctx context.Context, arg InsertVerificationRunItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVerificationRunItems, arg.RunID, arg.VerificationIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lastFinishedVerificationRun = `-- name: LastFinishedVerificationRun :one
SELECT id, pass, status, filter, total, done, failed, skipped, credits_used, est_cost_cents, source_id, error, created_at, started_at, finished_at, auto FROM verification_runs
WHERE pass = $1 AND finished_at IS NOT NULL
ORDER BY finished_at DESC
LIMIT 1
`

func (q *Queries) LastFinishedVerificationRun(ctx context.Context, pass string) (VerificationRun, error) {
	row := q.db.QueryRow(ctx, lastFinishedVerificationRun, pass)
	var i VerificationRun
	err := row.Scan(
		&i.ID,
		&i.Pass,
		&i.Status,
		&i.Filter,
		&i.Total,
		&i.Done,
		&i.Failed,
		&i.Skipped,
		&i.CreditsUsed,
		&i.EstCostCents,
		&i.SourceID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Auto,
	)
	return i, err
}

const listQueuedVerificationRunItems = `-- name: ListQueuedVerificationRunItems :many
SELECT verification_id FROM verification_run_items
WHERE run_id = $1 AND status = 'queued'
ORDER BY verification_id
`

func (q *Queries) ListQueuedVerificationRunItems(ctx context.Context, runID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listQueuedVerificationRunItems, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var verification_id uuid.UUID
		if err := rows.Scan(&verification_id); err != nil {
			return nil, err
		}
		items = append(items, verification_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationRuns = `-- name: ListVerificationRuns :many
SELECT id, pass, status, filter, total, done, failed, skipped, credits_used, est_cost_cents, source_id, error, created_at, started_at, finished_at, auto FROM verification_runs
WHERE ($1::text IS NULL OR pass = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListVerificationRunsParams struct {
	Pass   *string
	Status *string
	Off    int32
	Lim    int32
}

func (q *Queries) ListVerificationRuns(ctx context.Context, arg ListVerificationRunsParams) ([]VerificationRun, error) {
	rows, err := q.db.Query(ctx, listVerificationRuns,
		arg.Pass,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationRun{}
	for rows.Next() {
		var i VerificationRun
		if err := rows.Scan(
			&i.ID,
			&i.Pass,
			&i.Status,
			&i.Filter,
			&i.Total,
			&i.Done,
			&i.Failed,
			&i.Skipped,
			&i.CreditsUsed,
			&i.EstCostCents,
			&i.SourceID,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Auto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVerificationRunItem = `-- name: MarkVerificationRunItem :exec
UPDATE verification_run_items
SET status      = $1,
    error       = $2,
    credits     = $3,
    finished_at = now()
WHERE run_id = $4 AND verification_id = $5
`

type MarkVerificationRunItemParams struct {
	Status         string
	Error          *string
	Credits        int32
	RunID          uuid.UUID
	VerificationID uuid.UUID
}

func (q *Queries) MarkVerificationRunItem(ctx context.Context, arg MarkVerificationRunItemParams) error {
	_, err := q.db.Exec(ctx, markVerificationRunItem,
		arg.Status,
		arg.Error,
		arg.Credits,
		arg.RunID,
		arg.VerificationID,
	)
	return err
}

const markVerificationRunRunning = `-- name: MarkVerificationRunRunning :exec
UPDATE verification_runs
SET status = 'running', started_at = COALESCE(started_at, now())
WHERE id = $1 AND status = 'queued'
`

func (q *Queries) MarkVerificationRunRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markVerificationRunRunning, id)
	return err
}

const markVerificationRunTerminal = `-- name: MarkVerificationRunTerminal :exec
UPDATE verification_runs
SET status = $1, error = $2, finished_at = now()
WHERE id = $3 AND status IN ('queued', 'running')
`

type MarkVerificationRunTerminalParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) MarkVerificationRunTerminal(ctx context.Context, arg MarkVerificationRunTerminalParams) error {
	_, err := q.db.Exec(ctx, markVerificationRunTerminal, arg.Status, arg.Error, arg.ID)
	return err
}

const recomputeVerificationRunStats = `-- name: RecomputeVerificationRunStats :one
UPDATE verification_runs r
SET done         = counted.done,
    failed       = counted.failed,
    skipped      = counted.skipped,
    credits_used = counted.credits
FROM (SELECT count(*) FILTER (WHERE status = 'done')::int    AS done,
             count(*) FILTER (WHERE status = 'failed')::int  AS failed,
             count(*) FILTER (WHERE status = 'skipped')::int AS skipped,
             COALESCE(sum(credits), 0)::int                  AS credits
      FROM verification_run_items
      WHERE run_id = $1) counted
WHERE r.id = $1
RETURNING r.id, r.pass, r.status, r.filter, r.total, r.done, r.failed, r.skipped, r.credits_used, r.est_cost_cents, r.source_id, r.error, r.created_at, r.started_at, r.finished_at, r.auto
`

func (q *Queries) RecomputeVerificationRunStats(ctx context.Context, id uuid.UUID) (VerificationRun, error) {
	row := q.db.QueryRow(ctx, recomputeVerificationRunStats, id)
	var i VerificationRun
	err := row.Scan(
		&i.ID,
		&i.Pass,
		&i.Status,
		&i.Filter,
		&i.Total,
		&i.Done,
		&i.Failed,
		&i.Skipped,
		&i.CreditsUsed,
		&i.EstCostCents,
		&i.SourceID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Auto,
	)
	return i, err
}

const setVerificationRunTotal = `-- name: SetVerificationRunTotal :exec
UPDATE verification_runs SET total = $1 WHERE id = $2
`

type SetVerificationRunTotalParams struct {
	Total int32
	ID    uuid.UUID
}

func (q *Queries) SetVerificationRunTotal(ctx context.Context, arg SetVerificationRunTotalParams) error {
	_, err := q.db.Exec(ctx, setVerificationRunTotal, arg.Total, arg.ID)
	return err
}
