// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verification_stats.sql

package dbgen

import (
	"context"
)

const countEmailsNeedingSelfVerification = `-- name: CountEmailsNeedingSelfVerification :one
SELECT count(DISTINCT be.email)::bigint
FROM business_emails be
         LEFT JOIN email_verifications ev ON ev.email = be.email
WHERE (ev.id IS NULL OR ev.free_scored_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM global_excluded_addresses x WHERE x.email = be.email)
`

// Addresses on the master list that have never been through the free stage, whether
// or not a verification row exists for them yet, leaving out globally excluded ones.
func (q *Queries) CountEmailsNeedingSelfVerification(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailsNeedingSelfVerification)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countQualifyingForThirdParty = `-- name: CountQualifyingForThirdParty :one
SELECT count(*)::bigint
FROM email_verifications ev
WHERE ev.free_scored_at IS NOT NULL
  AND ev.third_party_sent_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM global_excluded_addresses x WHERE x.email = ev.email)
  AND ev.free_score >= $1::int
  AND ev.free_score < $2::int
`

type CountQualifyingForThirdPartyParams struct {
	MinScore int32
	MaxScore int32
}

// Inside the paid band and never sent to a third party. The band has both a floor
// (below it an address is not worth paying for) and a ceiling (at or above it the
// free providers are already confident enough that paying adds nothing); the send
// lock is absolute and outranks both. A globally excluded address never qualifies.
func (q *Queries) CountQualifyingForThirdParty(ctx context.Context, arg CountQualifyingForThirdPartyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQualifyingForThirdParty, arg.MinScore, arg.MaxScore)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const verificationCounters = `-- name: VerificationCounters :one
SELECT (SELECT count(*) FROM email_verifications)::bigint                                          AS total,
       (SELECT count(*) FROM email_verifications WHERE verification_tag = 'green')::bigint         AS tag_green,
       (SELECT count(*) FROM email_verifications WHERE verification_tag = 'light_green')::bigint   AS tag_light_green,
       (SELECT count(*) FROM email_verifications WHERE verification_tag = 'yellow')::bigint        AS tag_yellow,
       (SELECT count(*) FROM email_verifications WHERE verification_tag = 'orange')::bigint        AS tag_orange,
       (SELECT count(*) FROM email_verifications WHERE verification_tag = 'red')::bigint           AS tag_red,
       (SELECT count(*) FROM email_verifications WHERE free_scored_at IS NOT NULL)::bigint         AS self_verified,
       (SELECT count(*) FROM email_verifications WHERE pass2_verified_at IS NOT NULL)::bigint      AS third_party_verified,
       (SELECT COALESCE(sum(pass2_credits), 0) FROM email_verifications)::bigint                   AS credits_used_total,
       (SELECT COALESCE(sum(credits_used), 0) FROM verification_runs
        WHERE created_at > now() - interval '30 days')::bigint                                     AS credits_used_30d
`

type VerificationCountersRow struct {
	Total              int64
	TagGreen           int64
	TagLightGreen      int64
	TagYellow          int64
	TagOrange          int64
	TagRed             int64
	SelfVerified       int64
	ThirdPartyVerified int64
	CreditsUsedTotal   int64
	CreditsUsed30d     int64
}

func (q *Queries) VerificationCounters(ctx context.Context) (VerificationCountersRow, error) {
	row := q.db.QueryRow(ctx, verificationCounters)
	var i VerificationCountersRow
	err := row.Scan(
		&i.Total,
		&i.TagGreen,
		&i.TagLightGreen,
		&i.TagYellow,
		&i.TagOrange,
		&i.TagRed,
		&i.SelfVerified,
		&i.ThirdPartyVerified,
		&i.CreditsUsedTotal,
		&i.CreditsUsed30d,
	)
	return i, err
}
