// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspace.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const connectInstantly = `-- name: ConnectInstantly :one
UPDATE workspace_mailboxes
SET instantly_status       = 'connected',
    instantly_account_id   = $1,
    instantly_connected_at = now(),
    instantly_error        = NULL,
    instantly_auth_url     = NULL,
    updated_at             = now()
WHERE id = $2 AND instantly_session_id = $3 AND instantly_status = 'connecting'
RETURNING id, domain_id, position, email, given_name, family_name, password_enc, status, create_attempts, google_user_id, error_code, error_message, provisioned_at, instantly_status, instantly_session_id, instantly_auth_url, instantly_session_expires_at, instantly_account_id, instantly_error, instantly_connected_at, instantly_warmup, instantly_warmup_enabled_at, created_at, updated_at
`

type ConnectInstantlyParams struct {
	AccountID *string
	ID        uuid.UUID
	SessionID *string
}

// The session id guards every outcome, so a session the operator has since replaced
// cannot overwrite the new one.
func (q *Queries) ConnectInstantly(ctx context.Context, arg ConnectInstantlyParams) (WorkspaceMailbox, error) {
	row := q.db.QueryRow(ctx, connectInstantly, arg.AccountID, arg.ID, arg.SessionID)
	var i WorkspaceMailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Position,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.PasswordEnc,
		&i.Status,
		&i.CreateAttempts,
		&i.GoogleUserID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ProvisionedAt,
		&i.InstantlyStatus,
		&i.InstantlySessionID,
		&i.InstantlyAuthUrl,
		&i.InstantlySessionExpiresAt,
		&i.InstantlyAccountID,
		&i.InstantlyError,
		&i.InstantlyConnectedAt,
		&i.InstantlyWarmup,
		&i.InstantlyWarmupEnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countWorkspaceDomains = `-- name: CountWorkspaceDomains :one
SELECT count(*) FROM workspace_domains
`

func (q *Queries) CountWorkspaceDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceMailboxAttempt = `-- name: CountWorkspaceMailboxAttempt :one
UPDATE workspace_mailboxes
SET create_attempts = create_attempts + 1, updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, domain_id, position, email, given_name, family_name, password_enc, status, create_attempts, google_user_id, error_code, error_message, provisioned_at, instantly_status, instantly_session_id, instantly_auth_url, instantly_session_expires_at, instantly_account_id, instantly_error, instantly_connected_at, instantly_warmup, instantly_warmup_enabled_at, created_at, updated_at
`

// The attempt is counted before the billable call, so the next pass knows whether a
// "this address already exists" answer can be its own earlier call landing.
func (q *Queries) CountWorkspaceMailboxAttempt(ctx context.Context, id uuid.UUID) (WorkspaceMailbox, error) {
	row := q.db.QueryRow(ctx, countWorkspaceMailboxAttempt, id)
	var i WorkspaceMailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Position,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.PasswordEnc,
		&i.Status,
		&i.CreateAttempts,
		&i.GoogleUserID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ProvisionedAt,
		&i.InstantlyStatus,
		&i.InstantlySessionID,
		&i.InstantlyAuthUrl,
		&i.InstantlySessionExpiresAt,
		&i.InstantlyAccountID,
		&i.InstantlyError,
		&i.InstantlyConnectedAt,
		&i.InstantlyWarmup,
		&i.InstantlyWarmupEnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceDomain = `-- name: CreateWorkspaceDomain :one
INSERT INTO workspace_domains (id, domain_name)
VALUES ($1, $2)
RETURNING id, domain_name, status, verification_token, dkim_selector, added_at, dns_published_at, verified_at, dkim_published_at, error_code, error_message, created_at, updated_at
`

type CreateWorkspaceDomainParams struct {
	ID         uuid.UUID
	DomainName string
}

func (q *Queries) CreateWorkspaceDomain(ctx context.Context, arg CreateWorkspaceDomainParams) (WorkspaceDomain, error) {
	row := q.db.QueryRow(ctx, createWorkspaceDomain, arg.ID, arg.DomainName)
	var i WorkspaceDomain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.Status,
		&i.VerificationToken,
		&i.DkimSelector,
		&i.AddedAt,
		&i.DnsPublishedAt,
		&i.VerifiedAt,
		&i.DkimPublishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceMailbox = `-- name: CreateWorkspaceMailbox :one
INSERT INTO workspace_mailboxes (id, domain_id, position, email, given_name, family_name, password_enc)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, domain_id, position, email, given_name, family_name, password_enc, status, create_attempts, google_user_id, error_code, error_message, provisioned_at, instantly_status, instantly_session_id, instantly_auth_url, instantly_session_expires_at, instantly_account_id, instantly_error, instantly_connected_at, instantly_warmup, instantly_warmup_enabled_at, created_at, updated_at
`

type CreateWorkspaceMailboxParams struct {
	ID          uuid.UUID
	DomainID    uuid.UUID
	Position    int16
	Email       string
	GivenName   string
	FamilyName  string
	PasswordEnc []byte
}

func (q *Queries) CreateWorkspaceMailbox(ctx context.Context, arg CreateWorkspaceMailboxParams) (WorkspaceMailbox, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMailbox,
		arg.ID,
		arg.DomainID,
		arg.Position,
		arg.Email,
		arg.GivenName,
		arg.FamilyName,
		arg.PasswordEnc,
	)
	var i WorkspaceMailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Position,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.PasswordEnc,
		&i.Status,
		&i.CreateAttempts,
		&i.GoogleUserID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ProvisionedAt,
		&i.InstantlyStatus,
		&i.InstantlySessionID,
		&i.InstantlyAuthUrl,
		&i.InstantlySessionExpiresAt,
		&i.InstantlyAccountID,
		&i.InstantlyError,
		&i.InstantlyConnectedAt,
		&i.InstantlyWarmup,
		&i.InstantlyWarmupEnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFailedWorkspaceMailbox = `-- name: DeleteFailedWorkspaceMailbox :one
DELETE FROM workspace_mailboxes
WHERE id = $1 AND status = 'failed'
RETURNING id, domain_id, position, email, given_name, family_name, password_enc, status, create_attempts, google_user_id, error_code, error_message, provisioned_at, instantly_status, instantly_session_id, instantly_auth_url, instantly_session_expires_at, instantly_account_id, instantly_error, instantly_connected_at, instantly_warmup, instantly_warmup_enabled_at, created_at, updated_at
`

// Only a mailbox that was never created is just a record; removing it frees its slot.
func (q *Queries) DeleteFailedWorkspaceMailbox(ctx context.Context, id uuid.UUID) (WorkspaceMailbox, error) {
	row := q.db.QueryRow(ctx, deleteFailedWorkspaceMailbox, id)
	var i WorkspaceMailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Position,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.PasswordEnc,
		&i.Status,
		&i.CreateAttempts,
		&i.GoogleUserID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ProvisionedAt,
		&i.InstantlyStatus,
		&i.InstantlySessionID,
		&i.InstantlyAuthUrl,
		&i.InstantlySessionExpiresAt,
		&i.InstantlyAccountID,
		&i.InstantlyError,
		&i.InstantlyConnectedAt,
		&i.InstantlyWarmup,
		&i.InstantlyWarmupEnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endInstantlyConnection = `-- name: EndInstantlyConnection :exec
UPDATE workspace_mailboxes
SET instantly_status   = $1,
    instantly_error    = $2,
    instantly_auth_url = NULL,
    updated_at         = now()
WHERE id = $3 AND instantly_session_id = $4 AND instantly_status = 'connecting'
`

type EndInstantlyConnectionParams struct {
	Status    *string
	Error     *string
	ID        uuid.UUID
	SessionID *string
}

func (q *Queries) EndInstantlyConnection(ctx context.Context, arg EndInstantlyConnectionParams) error {
	_, err := q.db.Exec(ctx, endInstantlyConnection,
		arg.Status,
		arg.Error,
		arg.ID,
		arg.SessionID,
	)
	return err
}

const failWorkspaceDomain = `-- name: FailWorkspaceDomain :exec
UPDATE workspace_domains
SET status        = 'failed',
    error_code    = $1,
    error_message = $2,
    updated_at    = now()
WHERE id = $3 AND status = 'provisioning'
`

type FailWorkspaceDomainParams struct {
	ErrorCode    *string
	ErrorMessage *string
	ID           uuid.UUID
}

func (q *Queries) FailWorkspaceDomain(ctx context.Context, arg FailWorkspaceDomainParams) error {
	_, err := q.db.Exec(ctx, failWorkspaceDomain, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	return err
}

const failWorkspaceMailbox = `-- name: FailWorkspaceMailbox :exec
UPDATE workspace_mailboxes
SET status        = 'failed',
    error_code    = $1,
    error_message = $2,
    updated_at    = now()
WHERE id = $3 AND status = 'pending'
`

type FailWorkspaceMailboxParams struct {
	ErrorCode    *string
	ErrorMessage *string
	ID           uuid.UUID
}

func (q *Queries) FailWorkspaceMailbox(ctx context.Context, arg FailWorkspaceMailboxParams) error {
	_, err := q.db.Exec(ctx, failWorkspaceMailbox, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	return err
}

const finishWorkspaceProvisioning = `-- name: FinishWorkspaceProvisioning :one
UPDATE workspace_domains
SET status        = CASE WHEN dkim_published_at IS NULL THEN 'dkim_required' ELSE 'active' END,
    error_code    = NULL,
    error_message = NULL,
    updated_at    = now()
WHERE id = $1 AND status = 'provisioning'
RETURNING id, domain_name, status, verification_token, dkim_selector, added_at, dns_published_at, verified_at, dkim_published_at, error_code, error_message, created_at, updated_at
`

// The automatic steps are done. A domain whose DKIM record was already published (a
// retry after adding a mailbox failed) goes straight back to active.
func (q *Queries) FinishWorkspaceProvisioning(ctx context.Context, id uuid.UUID) (WorkspaceDomain, error) {
	row := q.db.QueryRow(ctx, finishWorkspaceProvisioning, id)
	var i WorkspaceDomain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.Status,
		&i.VerificationToken,
		&i.DkimSelector,
		&i.AddedAt,
		&i.DnsPublishedAt,
		&i.VerifiedAt,
		&i.DkimPublishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceDomain = `-- name: GetWorkspaceDomain :one
SELECT id, domain_name, status, verification_token, dkim_selector, added_at, dns_published_at, verified_at, dkim_published_at, error_code, error_message, created_at, updated_at FROM workspace_domains WHERE id = $1
`

func (q *Queries) GetWorkspaceDomain(ctx context.Context, id uuid.UUID) (WorkspaceDomain, error) {
	row := q.db.QueryRow(ctx, getWorkspaceDomain, id)
	var i WorkspaceDomain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.Status,
		&i.VerificationToken,
		&i.DkimSelector,
		&i.AddedAt,
		&i.DnsPublishedAt,
		&i.VerifiedAt,
		&i.DkimPublishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceDomainByName = `-- name: GetWorkspaceDomainByName :one
SELECT id, domain_name, status, verification_token, dkim_selector, added_at, dns_published_at, verified_at, dkim_published_at, error_code, error_message, created_at, updated_at FROM workspace_domains WHERE domain_name = $1
`

func (q *Queries) GetWorkspaceDomainByName(ctx context.Context, domainName string) (WorkspaceDomain, error) {
	row := q.db.QueryRow(ctx, getWorkspaceDomainByName, domainName)
	var i WorkspaceDomain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.Status,
		&i.VerificationToken,
		&i.DkimSelector,
		&i.AddedAt,
		&i.DnsPublishedAt,
		&i.VerifiedAt,
		&i.DkimPublishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMailbox = `-- name: GetWorkspaceMailbox :one
SELECT id, domain_id, position, email, given_name, family_name, password_enc, status, create_attempts, google_user_id, error_code, error_message, provisioned_at, instantly_status, instantly_session_id, instantly_auth_url, instantly_session_expires_at, instantly_account_id, instantly_error, instantly_connected_at, instantly_warmup, instantly_warmup_enabled_at, created_at, updated_at FROM workspace_mailboxes WHERE id = $1
`

func (q *Queries) GetWorkspaceMailbox(ctx context.Context, id uuid.UUID) (WorkspaceMailbox, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMailbox, id)
	var i WorkspaceMailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Position,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.PasswordEnc,
		&i.Status,
		&i.CreateAttempts,
		&i.GoogleUserID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ProvisionedAt,
		&i.InstantlyStatus,
		&i.InstantlySessionID,
		&i.InstantlyAuthUrl,
		&i.InstantlySessionExpiresAt,
		&i.InstantlyAccountID,
		&i.InstantlyError,
		&i.InstantlyConnectedAt,
		&i.InstantlyWarmup,
		&i.InstantlyWarmupEnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceSettings = `-- name: GetWorkspaceSettings :one
SELECT id, admin_email, service_account_email, service_account_client_id, updated_at FROM workspace_settings WHERE id = 1
`

func (q *Queries) GetWorkspaceSettings(ctx context.Context) (WorkspaceSetting, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSettings)
	var i WorkspaceSetting
	err := row.Scan(
		&i.ID,
		&i.AdminEmail,
		&i.ServiceAccountEmail,
		&i.ServiceAccountClientID,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceDomains = `-- name: ListWorkspaceDomains :many
SELECT id, domain_name, status, verification_token, dkim_selector, added_at, dns_published_at, verified_at, dkim_published_at, error_code, error_message, created_at, updated_at FROM workspace_domains
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListWorkspaceDomainsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListWorkspaceDomains(ctx context.Context, arg ListWorkspaceDomainsParams) ([]WorkspaceDomain, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDomains, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceDomain{}
	for rows.Next() {
		var i WorkspaceDomain
		if err := rows.Scan(
			&i.ID,
			&i.DomainName,
			&i.Status,
			&i.VerificationToken,
			&i.DkimSelector,
			&i.AddedAt,
			&i.DnsPublishedAt,
			&i.VerifiedAt,
			&i.DkimPublishedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMailboxes = `-- name: ListWorkspaceMailboxes :many
SELECT id, domain_id, position, email, given_name, family_name, password_enc, status, create_attempts, google_user_id, error_code, error_message, provisioned_at, instantly_status, instantly_session_id, instantly_auth_url, instantly_session_expires_at, instantly_account_id, instantly_error, instantly_connected_at, instantly_warmup, instantly_warmup_enabled_at, created_at, updated_at FROM workspace_mailboxes WHERE domain_id = $1 ORDER BY position
`

func (q *Queries) ListWorkspaceMailboxes(ctx context.Context, domainID uuid.UUID) ([]WorkspaceMailbox, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMailboxes, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceMailbox{}
	for rows.Next() {
		var i WorkspaceMailbox
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Position,
			&i.Email,
			&i.GivenName,
			&i.FamilyName,
			&i.PasswordEnc,
			&i.Status,
			&i.CreateAttempts,
			&i.GoogleUserID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ProvisionedAt,
			&i.InstantlyStatus,
			&i.InstantlySessionID,
			&i.InstantlyAuthUrl,
			&i.InstantlySessionExpiresAt,
			&i.InstantlyAccountID,
			&i.InstantlyError,
			&i.InstantlyConnectedAt,
			&i.InstantlyWarmup,
			&i.InstantlyWarmupEnabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMailboxesFor = `-- name: ListWorkspaceMailboxesFor :many
SELECT id, domain_id, position, email, given_name, family_name, password_enc, status, create_attempts, google_user_id, error_code, error_message, provisioned_at, instantly_status, instantly_session_id, instantly_auth_url, instantly_session_expires_at, instantly_account_id, instantly_error, instantly_connected_at, instantly_warmup, instantly_warmup_enabled_at, created_at, updated_at FROM workspace_mailboxes
WHERE domain_id = ANY($1::uuid[])
ORDER BY domain_id, position
`

func (q *Queries) ListWorkspaceMailboxesFor(ctx context.Context, domainIds []uuid.UUID) ([]WorkspaceMailbox, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMailboxesFor, domainIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceMailbox{}
	for rows.Next() {
		var i WorkspaceMailbox
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Position,
			&i.Email,
			&i.GivenName,
			&i.FamilyName,
			&i.PasswordEnc,
			&i.Status,
			&i.CreateAttempts,
			&i.GoogleUserID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ProvisionedAt,
			&i.InstantlyStatus,
			&i.InstantlySessionID,
			&i.InstantlyAuthUrl,
			&i.InstantlySessionExpiresAt,
			&i.InstantlyAccountID,
			&i.InstantlyError,
			&i.InstantlyConnectedAt,
			&i.InstantlyWarmup,
			&i.InstantlyWarmupEnabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkspaceDNSPublished = `-- name: MarkWorkspaceDNSPublished :exec
UPDATE workspace_domains
SET dns_published_at = COALESCE(dns_published_at, now()), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkWorkspaceDNSPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWorkspaceDNSPublished, id)
	return err
}

const markWorkspaceDomainAdded = `-- name: MarkWorkspaceDomainAdded :exec
UPDATE workspace_domains
SET added_at = COALESCE(added_at, now()), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkWorkspaceDomainAdded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWorkspaceDomainAdded, id)
	return err
}

const markWorkspaceDomainVerified = `-- name: MarkWorkspaceDomainVerified :exec
UPDATE workspace_domains
SET verified_at = COALESCE(verified_at, now()), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkWorkspaceDomainVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWorkspaceDomainVerified, id)
	return err
}

const publishWorkspaceDKIM = `-- name: PublishWorkspaceDKIM :one
UPDATE workspace_domains
SET status            = 'active',
    dkim_selector     = $1,
    dkim_published_at = now(),
    updated_at        = now()
WHERE id = $2 AND status IN ('dkim_required', 'active')
RETURNING id, domain_name, status, verification_token, dkim_selector, added_at, dns_published_at, verified_at, dkim_published_at, error_code, error_message, created_at, updated_at
`

type PublishWorkspaceDKIMParams struct {
	DkimSelector *string
	ID           uuid.UUID
}

func (q *Queries) PublishWorkspaceDKIM(ctx context.Context, arg PublishWorkspaceDKIMParams) (WorkspaceDomain, error) {
	row := q.db.QueryRow(ctx, publishWorkspaceDKIM, arg.DkimSelector, arg.ID)
	var i WorkspaceDomain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.Status,
		&i.VerificationToken,
		&i.DkimSelector,
		&i.AddedAt,
		&i.DnsPublishedAt,
		&i.VerifiedAt,
		&i.DkimPublishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reopenWorkspaceDomain = `-- name: ReopenWorkspaceDomain :one
UPDATE workspace_domains
SET status = 'provisioning', error_code = NULL, error_message = NULL, updated_at = now()
WHERE id = $1 AND status IN ('dkim_required', 'active')
RETURNING id, domain_name, status, verification_token, dkim_selector, added_at, dns_published_at, verified_at, dkim_published_at, error_code, error_message, created_at, updated_at
`

// A domain that is set up takes more mailboxes by going back to provisioning; the
// worker skips every finished step and creates the new ones.
func (q *Queries) ReopenWorkspaceDomain(ctx context.Context, id uuid.UUID) (WorkspaceDomain, error) {
	row := q.db.QueryRow(ctx, reopenWorkspaceDomain, id)
	var i WorkspaceDomain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.Status,
		&i.VerificationToken,
		&i.DkimSelector,
		&i.AddedAt,
		&i.DnsPublishedAt,
		&i.VerifiedAt,
		&i.DkimPublishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetFailedWorkspaceMailboxes = `-- name: ResetFailedWorkspaceMailboxes :exec
UPDATE workspace_mailboxes
SET status = 'pending', create_attempts = 0, error_code = NULL, error_message = NULL, updated_at = now()
WHERE domain_id = $1 AND status = 'failed' AND error_code IS DISTINCT FROM 'address_taken'
`

// A retry sends refused mailboxes again. An address that belonged to someone else is
// left failed: sending it again would count it as ours.
func (q *Queries) ResetFailedWorkspaceMailboxes(ctx context.Context, domainID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedWorkspaceMailboxes, domainID)
	return err
}

const retryWorkspaceDomain = `-- name: RetryWorkspaceDomain :one
UPDATE workspace_domains
SET status = 'provisioning', error_code = NULL, error_message = NULL, updated_at = now()
WHERE id = $1 AND status = 'failed'
RETURNING id, domain_name, status, verification_token, dkim_selector, added_at, dns_published_at, verified_at, dkim_published_at, error_code, error_message, created_at, updated_at
`

func (q *Queries) RetryWorkspaceDomain(ctx context.Context, id uuid.UUID) (WorkspaceDomain, error) {
	row := q.db.QueryRow(ctx, retryWorkspaceDomain, id)
	var i WorkspaceDomain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.Status,
		&i.VerificationToken,
		&i.DkimSelector,
		&i.AddedAt,
		&i.DnsPublishedAt,
		&i.VerifiedAt,
		&i.DkimPublishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setInstantlyWarmupResult = `-- name: SetInstantlyWarmupResult :exec
UPDATE workspace_mailboxes
SET instantly_warmup_enabled_at = $1,
    instantly_error             = $2,
    updated_at                  = now()
WHERE id = $3 AND instantly_status = 'connected'
`

type SetInstantlyWarmupResultParams struct {
	EnabledAt *time.Time
	Error     *string
	ID        uuid.UUID
}

func (q *Queries) SetInstantlyWarmupResult(ctx context.Context, arg SetInstantlyWarmupResultParams) error {
	_, err := q.db.Exec(ctx, setInstantlyWarmupResult, arg.EnabledAt, arg.Error, arg.ID)
	return err
}

const setWorkspaceAdminEmail = `-- name: SetWorkspaceAdminEmail :one
UPDATE workspace_settings
SET admin_email = $1,
    updated_at  = now()
WHERE id = 1
RETURNING id, admin_email, service_account_email, service_account_client_id, updated_at
`

func (q *Queries) SetWorkspaceAdminEmail(ctx context.Context, adminEmail *string) (WorkspaceSetting, error) {
	row := q.db.QueryRow(ctx, setWorkspaceAdminEmail, adminEmail)
	var i WorkspaceSetting
	err := row.Scan(
		&i.ID,
		&i.AdminEmail,
		&i.ServiceAccountEmail,
		&i.ServiceAccountClientID,
		&i.UpdatedAt,
	)
	return i, err
}

const setWorkspaceServiceAccount = `-- name: SetWorkspaceServiceAccount :one
UPDATE workspace_settings
SET service_account_email     = $1,
    service_account_client_id = $2,
    updated_at                = now()
WHERE id = 1
RETURNING id, admin_email, service_account_email, service_account_client_id, updated_at
`

type SetWorkspaceServiceAccountParams struct {
	ServiceAccountEmail    *string
	ServiceAccountClientID *string
}

func (q *Queries) SetWorkspaceServiceAccount(ctx context.Context, arg SetWorkspaceServiceAccountParams) (WorkspaceSetting, error) {
	row := q.db.QueryRow(ctx, setWorkspaceServiceAccount, arg.ServiceAccountEmail, arg.ServiceAccountClientID)
	var i WorkspaceSetting
	err := row.Scan(
		&i.ID,
		&i.AdminEmail,
		&i.ServiceAccountEmail,
		&i.ServiceAccountClientID,
		&i.UpdatedAt,
	)
	return i, err
}

const setWorkspaceVerificationToken = `-- name: SetWorkspaceVerificationToken :exec
UPDATE workspace_domains
SET verification_token = $2, updated_at = now()
WHERE id = $1
`

type SetWorkspaceVerificationTokenParams struct {
	ID                uuid.UUID
	VerificationToken *string
}

func (q *Queries) SetWorkspaceVerificationToken(ctx context.Context, arg SetWorkspaceVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setWorkspaceVerificationToken, arg.ID, arg.VerificationToken)
	return err
}

const startInstantlyConnection = `-- name: StartInstantlyConnection :one
UPDATE workspace_mailboxes
SET instantly_status             = 'connecting',
    instantly_session_id         = $1,
    instantly_auth_url           = $2,
    instantly_session_expires_at = $3,
    instantly_warmup             = $4,
    instantly_error              = NULL,
    updated_at                   = now()
WHERE id = $5 AND status = 'created'
  AND instantly_status IS DISTINCT FROM 'connected'
RETURNING id, domain_id, position, email, given_name, family_name, password_enc, status, create_attempts, google_user_id, error_code, error_message, provisioned_at, instantly_status, instantly_session_id, instantly_auth_url, instantly_session_expires_at, instantly_account_id, instantly_error, instantly_connected_at, instantly_warmup, instantly_warmup_enabled_at, created_at, updated_at
`

type StartInstantlyConnectionParams struct {
	SessionID *string
	AuthUrl   *string
	ExpiresAt *time.Time
	Warmup    bool
	ID        uuid.UUID
}

func (q *Queries) StartInstantlyConnection(ctx context.Context, arg StartInstantlyConnectionParams) (WorkspaceMailbox, error) {
	row := q.db.QueryRow(ctx, startInstantlyConnection,
		arg.SessionID,
		arg.AuthUrl,
		arg.ExpiresAt,
		arg.Warmup,
		arg.ID,
	)
	var i WorkspaceMailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Position,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.PasswordEnc,
		&i.Status,
		&i.CreateAttempts,
		&i.GoogleUserID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ProvisionedAt,
		&i.InstantlyStatus,
		&i.InstantlySessionID,
		&i.InstantlyAuthUrl,
		&i.InstantlySessionExpiresAt,
		&i.InstantlyAccountID,
		&i.InstantlyError,
		&i.InstantlyConnectedAt,
		&i.InstantlyWarmup,
		&i.InstantlyWarmupEnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const succeedWorkspaceMailbox = `-- name: SucceedWorkspaceMailbox :exec
UPDATE workspace_mailboxes
SET status         = 'created',
    google_user_id = $1,
    provisioned_at = now(),
    error_code     = NULL,
    error_message  = NULL,
    updated_at     = now()
WHERE id = $2 AND status = 'pending'
`

type SucceedWorkspaceMailboxParams struct {
	GoogleUserID *string
	ID           uuid.UUID
}

func (q *Queries) SucceedWorkspaceMailbox(ctx context.Context, arg SucceedWorkspaceMailboxParams) error {
	_, err := q.db.Exec(ctx, succeedWorkspaceMailbox, arg.GoogleUserID, arg.ID)
	return err
}

const uncountWorkspaceMailboxAttempt = `-- name: UncountWorkspaceMailboxAttempt :exec
UPDATE workspace_mailboxes
SET create_attempts = greatest(create_attempts - 1, 0), updated_at = now()
WHERE id = $1 AND status = 'pending'
`

// An attempt Google refused without looking at it (throttled, or the credentials
// were refused) does not count.
func (q *Queries) UncountWorkspaceMailboxAttempt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, uncountWorkspaceMailboxAttempt, id)
	return err
}
